// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlazorBoilerplate.Api.SubContext;
using BlazorBoilerplate.Api.SubModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace BlazorBoilerplate.Api.SubContext.Configurations
{
    public partial class AntechBreedConfiguration : IEntityTypeConfiguration<AntechBreed>
    {
        public void Configure(EntityTypeBuilder<AntechBreed> entity)
        {
            entity.Property(e => e.BreedGuid).HasDefaultValueSql("(newid())");

            entity.Property(e => e.BreedCode).IsFixedLength();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<AntechBreed> entity);
    }
}
