// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlazorBoilerplate.Api.SubContext;
using BlazorBoilerplate.Api.SubModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace BlazorBoilerplate.Api.SubContext.Configurations
{
    public partial class ApptUserPrefConfiguration : IEntityTypeConfiguration<ApptUserPref>
    {
        public void Configure(EntityTypeBuilder<ApptUserPref> entity)
        {
            entity.HasKey(e => e.EzprefGuid)
                .HasName("PK_EZT_USER_PREFERENCES")
                .IsClustered(false);

            entity.Property(e => e.EzprefGuid).ValueGeneratedNever();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ApptUserPref> entity);
    }
}
