// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlazorBoilerplate.Api.SubContext;
using BlazorBoilerplate.Api.SubModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace BlazorBoilerplate.Api.SubContext.Configurations
{
    public partial class ApptTypeConfiguration : IEntityTypeConfiguration<ApptType>
    {
        public void Configure(EntityTypeBuilder<ApptType> entity)
        {
            entity.HasKey(e => e.ApptTypeGuid)
                .HasName("PK_EZT_APPOINTMENT_TYPES")
                .IsClustered(false);

            entity.HasIndex(e => new { e.PracticeVid, e.Name, e.DeleteGuid }, "ApptTypeName")
                .IsUnique()
                .HasFillFactor(90);

            entity.HasIndex(e => e.Deleted, "deld")
                .HasFillFactor(90);

            entity.HasIndex(e => e.GroupGuid, "groupg")
                .HasFillFactor(90);

            entity.Property(e => e.ApptTypeGuid).ValueGeneratedNever();

            entity.Property(e => e.PopupMessage).HasDefaultValueSql("('')");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ApptType> entity);
    }
}
