// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlazorBoilerplate.Api.SubContext;
using BlazorBoilerplate.Api.SubModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace BlazorBoilerplate.Api.SubContext.Configurations
{
    public partial class ApptResourceGroupConfiguration : IEntityTypeConfiguration<ApptResourceGroup>
    {
        public void Configure(EntityTypeBuilder<ApptResourceGroup> entity)
        {
            entity.HasKey(e => e.GroupGuid)
                .HasName("PK_EZT_RESOURCE_GROUPS")
                .IsClustered(false);

            entity.HasIndex(e => new { e.Name, e.DeleteGuid, e.PracticeVid }, "ResourceGroupName")
                .IsUnique()
                .HasFillFactor(90);

            entity.Property(e => e.GroupGuid).ValueGeneratedNever();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ApptResourceGroup> entity);
    }
}
