// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlazorBoilerplate.Api.SubContext;
using BlazorBoilerplate.Api.SubModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace BlazorBoilerplate.Api.SubContext.Configurations
{
    public partial class ArClientSettingConfiguration : IEntityTypeConfiguration<ArClientSetting>
    {
        public void Configure(EntityTypeBuilder<ArClientSetting> entity)
        {
            entity.HasKey(e => e.RevisionGuid)
                .IsClustered(false);

            entity.HasIndex(e => e.ClientGuid, "clientguid")
                .HasFillFactor(90);

            entity.Property(e => e.RevisionGuid).ValueGeneratedNever();

            entity.Property(e => e.AllowAr).HasDefaultValueSql("(1)");

            entity.Property(e => e.ChargeBf).HasDefaultValueSql("(1)");

            entity.Property(e => e.EmailAddress).HasDefaultValueSql("(' ')");

            entity.Property(e => e.HomePhone).HasDefaultValueSql("(' ')");

            entity.Property(e => e.StreetAddress1).HasDefaultValueSql("(' ')");

            entity.Property(e => e.StreetAddress2).HasDefaultValueSql("(' ')");

            entity.Property(e => e.WorkPhone).HasDefaultValueSql("(' ')");

            entity.Property(e => e.Zipcode).HasDefaultValueSql("(' ')");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ArClientSetting> entity);
    }
}
