// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlazorBoilerplate.Api.SubContext;
using BlazorBoilerplate.Api.SubModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace BlazorBoilerplate.Api.SubContext.Configurations
{
    public partial class ArGlobalSettingConfiguration : IEntityTypeConfiguration<ArGlobalSetting>
    {
        public void Configure(EntityTypeBuilder<ArGlobalSetting> entity)
        {
            entity.HasKey(e => e.RevisionGuid)
                .IsClustered(false);

            entity.Property(e => e.RevisionGuid).ValueGeneratedNever();

            entity.Property(e => e.ChargeBf).HasDefaultValueSql("(1)");

            entity.Property(e => e.ChargeInactiveInt).HasDefaultValueSql("(1)");

            entity.Property(e => e.DefChargeBf).HasDefaultValueSql("(1)");

            entity.Property(e => e.DefaultAllowAr).HasDefaultValueSql("(1)");

            entity.Property(e => e.DiscountDays).HasDefaultValueSql("(1)");

            entity.Property(e => e.DiscountPercent).HasDefaultValueSql("(1)");

            entity.Property(e => e.PmtPlanStmt).HasDefaultValueSql("('{00000000-0000-0000-0000-000000000000}')");

            entity.Property(e => e.SendPmtPlanStmts).HasDefaultValueSql("(1)");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ArGlobalSetting> entity);
    }
}
