// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlazorBoilerplate.Api.SubContext;
using BlazorBoilerplate.Api.SubModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace BlazorBoilerplate.Api.SubContext.Configurations
{
    public partial class ArStmtHistoryConfiguration : IEntityTypeConfiguration<ArStmtHistory>
    {
        public void Configure(EntityTypeBuilder<ArStmtHistory> entity)
        {
            entity.HasKey(e => e.StmtGuid)
                .IsClustered(false);

            entity.HasIndex(e => e.ClientGuid, "clientguid")
                .HasFillFactor(90);

            entity.HasIndex(e => e.DateTimeSelected, "dtsel")
                .HasFillFactor(90);

            entity.HasIndex(e => e.TransGuid, "transguid")
                .HasFillFactor(90);

            entity.Property(e => e.StmtGuid).ValueGeneratedNever();

            entity.Property(e => e.DiscountDueDate).HasDefaultValueSql("('1-1-2001')");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ArStmtHistory> entity);
    }
}
