// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlazorBoilerplate.Api.SubContext;
using BlazorBoilerplate.Api.SubModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace BlazorBoilerplate.Api.SubContext.Configurations
{
    public partial class BucketTotalsTaxisConfiguration : IEntityTypeConfiguration<BucketTotalsTaxis>
    {
        public void Configure(EntityTypeBuilder<BucketTotalsTaxis> entity)
        {
            entity.HasIndex(e => new { e.BucketDate, e.PracticeVid, e.TaxmRevGuid }, "BucketDate")
                .HasFillFactor(90);

            entity.Property(e => e.BucketTaxGuid).ValueGeneratedNever();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<BucketTotalsTaxis> entity);
    }
}
