// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlazorBoilerplate.Api.SubContext;
using BlazorBoilerplate.Api.SubModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace BlazorBoilerplate.Api.SubContext.Configurations
{
    public partial class CallLogConfiguration : IEntityTypeConfiguration<CallLog>
    {
        public void Configure(EntityTypeBuilder<CallLog> entity)
        {
            entity.HasIndex(e => e.CallGuid, "callg")
                .HasFillFactor(90);

            entity.HasIndex(e => e.CallGuid, "cg")
                .HasFillFactor(90);

            entity.HasIndex(e => e.ClientGuid, "clClient")
                .HasFillFactor(90);

            entity.HasIndex(e => e.DeletedGuid, "clDeleted")
                .HasFillFactor(90);

            entity.HasIndex(e => e.Revision, "clRevision")
                .HasFillFactor(90);

            entity.HasIndex(e => e.StartDateTime, "st")
                .HasFillFactor(90);

            entity.HasIndex(e => e.StartDateTime, "stdt")
                .HasFillFactor(90);

            entity.Property(e => e.RevisionGuid).ValueGeneratedNever();

            entity.Property(e => e.EgroupGuid).HasDefaultValueSql("('{00000000-0000-0000-0000-000000000000}')");

            entity.Property(e => e.EmployeeGuid).HasDefaultValueSql("('{00000000-0000-0000-0000-000000000000}')");

            entity.Property(e => e.EuserGuid).HasDefaultValueSql("('{00000000-0000-0000-0000-000000000000}')");

            entity.Property(e => e.StatusCode).HasDefaultValueSql("('{00000000-0000-0000-0000-000000000000}')");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CallLog> entity);
    }
}
