// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlazorBoilerplate.Api.SubContext;
using BlazorBoilerplate.Api.SubModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace BlazorBoilerplate.Api.SubContext.Configurations
{
    public partial class CensusPatientLogConfiguration : IEntityTypeConfiguration<CensusPatientLog>
    {
        public void Configure(EntityTypeBuilder<CensusPatientLog> entity)
        {
            entity.HasIndex(e => e.CpllGuid, "cpllg")
                .HasFillFactor(90);

            entity.HasIndex(e => e.Invoiced, "invd")
                .HasFillFactor(90);

            entity.HasIndex(e => e.PatientGuid, "patg")
                .HasFillFactor(90);

            entity.HasIndex(e => e.PracticeVid, "pv")
                .HasFillFactor(90);

            entity.HasIndex(e => e.Removed, "remd")
                .HasFillFactor(90);

            entity.HasIndex(e => e.ReasonRevGuid, "rrg")
                .HasFillFactor(90);

            entity.Property(e => e.CplGuid).ValueGeneratedNever();

            entity.Property(e => e.Invoiced).IsFixedLength();

            entity.Property(e => e.Removed).IsFixedLength();

            entity.Property(e => e.WaitStatus).HasDefaultValueSql("(1)");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CensusPatientLog> entity);
    }
}
