// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlazorBoilerplate.Api.SubContext;
using BlazorBoilerplate.Api.SubModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace BlazorBoilerplate.Api.SubContext.Configurations
{
    public partial class CensusPatientLogLocationConfiguration : IEntityTypeConfiguration<CensusPatientLogLocation>
    {
        public void Configure(EntityTypeBuilder<CensusPatientLogLocation> entity)
        {
            entity.Property(e => e.CpllGuid).ValueGeneratedNever();

            entity.Property(e => e.MovedByOp)
                .HasDefaultValueSql("('')")
                .IsFixedLength();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CensusPatientLogLocation> entity);
    }
}
