// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlazorBoilerplate.Api.SubContext;
using BlazorBoilerplate.Api.SubModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace BlazorBoilerplate.Api.SubContext.Configurations
{
    public partial class CertificatesTemplateConfiguration : IEntityTypeConfiguration<CertificatesTemplate>
    {
        public void Configure(EntityTypeBuilder<CertificatesTemplate> entity)
        {
            entity.HasKey(e => e.CertTempGuid)
                .IsClustered(false);

            entity.HasIndex(e => new { e.Name, e.DeletedGuid }, "NAME")
                .IsUnique()
                .HasFillFactor(90);

            entity.Property(e => e.CertTempGuid).ValueGeneratedNever();

            entity.Property(e => e.Copies).HasDefaultValueSql("(1)");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CertificatesTemplate> entity);
    }
}
