// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlazorBoilerplate.Api.SubContext;
using BlazorBoilerplate.Api.SubModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace BlazorBoilerplate.Api.SubContext.Configurations
{
    public partial class CommunicationMethodConfiguration : IEntityTypeConfiguration<CommunicationMethod>
    {
        public void Configure(EntityTypeBuilder<CommunicationMethod> entity)
        {
            entity.HasKey(e => e.CommunicationMethodGuid)
                .IsClustered(false);

            entity.Property(e => e.CommunicationMethodGuid).ValueGeneratedNever();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CommunicationMethod> entity);
    }
}
