// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlazorBoilerplate.Api.SubContext;
using BlazorBoilerplate.Api.SubModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace BlazorBoilerplate.Api.SubContext.Configurations
{
    public partial class ControlledSubstanceConfiguration : IEntityTypeConfiguration<ControlledSubstance>
    {
        public void Configure(EntityTypeBuilder<ControlledSubstance> entity)
        {
            entity.HasKey(e => e.CsGuid)
                .IsClustered(false);

            entity.Property(e => e.CsGuid).ValueGeneratedNever();

            entity.Property(e => e.CashierGuid).HasDefaultValueSql("('{00000000-0000-0000-0000-000000000000}')");

            entity.Property(e => e.NewManufacturerLotNum).HasDefaultValueSql("('')");

            entity.Property(e => e.NewNdcNumber).IsFixedLength();

            entity.Property(e => e.OldManufacturerLotNum).HasDefaultValueSql("('')");

            entity.Property(e => e.OldNdcNumber).IsFixedLength();

            entity.Property(e => e.StateAbbrev).IsFixedLength();

            entity.Property(e => e.TxProdGuid).HasDefaultValueSql("('{00000000-0000-0000-0000-000000000000}')");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ControlledSubstance> entity);
    }
}
