// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlazorBoilerplate.Api.SubContext;
using BlazorBoilerplate.Api.SubModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace BlazorBoilerplate.Api.SubContext.Configurations
{
    public partial class CorpTaskConfiguration : IEntityTypeConfiguration<CorpTask>
    {
        public void Configure(EntityTypeBuilder<CorpTask> entity)
        {
            entity.Property(e => e.TaskGuid).HasDefaultValueSql("(newid())");

            entity.Property(e => e.TaskCreated).HasDefaultValueSql("(getutcdate())");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CorpTask> entity);
    }
}
