// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlazorBoilerplate.Api.SubContext;
using BlazorBoilerplate.Api.SubModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace BlazorBoilerplate.Api.SubContext.Configurations
{
    public partial class DicomaeConfiguration : IEntityTypeConfiguration<Dicomae>
    {
        public void Configure(EntityTypeBuilder<Dicomae> entity)
        {
            entity.Property(e => e.KeyGuid).HasDefaultValueSql("(newid())");

            entity.Property(e => e.Imageq).HasDefaultValueSql("(1)");

            entity.Property(e => e.Relational).HasDefaultValueSql("(1)");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Dicomae> entity);
    }
}
