// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlazorBoilerplate.Api.SubContext;
using BlazorBoilerplate.Api.SubModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace BlazorBoilerplate.Api.SubContext.Configurations
{
    public partial class EcRptDetailConfiguration : IEntityTypeConfiguration<EcRptDetail>
    {
        public void Configure(EntityTypeBuilder<EcRptDetail> entity)
        {
            entity.HasIndex(e => e.EmployeeGuid, "IX_ECD_EMPLOYEE_GUID")
                .HasFillFactor(90);

            entity.HasIndex(e => e.EmpName, "IX_ECD_EmpName")
                .HasFillFactor(90);

            entity.HasIndex(e => e.ProdGuid, "IX_ECD_PROD_GUID")
                .HasFillFactor(90);

            entity.HasIndex(e => e.SessionGuid, "IX_ECD_SESSION_GUID")
                .HasFillFactor(90);

            entity.HasIndex(e => new { e.TxProdGuid, e.EmployeeGuid }, "IX_ECD_TXPROD_EMP")
                .HasFillFactor(90);

            entity.Property(e => e.EcDtlGuid).HasDefaultValueSql("(newid())");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<EcRptDetail> entity);
    }
}
