// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlazorBoilerplate.Api.SubContext;
using BlazorBoilerplate.Api.SubModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace BlazorBoilerplate.Api.SubContext.Configurations
{
    public partial class EfLabFieldConfiguration : IEntityTypeConfiguration<EfLabField>
    {
        public void Configure(EntityTypeBuilder<EfLabField> entity)
        {
            entity.HasKey(e => e.LabFieldGuid)
                .IsClustered(false);

            entity.HasIndex(e => new { e.FieldName, e.DeletedGuid }, "Name")
                .IsUnique()
                .HasFillFactor(90);

            entity.HasIndex(e => new { e.LabFieldGuid, e.FieldName, e.FieldType }, "fnt")
                .HasFillFactor(90);

            entity.Property(e => e.LabFieldGuid).ValueGeneratedNever();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<EfLabField> entity);
    }
}
