// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlazorBoilerplate.Api.SubContext;
using BlazorBoilerplate.Api.SubModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace BlazorBoilerplate.Api.SubContext.Configurations
{
    public partial class EformsFieldConfiguration : IEntityTypeConfiguration<EformsField>
    {
        public void Configure(EntityTypeBuilder<EformsField> entity)
        {
            entity.HasKey(e => e.FieldGuid)
                .HasName("PK_EFORM_FIELDS")
                .IsClustered(false);

            entity.HasIndex(e => e.EformGuid, "EF_GUID")
                .HasFillFactor(90);

            entity.Property(e => e.FieldGuid).ValueGeneratedNever();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<EformsField> entity);
    }
}
