// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlazorBoilerplate.Api.SubContext;
using BlazorBoilerplate.Api.SubModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace BlazorBoilerplate.Api.SubContext.Configurations
{
    public partial class EmailTopicConfiguration : IEntityTypeConfiguration<EmailTopic>
    {
        public void Configure(EntityTypeBuilder<EmailTopic> entity)
        {
            entity.HasIndex(e => new { e.Name, e.DeletedGuid, e.PracticeVid }, "emailname")
                .IsUnique()
                .HasFillFactor(90);

            entity.Property(e => e.TopicGuid).ValueGeneratedNever();

            entity.Property(e => e.DeletedGuid).HasDefaultValueSql("('{00000000-0000-0000-0000-000000000000}')");

            entity.Property(e => e.TemplateType).HasDefaultValueSql("('Client and Patient')");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<EmailTopic> entity);
    }
}
