// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlazorBoilerplate.Api.SubContext;
using BlazorBoilerplate.Api.SubModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace BlazorBoilerplate.Api.SubContext.Configurations
{
    public partial class EmployeesMConfiguration : IEntityTypeConfiguration<EmployeesM>
    {
        public void Configure(EntityTypeBuilder<EmployeesM> entity)
        {
            entity.HasKey(e => e.EmpRevisionGuid)
                .IsClustered(false);

            entity.HasIndex(e => new { e.FirstName, e.LastName, e.Prefix, e.DeleteGuid }, "EmployeeName")
                .IsUnique()
                .HasFillFactor(90);

            entity.HasIndex(e => new { e.Vid, e.DeleteGuid }, "EmployeeVID")
                .IsUnique()
                .HasFillFactor(90);

            entity.HasIndex(e => e.EmpRevisionGuid, "IDXP_EmployeesM_CL_EmpRevGuid")
                .IsClustered()
                .HasFillFactor(90);

            entity.HasIndex(e => new { e.EmployeeGuid, e.Deleted, e.Enable, e.Prefix, e.FirstName, e.LastName }, "IX_EmployeesM_EDEPFL")
                .HasFillFactor(90);

            entity.Property(e => e.EmpRevisionGuid).ValueGeneratedNever();

            entity.Property(e => e.AllowDiscounts).HasDefaultValueSql("(1)");

            entity.Property(e => e.Custom01).HasDefaultValueSql("('')");

            entity.Property(e => e.Custom02).HasDefaultValueSql("('')");

            entity.Property(e => e.Custom03).HasDefaultValueSql("('')");

            entity.Property(e => e.Custom04).HasDefaultValueSql("('')");

            entity.Property(e => e.Custom05).HasDefaultValueSql("('')");

            entity.Property(e => e.Custom06).HasDefaultValueSql("('')");

            entity.Property(e => e.Custom07).HasDefaultValueSql("('')");

            entity.Property(e => e.Custom08).HasDefaultValueSql("('')");

            entity.Property(e => e.Custom09).HasDefaultValueSql("('')");

            entity.Property(e => e.Custom10).HasDefaultValueSql("('')");

            entity.Property(e => e.IsProvider).HasDefaultValueSql("(1)");

            entity.Property(e => e.MayInvoice).HasDefaultValueSql("(1)");

            entity.Property(e => e.RefillEmpguid).HasDefaultValueSql("('{00000000-0000-0000-0000-000000000000}')");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<EmployeesM> entity);
    }
}
