// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlazorBoilerplate.Api.SubContext;
using BlazorBoilerplate.Api.SubModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace BlazorBoilerplate.Api.SubContext.Configurations
{
    public partial class EmployeeCommissionConfiguration : IEntityTypeConfiguration<EmployeeCommission>
    {
        public void Configure(EntityTypeBuilder<EmployeeCommission> entity)
        {
            entity.HasKey(e => e.EmpComGuid)
                .HasName("PK_EMPLOYEE_COMMISSON");

            entity.HasIndex(e => new { e.EmployeeGuid, e.PracticeVid }, "EmployeeGUID")
                .HasFillFactor(90);

            entity.HasIndex(e => e.ProdGuid, "ProdGUID")
                .HasFillFactor(90);

            entity.Property(e => e.EmpComGuid).HasDefaultValueSql("(newid())");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<EmployeeCommission> entity);
    }
}
