// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlazorBoilerplate.Api.SubContext;
using BlazorBoilerplate.Api.SubModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace BlazorBoilerplate.Api.SubContext.Configurations
{
    public partial class EstimateFlagsBConfiguration : IEntityTypeConfiguration<EstimateFlagsB>
    {
        public void Configure(EntityTypeBuilder<EstimateFlagsB> entity)
        {
            entity.Property(e => e.FlagGuid).ValueGeneratedNever();

            entity.Property(e => e.PrintXferProds).HasDefaultValueSql("(1)");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<EstimateFlagsB> entity);
    }
}
