// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlazorBoilerplate.Api.SubContext;
using BlazorBoilerplate.Api.SubModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace BlazorBoilerplate.Api.SubContext.Configurations
{
    public partial class EstimateConsent2Configuration : IEntityTypeConfiguration<EstimateConsent2>
    {
        public void Configure(EntityTypeBuilder<EstimateConsent2> entity)
        {
            entity.HasIndex(e => e.ClientGuid, "CLIENT_GUID")
                .HasFillFactor(90);

            entity.HasIndex(e => e.ConsentGuid, "CONSENT_GUID")
                .HasFillFactor(90);

            entity.HasIndex(e => e.EstimateGuid, "ESTIMATE_GUID")
                .HasFillFactor(90);

            entity.HasIndex(e => e.PatientGuid, "PATIENT_GUID")
                .HasFillFactor(90);

            entity.Property(e => e.EconsentGuid).ValueGeneratedNever();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<EstimateConsent2> entity);
    }
}
