// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlazorBoilerplate.Api.SubContext;
using BlazorBoilerplate.Api.SubModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace BlazorBoilerplate.Api.SubContext.Configurations
{
    public partial class HdAcctConfiguration : IEntityTypeConfiguration<HdAcct>
    {
        public void Configure(EntityTypeBuilder<HdAcct> entity)
        {
            entity.HasKey(e => e.HdGuid)
                .IsClustered(false);

            entity.Property(e => e.HdGuid).ValueGeneratedNever();

            entity.Property(e => e.InvoiceLogoText).HasDefaultValueSql("('')");

            entity.Property(e => e.Status).HasDefaultValueSql("('ORDERSSENT')");

            entity.Property(e => e.WebReferenceUrl).HasDefaultValueSql("('')");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<HdAcct> entity);
    }
}
