// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlazorBoilerplate.Api.SubContext;
using BlazorBoilerplate.Api.SubModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace BlazorBoilerplate.Api.SubContext.Configurations
{
    public partial class HdErrorConfiguration : IEntityTypeConfiguration<HdError>
    {
        public void Configure(EntityTypeBuilder<HdError> entity)
        {
            entity.HasKey(e => e.HdErrorGuid)
                .HasName("PK_HD_ERROR")
                .IsClustered(false);

            entity.Property(e => e.HdErrorGuid).ValueGeneratedNever();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<HdError> entity);
    }
}
