// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlazorBoilerplate.Api.SubContext;
using BlazorBoilerplate.Api.SubModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace BlazorBoilerplate.Api.SubContext.Configurations
{
    public partial class HdOptionConfiguration : IEntityTypeConfiguration<HdOption>
    {
        public void Configure(EntityTypeBuilder<HdOption> entity)
        {
            entity.HasKey(e => e.HdOptionGuid)
                .IsClustered(false);

            entity.Property(e => e.HdOptionGuid).ValueGeneratedNever();

            entity.Property(e => e.NextOrderNum).HasDefaultValueSql("(1)");

            entity.Property(e => e.Password).HasDefaultValueSql("('')");

            entity.Property(e => e.Secretkey).HasDefaultValueSql("('')");

            entity.Property(e => e.SubmitChoice).HasDefaultValueSql("(1)");

            entity.Property(e => e.Username).HasDefaultValueSql("('')");

            entity.Property(e => e.Vetid).HasDefaultValueSql("('')");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<HdOption> entity);
    }
}
