// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlazorBoilerplate.Api.SubContext;
using BlazorBoilerplate.Api.SubModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace BlazorBoilerplate.Api.SubContext.Configurations
{
    public partial class HdOrderConfiguration : IEntityTypeConfiguration<HdOrder>
    {
        public void Configure(EntityTypeBuilder<HdOrder> entity)
        {
            entity.HasKey(e => e.HdOrderGuid)
                .HasName("PK_HD_ORDERS_1");

            entity.Property(e => e.HdOrderGuid).HasDefaultValueSql("(newid())");

            entity.Property(e => e.InvoiceGuid).HasDefaultValueSql("('{00000000-0000-0000-0000-000000000000}')");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<HdOrder> entity);
    }
}
