// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlazorBoilerplate.Api.SubContext;
using BlazorBoilerplate.Api.SubModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace BlazorBoilerplate.Api.SubContext.Configurations
{
    public partial class IdvDynChangeConfiguration : IEntityTypeConfiguration<IdvDynChange>
    {
        public void Configure(EntityTypeBuilder<IdvDynChange> entity)
        {
            entity.HasIndex(e => e.Adm, "adm")
                .HasFillFactor(90);

            entity.HasIndex(e => e.DateTimeStamp, "dt")
                .HasFillFactor(90);

            entity.HasIndex(e => e.KeyGuid, "kg")
                .HasFillFactor(90);

            entity.HasIndex(e => e.ViewName, "vn")
                .HasFillFactor(90);

            entity.Property(e => e.ChangeGuid).HasDefaultValueSql("(newid())");

            entity.Property(e => e.Adm).IsFixedLength();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<IdvDynChange> entity);
    }
}
