// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlazorBoilerplate.Api.SubContext;
using BlazorBoilerplate.Api.SubModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace BlazorBoilerplate.Api.SubContext.Configurations
{
    public partial class InventoryInteractionConfiguration : IEntityTypeConfiguration<InventoryInteraction>
    {
        public void Configure(EntityTypeBuilder<InventoryInteraction> entity)
        {
            entity.HasKey(e => e.InteractGuid)
                .IsClustered(false);

            entity.HasIndex(e => e.InvmGuid1, "invm_guid1")
                .HasFillFactor(90);

            entity.HasIndex(e => e.InvmGuid2, "invm_guid2")
                .HasFillFactor(90);

            entity.Property(e => e.InteractGuid).ValueGeneratedNever();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<InventoryInteraction> entity);
    }
}
