// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlazorBoilerplate.Api.SubContext;
using BlazorBoilerplate.Api.SubModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace BlazorBoilerplate.Api.SubContext.Configurations
{
    public partial class InventoryItemsMConfiguration : IEntityTypeConfiguration<InventoryItemsM>
    {
        public void Configure(EntityTypeBuilder<InventoryItemsM> entity)
        {
            entity.HasKey(e => e.InvRevisionGuid)
                .IsClustered(false);

            entity.HasIndex(e => new { e.Barcode, e.DeleteGuid }, "InventoryBarcode")
                .IsUnique()
                .HasFillFactor(90);

            entity.HasIndex(e => new { e.InvmGuid, e.DeleteGuid }, "InventoryGUID")
                .IsUnique()
                .HasFillFactor(90);

            entity.HasIndex(e => new { e.Name, e.DeleteGuid }, "InventoryName")
                .IsUnique()
                .HasFillFactor(90);

            entity.HasIndex(e => new { e.Code, e.DeleteGuid }, "InvnetoryCode")
                .IsUnique()
                .HasFillFactor(90);

            entity.HasIndex(e => new { e.IcatGuid, e.Deleted, e.InvmGuid }, "_dta_index_INVENTORY_ITEMS_M_IDI")
                .HasFillFactor(90);

            entity.HasIndex(e => e.Deleted, "del")
                .HasFillFactor(90);

            entity.HasIndex(e => e.DeleteGuid, "delg")
                .HasFillFactor(90);

            entity.HasIndex(e => e.InvmGuid, "invm")
                .HasFillFactor(90);

            entity.Property(e => e.InvRevisionGuid).ValueGeneratedNever();

            entity.Property(e => e.Strength).HasDefaultValueSql("('')");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<InventoryItemsM> entity);
    }
}
