// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlazorBoilerplate.Api.SubContext;
using BlazorBoilerplate.Api.SubModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace BlazorBoilerplate.Api.SubContext.Configurations
{
    public partial class InventoryStorageConfiguration : IEntityTypeConfiguration<InventoryStorage>
    {
        public void Configure(EntityTypeBuilder<InventoryStorage> entity)
        {
            entity.HasKey(e => e.StorageGuid)
                .IsClustered(false);

            entity.HasIndex(e => new { e.Name, e.DeleteGuid, e.PracticeVid }, "StorageName")
                .IsUnique()
                .HasFillFactor(90);

            entity.HasIndex(e => e.ClientGuid, "client")
                .HasFillFactor(90);

            entity.Property(e => e.StorageGuid).ValueGeneratedNever();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<InventoryStorage> entity);
    }
}
