// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlazorBoilerplate.Api.SubContext;
using BlazorBoilerplate.Api.SubModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace BlazorBoilerplate.Api.SubContext.Configurations
{
    public partial class InvoiceLogConfiguration : IEntityTypeConfiguration<InvoiceLog>
    {
        public void Configure(EntityTypeBuilder<InvoiceLog> entity)
        {
            entity.HasIndex(e => e.ListProdGuid, "ListProdGUID")
                .HasFillFactor(90);

            entity.Property(e => e.LogGuid).ValueGeneratedNever();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<InvoiceLog> entity);
    }
}
