// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlazorBoilerplate.Api.SubContext;
using BlazorBoilerplate.Api.SubModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace BlazorBoilerplate.Api.SubContext.Configurations
{
    public partial class InvoiceSectionFieldConfiguration : IEntityTypeConfiguration<InvoiceSectionField>
    {
        public void Configure(EntityTypeBuilder<InvoiceSectionField> entity)
        {
            entity.HasIndex(e => e.SectionGuid, "IX_INV_SECT_FIELDS_SECTIONGUID")
                .HasFillFactor(90);

            entity.Property(e => e.EtFieldGuid).HasDefaultValueSql("(newid())");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<InvoiceSectionField> entity);
    }
}
