// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlazorBoilerplate.Api.SubContext;
using BlazorBoilerplate.Api.SubModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace BlazorBoilerplate.Api.SubContext.Configurations
{
    public partial class InvoicePracticeSettingConfiguration : IEntityTypeConfiguration<InvoicePracticeSetting>
    {
        public void Configure(EntityTypeBuilder<InvoicePracticeSetting> entity)
        {
            entity.HasKey(e => e.SettingsGuid)
                .IsClustered(false);

            entity.Property(e => e.SettingsGuid).ValueGeneratedNever();

            entity.Property(e => e.Addlocksproducts).HasDefaultValueSql("(1)");

            entity.Property(e => e.AfterHoursEnd).HasDefaultValueSql("('08:00:00 AM')");

            entity.Property(e => e.AfterHoursModeguid).HasDefaultValueSql("('{00000000-0000-0000-0000-000000000000}')");

            entity.Property(e => e.AfterHoursStart).HasDefaultValueSql("('08:00:00 PM')");

            entity.Property(e => e.AutoApplyCb).HasDefaultValueSql("(1)");

            entity.Property(e => e.BeginnerMode).HasDefaultValueSql("(1)");

            entity.Property(e => e.CashierTabSetting).HasDefaultValueSql("(1)");

            entity.Property(e => e.ClientOnlyWarning).HasDefaultValueSql("(1)");

            entity.Property(e => e.DefaultArPmtGuid).HasDefaultValueSql("('{00000000-0000-0000-0000-000000000000}')");

            entity.Property(e => e.DefaultPmtGuid).HasDefaultValueSql("('{00000000-0000-0000-0000-000000000000}')");

            entity.Property(e => e.DischargeGuid).HasDefaultValueSql("('{00000000-0000-0000-0000-000000000000}')");

            entity.Property(e => e.EmployeeFirst).HasDefaultValueSql("(1)");

            entity.Property(e => e.Maxaddscreen).HasDefaultValueSql("(1)");

            entity.Property(e => e.Maxmodscreen).HasDefaultValueSql("(1)");

            entity.Property(e => e.NextDailyReceiptNumber).HasDefaultValueSql("(1)");

            entity.Property(e => e.PleasePayWithAr).HasDefaultValueSql("(1)");

            entity.Property(e => e.PreviewBundles).HasDefaultValueSql("(1)");

            entity.Property(e => e.Restrictrxrefills).HasDefaultValueSql("(1)");

            entity.Property(e => e.ReviewInvoiceTemplate).HasDefaultValueSql("('{00000000-0000-0000-0000-000000000000}')");

            entity.Property(e => e.RxUseInvdate).HasDefaultValueSql("(1)");

            entity.Property(e => e.RxWarning).HasDefaultValueSql("(1)");

            entity.Property(e => e.WarnInactive).HasDefaultValueSql("(1)");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<InvoicePracticeSetting> entity);
    }
}
