// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlazorBoilerplate.Api.SubContext;
using BlazorBoilerplate.Api.SubModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace BlazorBoilerplate.Api.SubContext.Configurations
{
    public partial class InvoiceScriptConfiguration : IEntityTypeConfiguration<InvoiceScript>
    {
        public void Configure(EntityTypeBuilder<InvoiceScript> entity)
        {
            entity.Property(e => e.RevisionGuid).HasDefaultValueSql("(newid())");

            entity.Property(e => e.Code).HasDefaultValueSql("('')");

            entity.Property(e => e.PharmacyGuid).HasDefaultValueSql("('{00000000-0000-0000-0000-000000000000}')");

            entity.Property(e => e.ProdGuid).HasDefaultValueSql("('{00000000-0000-0000-0000-000000000000}')");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<InvoiceScript> entity);
    }
}
