// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlazorBoilerplate.Api.SubContext;
using BlazorBoilerplate.Api.SubModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace BlazorBoilerplate.Api.SubContext.Configurations
{
    public partial class InvoiceStatusConfiguration : IEntityTypeConfiguration<InvoiceStatus>
    {
        public void Configure(EntityTypeBuilder<InvoiceStatus> entity)
        {
            entity.HasIndex(e => e.ClientGuid, "isClientGUID")
                .HasFillFactor(90);

            entity.HasIndex(e => e.PracticeVid, "pv")
                .HasFillFactor(90);

            entity.Property(e => e.IsGuid).ValueGeneratedNever();

            entity.Property(e => e.TaskCashierGuid).HasDefaultValueSql("('{00000000-0000-0000-0000-000000000000}')");

            entity.Property(e => e.TaskRtf).HasDefaultValueSql("('')");

            entity.Property(e => e.TaskText).HasDefaultValueSql("('')");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<InvoiceStatus> entity);
    }
}
