// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlazorBoilerplate.Api.SubContext;
using BlazorBoilerplate.Api.SubModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace BlazorBoilerplate.Api.SubContext.Configurations
{
    public partial class InvoiceInventoryConfiguration : IEntityTypeConfiguration<InvoiceInventory>
    {
        public void Configure(EntityTypeBuilder<InvoiceInventory> entity)
        {
            entity.HasKey(e => e.InvoiceInvGuid)
                .IsClustered(false);

            entity.HasIndex(e => e.InvGuid, "inv_guid")
                .HasFillFactor(90);

            entity.HasIndex(e => e.InvmGuid, "invm")
                .HasFillFactor(90);

            entity.HasIndex(e => e.InvoiceProdGuid, "invoice_prod_guid")
                .HasFillFactor(90);

            entity.Property(e => e.InvoiceInvGuid).ValueGeneratedNever();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<InvoiceInventory> entity);
    }
}
