// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlazorBoilerplate.Api.SubContext;
using BlazorBoilerplate.Api.SubModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace BlazorBoilerplate.Api.SubContext.Configurations
{
    public partial class LabelsEnhConfiguration : IEntityTypeConfiguration<LabelsEnh>
    {
        public void Configure(EntityTypeBuilder<LabelsEnh> entity)
        {
            entity.HasKey(e => e.EnhLabelGuid)
                .IsClustered(false);

            entity.HasIndex(e => new { e.PracticeVid, e.Name }, "Name")
                .IsUnique()
                .HasFillFactor(90);

            entity.Property(e => e.EnhLabelGuid).ValueGeneratedNever();

            entity.Property(e => e.LabelType).HasDefaultValueSql("(1)");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<LabelsEnh> entity);
    }
}
