// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlazorBoilerplate.Api.SubContext;
using BlazorBoilerplate.Api.SubModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace BlazorBoilerplate.Api.SubContext.Configurations
{
    public partial class LogCheckConfiguration : IEntityTypeConfiguration<LogCheck>
    {
        public void Configure(EntityTypeBuilder<LogCheck> entity)
        {
            entity.HasKey(e => e.CheckId)
                .HasName("PK__LogChecks");

            entity.HasIndex(e => e.KeyRowGuid, "krg")
                .IsUnique()
                .HasFillFactor(90);

            entity.Property(e => e.CheckId).ValueGeneratedNever();

            entity.Property(e => e.CheckActive).HasDefaultValueSql("(1)");

            entity.Property(e => e.KeyRowGuid).HasDefaultValueSql("(newid())");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<LogCheck> entity);
    }
}
