// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlazorBoilerplate.Api.SubContext;
using BlazorBoilerplate.Api.SubModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace BlazorBoilerplate.Api.SubContext.Configurations
{
    public partial class PatientRecheckConfiguration : IEntityTypeConfiguration<PatientRecheck>
    {
        public void Configure(EntityTypeBuilder<PatientRecheck> entity)
        {
            entity.HasKey(e => e.PatientRecheckGuid)
                .IsClustered(false);

            entity.HasIndex(e => e.ClientGuid, "CLT_GUID")
                .HasFillFactor(90);

            entity.HasIndex(e => e.PatientGuid, "PAT_GUID")
                .HasFillFactor(90);

            entity.HasIndex(e => e.Completed, "compd")
                .HasFillFactor(90);

            entity.HasIndex(e => e.Deleted, "deld")
                .HasFillFactor(90);

            entity.HasIndex(e => e.InvoiceGuid, "ig")
                .HasFillFactor(90);

            entity.HasIndex(e => e.LockGuid, "lg")
                .HasFillFactor(90);

            entity.HasIndex(e => e.PrintOnInvoice, "poi")
                .HasFillFactor(90);

            entity.Property(e => e.PatientRecheckGuid).ValueGeneratedNever();

            entity.Property(e => e.EmployeeRevGuid).HasDefaultValueSql("('{00000000-0000-0000-0000-000000000000}')");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PatientRecheck> entity);
    }
}
