// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlazorBoilerplate.Api.SubContext;
using BlazorBoilerplate.Api.SubModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace BlazorBoilerplate.Api.SubContext.Configurations
{
    public partial class PatientDefaultConfiguration : IEntityTypeConfiguration<PatientDefault>
    {
        public void Configure(EntityTypeBuilder<PatientDefault> entity)
        {
            entity.HasKey(e => e.PkGuid)
                .IsClustered(false);

            entity.Property(e => e.PkGuid).ValueGeneratedNever();

            entity.Property(e => e.HealthPlanGuid).HasDefaultValueSql("('{00000000-0000-0000-0000-000000000000}')");

            entity.Property(e => e.TrainerGuid).HasDefaultValueSql("('{00000000-0000-0000-0000-000000000000}')");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PatientDefault> entity);
    }
}
