// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlazorBoilerplate.Api.SubContext;
using BlazorBoilerplate.Api.SubModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace BlazorBoilerplate.Api.SubContext.Configurations
{
    public partial class PpDbstatusSettingConfiguration : IEntityTypeConfiguration<PpDbstatusSetting>
    {
        public void Configure(EntityTypeBuilder<PpDbstatusSetting> entity)
        {
            entity.HasIndex(e => new { e.UserGuid, e.LocationId }, "userlocation")
                .IsUnique()
                .HasFillFactor(90);

            entity.Property(e => e.DbstatusGuid).ValueGeneratedNever();

            entity.Property(e => e.LocationId).IsFixedLength();

            entity.Property(e => e.TabDecl).HasDefaultValueSql("(1)");

            entity.Property(e => e.TabDef).HasDefaultValueSql("(1)");

            entity.Property(e => e.TabDx).HasDefaultValueSql("(1)");

            entity.Property(e => e.TabProblem).HasDefaultValueSql("(1)");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PpDbstatusSetting> entity);
    }
}
