// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlazorBoilerplate.Api.SubContext;
using BlazorBoilerplate.Api.SubModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace BlazorBoilerplate.Api.SubContext.Configurations
{
    public partial class PpDbviewContentConfiguration : IEntityTypeConfiguration<PpDbviewContent>
    {
        public void Configure(EntityTypeBuilder<PpDbviewContent> entity)
        {
            entity.HasIndex(e => new { e.UserGuid, e.LocationId, e.ViewType }, "UserLocation")
                .HasFillFactor(90);

            entity.Property(e => e.ContentGuid).ValueGeneratedNever();

            entity.Property(e => e.LocationId).IsFixedLength();

            entity.Property(e => e.ViewType).IsFixedLength();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PpDbviewContent> entity);
    }
}
