// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlazorBoilerplate.Api.SubContext;
using BlazorBoilerplate.Api.SubModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace BlazorBoilerplate.Api.SubContext.Configurations
{
    public partial class ProductsMConfiguration : IEntityTypeConfiguration<ProductsM>
    {
        public void Configure(EntityTypeBuilder<ProductsM> entity)
        {
            entity.HasKey(e => e.RevisionGuid)
                .IsClustered(false);

            entity.HasIndex(e => new { e.Code, e.DeleteGuid }, "Code")
                .IsUnique()
                .HasFillFactor(90);

            entity.HasIndex(e => new { e.Barcode, e.DeleteGuid }, "Product_Barcode")
                .IsUnique()
                .HasFillFactor(90);

            entity.HasIndex(e => new { e.Name, e.DeleteGuid }, "Product_Name")
                .IsUnique()
                .HasFillFactor(90);

            entity.HasIndex(e => e.Deleted, "del")
                .HasFillFactor(90);

            entity.HasIndex(e => e.PcatGuid, "pcatg")
                .HasFillFactor(90);

            entity.HasIndex(e => e.ProdmGuid, "prodm")
                .HasFillFactor(90);

            entity.Property(e => e.RevisionGuid).ValueGeneratedNever();

            entity.Property(e => e.Comment).HasDefaultValueSql("('')");

            entity.Property(e => e.DtypeGuid).HasDefaultValueSql("('{00000000-0000-0000-0000-000000000000}')");

            entity.Property(e => e.VetinsiteGuid).HasDefaultValueSql("('{00000000-0000-0000-0000-000000000000}')");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ProductsM> entity);
    }
}
