// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlazorBoilerplate.Api.SubContext;
using BlazorBoilerplate.Api.SubModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace BlazorBoilerplate.Api.SubContext.Configurations
{
    public partial class ProductSexConfiguration : IEntityTypeConfiguration<ProductSex>
    {
        public void Configure(EntityTypeBuilder<ProductSex> entity)
        {
            entity.Property(e => e.ProdSexGuid).ValueGeneratedNever();

            entity.Property(e => e.SexCode).IsFixedLength();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ProductSex> entity);
    }
}
