// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlazorBoilerplate.Api.SubContext;
using BlazorBoilerplate.Api.SubModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace BlazorBoilerplate.Api.SubContext.Configurations
{
    public partial class ProductConfiguration : IEntityTypeConfiguration<Product>
    {
        public void Configure(EntityTypeBuilder<Product> entity)
        {
            entity.HasKey(e => e.RevisionGuid)
                .IsClustered(false);

            entity.HasIndex(e => e.Available, "av")
                .HasFillFactor(90);

            entity.HasIndex(e => e.Deleted, "del")
                .HasFillFactor(90);

            entity.HasIndex(e => e.InvGuid, "inv_guid")
                .HasFillFactor(90);

            entity.HasIndex(e => e.InvmGuid, "invm")
                .HasFillFactor(90);

            entity.HasIndex(e => e.ProdGuid, "prod_guid")
                .HasFillFactor(90);

            entity.HasIndex(e => e.ProdmGuid, "prodm")
                .HasFillFactor(90);

            entity.HasIndex(e => e.PracticeVid, "pvid")
                .HasFillFactor(90);

            entity.Property(e => e.RevisionGuid).ValueGeneratedNever();

            entity.Property(e => e.DefComment).HasDefaultValueSql("('')");

            entity.Property(e => e.DefHiQty).HasDefaultValueSql("(1)");

            entity.Property(e => e.DefPriority).HasDefaultValueSql("(2)");

            entity.Property(e => e.SoapTab).HasDefaultValueSql("(2)");

            entity.Property(e => e.TimerGuid).HasDefaultValueSql("('{00000000-0000-0000-0000-000000000000}')");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Product> entity);
    }
}
