// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlazorBoilerplate.Api.SubContext;
using BlazorBoilerplate.Api.SubModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace BlazorBoilerplate.Api.SubContext.Configurations
{
    public partial class ProductReminderConfiguration : IEntityTypeConfiguration<ProductReminder>
    {
        public void Configure(EntityTypeBuilder<ProductReminder> entity)
        {
            entity.HasKey(e => e.ProdRemGuid)
                .IsClustered(false);

            entity.HasIndex(e => e.ProdGuid, "prod_guid")
                .HasFillFactor(90);

            entity.HasIndex(e => e.ProdmGuid, "prodm_guid")
                .HasFillFactor(90);

            entity.Property(e => e.ProdRemGuid).ValueGeneratedNever();

            entity.Property(e => e.WhenCode).HasDefaultValueSql("(1)");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ProductReminder> entity);
    }
}
