// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlazorBoilerplate.Api.SubContext;
using BlazorBoilerplate.Api.SubModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace BlazorBoilerplate.Api.SubContext.Configurations
{
    public partial class ProductConsentConfiguration : IEntityTypeConfiguration<ProductConsent>
    {
        public void Configure(EntityTypeBuilder<ProductConsent> entity)
        {
            entity.HasIndex(e => e.ConsentGuid, "ConsentGUID")
                .HasFillFactor(90);

            entity.HasIndex(e => e.ProdGuid, "ProdGUID")
                .HasFillFactor(90);

            entity.HasIndex(e => e.ProdmGuid, "ProdMGUID")
                .HasFillFactor(90);

            entity.Property(e => e.ProdConsentGuid).ValueGeneratedNever();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ProductConsent> entity);
    }
}
