// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlazorBoilerplate.Api.SubContext;
using BlazorBoilerplate.Api.SubModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace BlazorBoilerplate.Api.SubContext.Configurations
{
    public partial class ProductRxConfiguration : IEntityTypeConfiguration<ProductRx>
    {
        public void Configure(EntityTypeBuilder<ProductRx> entity)
        {
            entity.HasKey(e => e.PrxGuid)
                .IsClustered(false);

            entity.HasIndex(e => e.ProdGuid, "prod_guid")
                .HasFillFactor(90);

            entity.HasIndex(e => e.ProdmGuid, "prodm_guid")
                .HasFillFactor(90);

            entity.Property(e => e.PrxGuid).ValueGeneratedNever();

            entity.Property(e => e.ExpireDays).HasDefaultValueSql("(365)");

            entity.Property(e => e.GenericMsg).HasDefaultValueSql("('')");

            entity.Property(e => e.RemarkGuid).HasDefaultValueSql("('{00000000-0000-0000-0000-000000000000}')");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ProductRx> entity);
    }
}
