// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlazorBoilerplate.Api.SubContext;
using BlazorBoilerplate.Api.SubModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace BlazorBoilerplate.Api.SubContext.Configurations
{
    public partial class ProgExclusionConfiguration : IEntityTypeConfiguration<ProgExclusion>
    {
        public void Configure(EntityTypeBuilder<ProgExclusion> entity)
        {
            entity.HasIndex(e => new { e.Type, e.Progid }, "ptype")
                .IsUnique()
                .HasFillFactor(90);

            entity.Property(e => e.KeyGuid).HasDefaultValueSql("(newid())");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ProgExclusion> entity);
    }
}
