// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlazorBoilerplate.Api.SubContext;
using BlazorBoilerplate.Api.SubModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace BlazorBoilerplate.Api.SubContext.Configurations
{
    public partial class PurchaseOrderItemConfiguration : IEntityTypeConfiguration<PurchaseOrderItem>
    {
        public void Configure(EntityTypeBuilder<PurchaseOrderItem> entity)
        {
            entity.HasKey(e => e.PoItemGuid)
                .IsClustered(false);

            entity.HasIndex(e => e.InvmGuid, "invmg")
                .HasFillFactor(90);

            entity.HasIndex(e => e.PoGuid, "pog")
                .HasFillFactor(90);

            entity.Property(e => e.PoItemGuid).ValueGeneratedNever();

            entity.Property(e => e.Barcode).HasDefaultValueSql("(' ')");

            entity.Property(e => e.ManufacturerCode).HasDefaultValueSql("(' ')");

            entity.Property(e => e.NdcNumber).IsFixedLength();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PurchaseOrderItem> entity);
    }
}
