// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlazorBoilerplate.Api.SubContext;
using BlazorBoilerplate.Api.SubModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace BlazorBoilerplate.Api.SubContext.Configurations
{
    public partial class RecentClientConfiguration : IEntityTypeConfiguration<RecentClient>
    {
        public void Configure(EntityTypeBuilder<RecentClient> entity)
        {
            entity.HasKey(e => e.RcGuid)
                .HasName("RC_GUID_PK");

            entity.HasIndex(e => e.ClientGuid, "cg")
                .HasFillFactor(90);

            entity.HasIndex(e => e.ModDateTime, "mdt")
                .HasFillFactor(90);

            entity.HasIndex(e => e.PracticeVid, "pvid")
                .HasFillFactor(90);

            entity.Property(e => e.RcGuid).ValueGeneratedNever();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<RecentClient> entity);
    }
}
