// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlazorBoilerplate.Api.SubContext;
using BlazorBoilerplate.Api.SubModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace BlazorBoilerplate.Api.SubContext.Configurations
{
    public partial class RecheckConfiguration : IEntityTypeConfiguration<Recheck>
    {
        public void Configure(EntityTypeBuilder<Recheck> entity)
        {
            entity.HasKey(e => e.RecheckGuid)
                .IsClustered(false);

            entity.HasIndex(e => new { e.Name, e.DeletedGuid }, "NAME")
                .IsUnique()
                .HasFillFactor(90);

            entity.Property(e => e.RecheckGuid).ValueGeneratedNever();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Recheck> entity);
    }
}
