// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlazorBoilerplate.Api.SubContext;
using BlazorBoilerplate.Api.SubModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace BlazorBoilerplate.Api.SubContext.Configurations
{
    public partial class RemReplaceHistoryConfiguration : IEntityTypeConfiguration<RemReplaceHistory>
    {
        public void Configure(EntityTypeBuilder<RemReplaceHistory> entity)
        {
            entity.Property(e => e.RepHistGuid).ValueGeneratedNever();

            entity.Property(e => e.FieldName).HasDefaultValueSql("('')");

            entity.Property(e => e.OldGuid).HasDefaultValueSql("('{00000000-0000-0000-0000-000000000000}')");

            entity.Property(e => e.TableName).HasDefaultValueSql("('')");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<RemReplaceHistory> entity);
    }
}
