// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlazorBoilerplate.Api.SubContext;
using BlazorBoilerplate.Api.SubModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace BlazorBoilerplate.Api.SubContext.Configurations
{
    public partial class ReservationOptionConfiguration : IEntityTypeConfiguration<ReservationOption>
    {
        public void Configure(EntityTypeBuilder<ReservationOption> entity)
        {
            entity.Property(e => e.Guid).ValueGeneratedNever();

            entity.Property(e => e.MaxDaysInFutureAllowed).HasDefaultValueSql("(99999)");

            entity.Property(e => e.StartDateInPastWarn).HasDefaultValueSql("(1)");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ReservationOption> entity);
    }
}
