// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlazorBoilerplate.Api.SubContext;
using BlazorBoilerplate.Api.SubModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace BlazorBoilerplate.Api.SubContext.Configurations
{
    public partial class ReservationdayConfiguration : IEntityTypeConfiguration<Reservationday>
    {
        public void Configure(EntityTypeBuilder<Reservationday> entity)
        {
            entity.HasKey(e => e.ReservationDayGuid)
                .IsClustered(false);

            entity.HasIndex(e => e.ReservationGuid, "IX_RESERVATIONDAYS")
                .HasFillFactor(90);

            entity.HasIndex(e => e.CageGuid, "cageg")
                .HasFillFactor(90);

            entity.HasIndex(e => e.PracticeVid, "pvid")
                .HasFillFactor(90);

            entity.HasIndex(e => e.RsvDate, "rsvdt")
                .HasFillFactor(90);

            entity.Property(e => e.ReservationDayGuid).ValueGeneratedNever();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Reservationday> entity);
    }
}
