// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlazorBoilerplate.Api.SubContext;
using BlazorBoilerplate.Api.SubModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace BlazorBoilerplate.Api.SubContext.Configurations
{
    public partial class StatusnoteConfiguration : IEntityTypeConfiguration<Statusnote>
    {
        public void Configure(EntityTypeBuilder<Statusnote> entity)
        {
            entity.HasKey(e => e.StatusNotesGuid)
                .IsClustered(false);

            entity.HasIndex(e => e.Deleted, "del")
                .HasFillFactor(90);

            entity.HasIndex(e => e.NotesDate, "ndt")
                .HasFillFactor(90);

            entity.HasIndex(e => e.PatientGuid, "patg")
                .HasFillFactor(90);

            entity.Property(e => e.StatusNotesGuid).ValueGeneratedNever();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Statusnote> entity);
    }
}
