// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlazorBoilerplate.Api.SubContext;
using BlazorBoilerplate.Api.SubModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace BlazorBoilerplate.Api.SubContext.Configurations
{
    public partial class TransPatientConfiguration : IEntityTypeConfiguration<TransPatient>
    {
        public void Configure(EntityTypeBuilder<TransPatient> entity)
        {
            entity.HasKey(e => e.RevisionGuid)
                .IsClustered(false);

            entity.HasIndex(e => e.AmountUnpaid, "amtun")
                .HasFillFactor(90);

            entity.HasIndex(e => e.ClientGuid, "clientguid")
                .HasFillFactor(90);

            entity.HasIndex(e => e.InvoiceGuid, "invoiceguid")
                .HasFillFactor(90);

            entity.HasIndex(e => e.PatientGuid, "patientguid")
                .HasFillFactor(90);

            entity.HasIndex(e => e.Revised, "rev")
                .HasFillFactor(90);

            entity.HasIndex(e => e.RevCount, "revcnt")
                .HasFillFactor(90);

            entity.HasIndex(e => e.TransGuid, "transguid")
                .HasFillFactor(90);

            entity.HasIndex(e => e.TxAccountGuid, "txacctg")
                .HasFillFactor(90);

            entity.Property(e => e.RevisionGuid).ValueGeneratedNever();

            entity.Property(e => e.PatientVisit).HasDefaultValueSql("(1)");

            entity.Property(e => e.ReferralSourceGuid).HasDefaultValueSql("('{00000000-0000-0000-0000-000000000000}')");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TransPatient> entity);
    }
}
