// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlazorBoilerplate.Api.SubContext;
using BlazorBoilerplate.Api.SubModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace BlazorBoilerplate.Api.SubContext.Configurations
{
    public partial class TransInvoiceStatusConfiguration : IEntityTypeConfiguration<TransInvoiceStatus>
    {
        public void Configure(EntityTypeBuilder<TransInvoiceStatus> entity)
        {
            entity.HasIndex(e => e.ClientGuid, "ClientGUID")
                .HasFillFactor(90);

            entity.HasIndex(e => e.InvoiceGuid, "InvoiceGUID")
                .HasFillFactor(90);

            entity.HasIndex(e => e.TransGuid, "TransGUID")
                .HasFillFactor(90);

            entity.Property(e => e.TxStatusGuid).ValueGeneratedNever();

            entity.Property(e => e.TaskCashierGuid).HasDefaultValueSql("('{00000000-0000-0000-0000-000000000000}')");

            entity.Property(e => e.TaskRtf).HasDefaultValueSql("('')");

            entity.Property(e => e.TaskText).HasDefaultValueSql("('')");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TransInvoiceStatus> entity);
    }
}
