// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlazorBoilerplate.Api.SubContext;
using BlazorBoilerplate.Api.SubModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace BlazorBoilerplate.Api.SubContext.Configurations
{
    public partial class TransProductEmployeeConfiguration : IEntityTypeConfiguration<TransProductEmployee>
    {
        public void Configure(EntityTypeBuilder<TransProductEmployee> entity)
        {
            entity.HasKey(e => e.RevisionGuid)
                .IsClustered(false);

            entity.HasIndex(e => new { e.EmployeeGuid, e.PracticeVid }, "IX_TPE_EMP_PVID")
                .HasFillFactor(90);

            entity.HasIndex(e => e.PracticeVid, "IX_TPE_PRACTICEVID")
                .HasFillFactor(90);

            entity.HasIndex(e => e.TxProdGuid, "IX_TPE_TXPRODGUID")
                .HasFillFactor(90);

            entity.HasIndex(e => new { e.TxProdGuid, e.PracticeVid }, "IX_TPE_TXPROD_PVID")
                .HasFillFactor(90);

            entity.HasIndex(e => new { e.EmployeeGuid, e.CommPercent, e.TxProdGuid, e.InvoiceGuid, e.TransGuid, e.ClientGuid, e.PatientGuid }, "IX_TransProductEmployees_ECTITCP")
                .HasFillFactor(90);

            entity.HasIndex(e => new { e.EmployeeGuid, e.TransGuid, e.Removed }, "IX_TransProductEmployees_ETR")
                .HasFillFactor(90);

            entity.HasIndex(e => new { e.TransGuid, e.Removed, e.EmployeeGuid, e.CommPercent, e.TxProdGuid, e.ClientGuid, e.PatientGuid }, "IX_TransProductEmployees_TRECTCP")
                .HasFillFactor(90);

            entity.HasIndex(e => new { e.TransGuid, e.RevCount, e.EmployeeGuid, e.CommPercent, e.TxProdEmpGuid, e.TxProdGuid, e.ClientGuid, e.PatientGuid }, "IX_TransProductEmployees_TRECTTCP")
                .HasFillFactor(90);

            entity.HasIndex(e => new { e.TransGuid, e.TxProdGuid }, "IX_TransProductEmployees_TT")
                .IsClustered()
                .HasFillFactor(90);

            entity.HasIndex(e => new { e.TxProdEmpGuid, e.TxProdGuid, e.TransGuid, e.CommPercent, e.EmployeeGuid, e.RevCount, e.ClientGuid, e.PatientGuid }, "IX_TransProductEmployees_TTTCERCP")
                .HasFillFactor(90);

            entity.HasIndex(e => e.ClientGuid, "clientguid")
                .HasFillFactor(90);

            entity.HasIndex(e => e.EmployeeGuid, "employeeguid")
                .HasFillFactor(90);

            entity.HasIndex(e => e.InvoiceGuid, "invoiceguid")
                .HasFillFactor(90);

            entity.HasIndex(e => e.TxProdGuid, "invoiceprodguid")
                .HasFillFactor(90);

            entity.HasIndex(e => e.PatientGuid, "patientguid")
                .HasFillFactor(90);

            entity.HasIndex(e => e.RevCount, "rev_cnt")
                .HasFillFactor(90);

            entity.HasIndex(e => e.TransGuid, "transguid")
                .HasFillFactor(90);

            entity.HasIndex(e => e.TxProdEmpGuid, "tx_prod_emp")
                .HasFillFactor(90);

            entity.Property(e => e.RevisionGuid).ValueGeneratedNever();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TransProductEmployee> entity);
    }
}
