// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlazorBoilerplate.Api.SubContext;
using BlazorBoilerplate.Api.SubModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace BlazorBoilerplate.Api.SubContext.Configurations
{
    public partial class TransInventoryConfiguration : IEntityTypeConfiguration<TransInventory>
    {
        public void Configure(EntityTypeBuilder<TransInventory> entity)
        {
            entity.HasKey(e => e.RevisionGuid)
                .IsClustered(false);

            entity.HasIndex(e => e.ClientGuid, "clientguid")
                .HasFillFactor(90);

            entity.HasIndex(e => e.InvGuid, "invguid")
                .HasFillFactor(90);

            entity.HasIndex(e => e.InvmGuid, "invmguid")
                .HasFillFactor(90);

            entity.HasIndex(e => e.InvoiceGuid, "invoiceguid")
                .HasFillFactor(90);

            entity.HasIndex(e => e.PatientGuid, "patientguid")
                .HasFillFactor(90);

            entity.HasIndex(e => e.RevCount, "rev_cnt")
                .HasFillFactor(90);

            entity.HasIndex(e => e.Revised, "revd")
                .HasFillFactor(90);

            entity.HasIndex(e => e.TransGuid, "transguid")
                .HasFillFactor(90);

            entity.HasIndex(e => e.TxInvGuid, "txinv")
                .HasFillFactor(90);

            entity.HasIndex(e => e.TxProdGuid, "txprodguid")
                .HasFillFactor(90);

            entity.Property(e => e.RevisionGuid).ValueGeneratedNever();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TransInventory> entity);
    }
}
