// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlazorBoilerplate.Api.SubContext;
using BlazorBoilerplate.Api.SubModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace BlazorBoilerplate.Api.SubContext.Configurations
{
    public partial class TransTreatmentPlanConfiguration : IEntityTypeConfiguration<TransTreatmentPlan>
    {
        public void Configure(EntityTypeBuilder<TransTreatmentPlan> entity)
        {
            entity.HasIndex(e => e.ClientGuid, "ClientGUID")
                .HasFillFactor(90);

            entity.HasIndex(e => e.InvoiceGuid, "InvoiceGUID")
                .HasFillFactor(90);

            entity.HasIndex(e => e.PatientGuid, "PatientGUID")
                .HasFillFactor(90);

            entity.HasIndex(e => e.TransGuid, "TransGUID")
                .HasFillFactor(90);

            entity.HasIndex(e => e.TxProdGuid, "TxProdGUID")
                .HasFillFactor(90);

            entity.Property(e => e.TplanGuid).ValueGeneratedNever();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TransTreatmentPlan> entity);
    }
}
