// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlazorBoilerplate.Api.SubContext;
using BlazorBoilerplate.Api.SubModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace BlazorBoilerplate.Api.SubContext.Configurations
{
    public partial class UsersMrPrefConfiguration : IEntityTypeConfiguration<UsersMrPref>
    {
        public void Configure(EntityTypeBuilder<UsersMrPref> entity)
        {
            entity.HasKey(e => e.UserGuid)
                .IsClustered(false);

            entity.Property(e => e.UserGuid).ValueGeneratedNever();

            entity.Property(e => e.CCase).HasDefaultValueSql("(1)");

            entity.Property(e => e.CProb).HasDefaultValueSql("(1)");

            entity.Property(e => e.CSoap).HasDefaultValueSql("(1)");

            entity.Property(e => e.FontEdit).HasDefaultValueSql("('')");

            entity.Property(e => e.FontView).HasDefaultValueSql("('')");

            entity.Property(e => e.Height).HasDefaultValueSql("(1300)");

            entity.Property(e => e.LastTab).HasDefaultValueSql("(1)");

            entity.Property(e => e.PSoap).HasDefaultValueSql("(1)");

            entity.Property(e => e.ShowLabs).HasDefaultValueSql("(1)");

            entity.Property(e => e.ShowPics).HasDefaultValueSql("(1)");

            entity.Property(e => e.SizeEdit).HasDefaultValueSql("(10)");

            entity.Property(e => e.SizeView).HasDefaultValueSql("(2)");

            entity.Property(e => e.Width).HasDefaultValueSql("(7334)");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<UsersMrPref> entity);
    }
}
