// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlazorBoilerplate.Api.SubContext;
using BlazorBoilerplate.Api.SubModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace BlazorBoilerplate.Api.SubContext.Configurations
{
    public partial class UserConfiguration : IEntityTypeConfiguration<User>
    {
        public void Configure(EntityTypeBuilder<User> entity)
        {
            entity.HasKey(e => e.UserGuid)
                .IsClustered(false);

            entity.HasIndex(e => new { e.UserGuid, e.UserName }, "IDXP_Users_GUIDNAME")
                .HasFillFactor(90);

            entity.HasIndex(e => new { e.UserName, e.DeleteGuid, e.PracticeVid }, "UserNamePerPractice")
                .IsUnique()
                .HasFillFactor(90);

            entity.Property(e => e.UserGuid).ValueGeneratedNever();

            entity.Property(e => e.AltWkstGuid).HasDefaultValueSql("(newid())");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<User> entity);
    }
}
