// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlazorBoilerplate.Api.SubContext;
using BlazorBoilerplate.Api.SubModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace BlazorBoilerplate.Api.SubContext.Configurations
{
    public partial class VaccineFlagConfiguration : IEntityTypeConfiguration<VaccineFlag>
    {
        public void Configure(EntityTypeBuilder<VaccineFlag> entity)
        {
            entity.HasKey(e => e.VfGuid)
                .IsClustered(false);

            entity.Property(e => e.VfGuid).ValueGeneratedNever();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VaccineFlag> entity);
    }
}
