// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlazorBoilerplate.Api.SubContext;
using BlazorBoilerplate.Api.SubModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace BlazorBoilerplate.Api.SubContext.Configurations
{
    public partial class WorkstationPrinterConfiguration : IEntityTypeConfiguration<WorkstationPrinter>
    {
        public void Configure(EntityTypeBuilder<WorkstationPrinter> entity)
        {
            entity.HasKey(e => e.WpGuid)
                .IsClustered(false);

            entity.HasIndex(e => e.HcptrGuid, "hcpg")
                .HasFillFactor(90);

            entity.HasIndex(e => e.WorkstationGuid, "wrksg")
                .HasFillFactor(90);

            entity.Property(e => e.WpGuid).ValueGeneratedNever();

            entity.Property(e => e.DuplexEdge).HasDefaultValueSql("(1)");

            entity.Property(e => e.PaperSource1).HasDefaultValueSql("(1)");

            entity.Property(e => e.PaperSource2).HasDefaultValueSql("(1)");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<WorkstationPrinter> entity);
    }
}
