// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlazorBoilerplate.Api.SubContext;
using BlazorBoilerplate.Api.SubModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace BlazorBoilerplate.Api.SubContext.Configurations
{
    public partial class Workstation1Configuration : IEntityTypeConfiguration<Workstation1>
    {
        public void Configure(EntityTypeBuilder<Workstation1> entity)
        {
            entity.HasKey(e => e.WorkstationGuid)
                .IsClustered(false);

            entity.HasIndex(e => new { e.WorkstationGuid, e.Name }, "IDXP_Workstations_GUIDNAME")
                .HasFillFactor(90);

            entity.Property(e => e.WorkstationGuid).ValueGeneratedNever();

            entity.Property(e => e.CdGuid).HasDefaultValueSql("('{00000000-0000-0000-0000-000000000000}')");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Workstation1> entity);
    }
}
