// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("ACCT_BATCH_DETAILS")]
    public partial class AcctBatchDetail
    {
        [Key]
        [Column("GUID")]
        public Guid Guid { get; set; }
        [Column("ACCT_BATCH_DAYS_GUID")]
        public Guid AcctBatchDaysGuid { get; set; }
        [Column("ACCT_LINKS_GUID")]
        public Guid AcctLinksGuid { get; set; }
        [Column("AMOUNT", TypeName = "money")]
        public decimal Amount { get; set; }
    }
}