// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("ADDRESSES")]
    [Index(nameof(CityGuid), Name = "IX_ADDRESSES_CITY")]
    public partial class Address
    {
        [Key]
        [Column("ADDRESS_GUID")]
        public Guid AddressGuid { get; set; }
        [Required]
        [Column("ADDRESS1")]
        [StringLength(50)]
        [Unicode(false)]
        public string Address1 { get; set; }
        [Required]
        [Column("ADDRESS2")]
        [StringLength(50)]
        [Unicode(false)]
        public string Address2 { get; set; }
        [Column("CITY_GUID")]
        public Guid CityGuid { get; set; }
        [Required]
        [Column("POSTALCODE")]
        [StringLength(10)]
        [Unicode(false)]
        public string Postalcode { get; set; }
    }
}