// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("Appt_Applied_BlockDays")]
    public partial class ApptAppliedBlockDay
    {
        [Key]
        [Column("BD_APPLIED_GUID")]
        public Guid BdAppliedGuid { get; set; }
        [Column("BLOCKDAY_GUID")]
        public Guid BlockdayGuid { get; set; }
        [Column("RESOURCE_GUID")]
        public Guid ResourceGuid { get; set; }
        [Column("PRACTICE_VID")]
        public short PracticeVid { get; set; }
        [Column("APPLIED_DAY", TypeName = "datetime")]
        public DateTime AppliedDay { get; set; }
        [Column("CREATE_DATE_TIME", TypeName = "datetime")]
        public DateTime CreateDateTime { get; set; }
        [Column("CREATE_USER_GUID")]
        public Guid CreateUserGuid { get; set; }
        [Column("CREATE_WORKSTATION_GUID")]
        public Guid CreateWorkstationGuid { get; set; }
        [Column("WORK_FLAG")]
        public short WorkFlag { get; set; }
    }
}