// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("Appt_Resource_Groups")]
    public partial class ApptResourceGroup
    {
        [Key]
        [Column("GROUP_GUID")]
        public Guid GroupGuid { get; set; }
        [Required]
        [Column("NAME")]
        [StringLength(30)]
        [Unicode(false)]
        public string Name { get; set; }
        [Column("DELETE_GUID")]
        public Guid DeleteGuid { get; set; }
        [Required]
        [Column("DESCRIPTION")]
        [StringLength(500)]
        [Unicode(false)]
        public string Description { get; set; }
        [Column("PRACTICE_VID")]
        public short PracticeVid { get; set; }
        [Column("COLOR_GUID")]
        public Guid ColorGuid { get; set; }
        [Column("TIME_INTERVAL")]
        public short TimeInterval { get; set; }
        [Column("START_TIME", TypeName = "datetime")]
        public DateTime StartTime { get; set; }
        [Column("END_TIME", TypeName = "datetime")]
        public DateTime EndTime { get; set; }
        [Column("CREATE_DATE_TIME", TypeName = "datetime")]
        public DateTime CreateDateTime { get; set; }
        [Column("CREATE_USER_GUID")]
        public Guid CreateUserGuid { get; set; }
        [Column("CREATE_WORKSTATION_GUID")]
        public Guid CreateWorkstationGuid { get; set; }
        [Column("DELETED")]
        public bool Deleted { get; set; }
        [Column("SEQUENCE")]
        public int Sequence { get; set; }
        [Column("FRAME_BEVEL")]
        public short FrameBevel { get; set; }
        [Column("CAPTION_BEVEL")]
        public short CaptionBevel { get; set; }
    }
}