// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Keyless]
    [Table("Appt_Options")]
    public partial class ApptOption
    {
        [Column("EZT_OPT_GUID")]
        public Guid EztOptGuid { get; set; }
        [Column("PRACTICE_VID")]
        public short PracticeVid { get; set; }
        [Column("FIRSTDAY")]
        public short Firstday { get; set; }
        [Column("OPID_REQ")]
        public bool OpidReq { get; set; }
        [Column("OVERLAP_OK")]
        public bool OverlapOk { get; set; }
        [Column("ACCOUNT_REQ")]
        public bool AccountReq { get; set; }
        [Column("CREATE_DATE_TIME", TypeName = "datetime")]
        public DateTime CreateDateTime { get; set; }
        [Column("CREATE_USER_GUID")]
        public Guid CreateUserGuid { get; set; }
        [Column("CREATE_WORKSTATION_GUID")]
        public Guid CreateWorkstationGuid { get; set; }
        [Column("PRINT_SPEED")]
        public short PrintSpeed { get; set; }
        [Column("PRINT_DENSITY")]
        public short PrintDensity { get; set; }
        [Column("NUMCOPIES")]
        public short Numcopies { get; set; }
        [Required]
        [Column("HEADER1")]
        [StringLength(50)]
        [Unicode(false)]
        public string Header1 { get; set; }
        [Required]
        [Column("HEADER2")]
        [StringLength(50)]
        [Unicode(false)]
        public string Header2 { get; set; }
        [Required]
        [Column("HEADER3")]
        [StringLength(50)]
        [Unicode(false)]
        public string Header3 { get; set; }
        [Required]
        [Column("FOOTER")]
        [StringLength(50)]
        [Unicode(false)]
        public string Footer { get; set; }
        [Column("DEFAULT_STATUS_TYPE")]
        public Guid DefaultStatusType { get; set; }
        [Column("MOVE_STATUS_TYPE")]
        public Guid MoveStatusType { get; set; }
        [Column("DATE_OUTA_RANGE_WARN")]
        public bool DateOutaRangeWarn { get; set; }
        [Required]
        [Column("HIDE_RESOURCES")]
        public bool? HideResources { get; set; }
        [Column("APPT_BLOCKING_OPTION")]
        public byte ApptBlockingOption { get; set; }
        [Column("CENSUS_CHECKIN_STATUS_TYPE")]
        public Guid CensusCheckinStatusType { get; set; }
        [Required]
        [Column("ENABLE_DRAG_DROP")]
        public bool? EnableDragDrop { get; set; }
    }
}