// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("AR_GLOBAL_SETTINGS")]
    public partial class ArGlobalSetting
    {
        [Key]
        [Column("REVISION_GUID")]
        public Guid RevisionGuid { get; set; }
        [Column("REVISED")]
        public bool Revised { get; set; }
        [Column("SEND_STMTS_FLAG")]
        public bool SendStmtsFlag { get; set; }
        [Column("SEND_CREDIT_BAL_STMT_FLAG")]
        public bool SendCreditBalStmtFlag { get; set; }
        [Column("SEND_STMTS_MIN_BALANCE", TypeName = "money")]
        public decimal SendStmtsMinBalance { get; set; }
        [Column("CHARGE_INTEREST_FLAG")]
        public bool ChargeInterestFlag { get; set; }
        [Column("CHARGE_INTEREST_ON_INTEREST_FLAG")]
        public bool ChargeInterestOnInterestFlag { get; set; }
        [Column("MIN_INTEREST_CHARGE", TypeName = "money")]
        public decimal MinInterestCharge { get; set; }
        [Column("MONTHLY_INTEREST_RATE", TypeName = "money")]
        public decimal MonthlyInterestRate { get; set; }
        [Column("OLDER_THEN_DAYS")]
        public short OlderThenDays { get; set; }
        [Column("DEFAULT_STMT_TEMPLATE1_GUID")]
        public Guid DefaultStmtTemplate1Guid { get; set; }
        [Column("DEFAULT_STMT_TEMPLATE2_GUID")]
        public Guid DefaultStmtTemplate2Guid { get; set; }
        [Column("DEFAULT_STMT_TEMPLATE3_GUID")]
        public Guid DefaultStmtTemplate3Guid { get; set; }
        [Column("DEFAULT_STMT_TEMPLATE4_GUID")]
        public Guid DefaultStmtTemplate4Guid { get; set; }
        [Column("DEFAULT_CREDIT_LIMIT", TypeName = "money")]
        public decimal DefaultCreditLimit { get; set; }
        [Column("DEFAULT_SEND_STMTS_FLAG")]
        public bool DefaultSendStmtsFlag { get; set; }
        [Column("DEFAULT_CHARGE_INTEREST_FLAG")]
        public bool DefaultChargeInterestFlag { get; set; }
        [Column("CREATE_DATE_TIME", TypeName = "datetime")]
        public DateTime CreateDateTime { get; set; }
        [Column("CREATE_USER_GUID")]
        public Guid CreateUserGuid { get; set; }
        [Column("CREATE_WORKSTATION_GUID")]
        public Guid CreateWorkstationGuid { get; set; }
        [Column("DISCOUNT_DAYS")]
        public int DiscountDays { get; set; }
        [Column("DISCOUNT_PERCENT")]
        public short DiscountPercent { get; set; }
        [Column("DISCOUNT_OVERDUE")]
        public bool DiscountOverdue { get; set; }
        [Column("PMT_PLAN_STMT")]
        public Guid PmtPlanStmt { get; set; }
        [Required]
        [Column("SEND_PMT_PLAN_STMTS")]
        public bool? SendPmtPlanStmts { get; set; }
        [Column("USE_PMT_PLAN_TEMPLATE")]
        public bool UsePmtPlanTemplate { get; set; }
        [Column("SEND_INACTIVE_STMTS")]
        public bool SendInactiveStmts { get; set; }
        [Required]
        [Column("CHARGE_INACTIVE_INT")]
        public bool? ChargeInactiveInt { get; set; }
        [Column("MONTHLY_AGING")]
        public bool MonthlyAging { get; set; }
        [Column("MIN_INT_BAL", TypeName = "money")]
        public decimal MinIntBal { get; set; }
        [Required]
        [Column("DEFAULT_ALLOW_AR")]
        public bool? DefaultAllowAr { get; set; }
        [Column("FIXED_INT", TypeName = "money")]
        public decimal FixedInt { get; set; }
        [Required]
        [Column("CHARGE_BF")]
        public bool? ChargeBf { get; set; }
        [Required]
        [Column("DEF_CHARGE_BF")]
        public bool? DefChargeBf { get; set; }
        [Column("CHARGE_INACTIVE_BF")]
        public bool ChargeInactiveBf { get; set; }
        [Column("BF_OLDER_THEN_DAYS")]
        public int BfOlderThenDays { get; set; }
        [Column("BF_MIN_BALANCE", TypeName = "money")]
        public decimal BfMinBalance { get; set; }
    }
}