// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("BREEDS")]
    public partial class Breed
    {
        [Key]
        [Column("BREED_GUID")]
        public Guid BreedGuid { get; set; }
        [Required]
        [Column("BREED_NAME")]
        [StringLength(30)]
        [Unicode(false)]
        public string BreedName { get; set; }
        [Column("SPECIES_GUID")]
        public Guid SpeciesGuid { get; set; }
        [Column("PRACTICE_VID")]
        public short PracticeVid { get; set; }
        [Column("CREATE_DATE_TIME", TypeName = "datetime")]
        public DateTime CreateDateTime { get; set; }
        [Column("CREATE_USER_GUID")]
        public Guid CreateUserGuid { get; set; }
        [Column("CREATE_WORKSTATION_GUID")]
        public Guid CreateWorkstationGuid { get; set; }
        [Column("DELETED_GUID")]
        public Guid DeletedGuid { get; set; }
    }
}