// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("BUCKET_TOTALS_GLOBAL")]
    public partial class BucketTotalsGlobal
    {
        [Key]
        [Column("BUCKET_GLOBAL_GUID")]
        public Guid BucketGlobalGuid { get; set; }
        [Column("BUCKET_DATE", TypeName = "datetime")]
        public DateTime BucketDate { get; set; }
        [Column("NEW_CLTS")]
        public int NewClts { get; set; }
        [Column("NEW_PATS")]
        public int NewPats { get; set; }
        [Column("PRACTICE_VID")]
        public short PracticeVid { get; set; }
    }
}