// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("BUCKET_TOTALS")]
    public partial class BucketTotal
    {
        [Key]
        [Column("BUCKET_GUID")]
        public Guid BucketGuid { get; set; }
        [Column("BUCKET_DATE", TypeName = "datetime")]
        public DateTime BucketDate { get; set; }
        [Column("PRACTICE_VID")]
        public short PracticeVid { get; set; }
        [Column("NON_TAXABLE_SUBTOTAL", TypeName = "money")]
        public decimal NonTaxableSubtotal { get; set; }
        [Column("NON_TAXABLE_ADJUST", TypeName = "money")]
        public decimal NonTaxableAdjust { get; set; }
        [Column("NON_TAXABLE_PROD_DISC", TypeName = "money")]
        public decimal NonTaxableProdDisc { get; set; }
        [Column("NON_TAXABLE_INV_DISC", TypeName = "money")]
        public decimal NonTaxableInvDisc { get; set; }
        [Column("TAXABLE_SUBTOTAL", TypeName = "money")]
        public decimal TaxableSubtotal { get; set; }
        [Column("TAXABLE_ADJUST", TypeName = "money")]
        public decimal TaxableAdjust { get; set; }
        [Column("TAXABLE_PROD_DISC", TypeName = "money")]
        public decimal TaxableProdDisc { get; set; }
        [Column("TAXABLE_INV_DISC", TypeName = "money")]
        public decimal TaxableInvDisc { get; set; }
        [Column("TAX_COLLECTED", TypeName = "money")]
        public decimal TaxCollected { get; set; }
        [Column("WRITE_OFFS", TypeName = "money")]
        public decimal WriteOffs { get; set; }
        [Column("INTEREST_CHARGED", TypeName = "money")]
        public decimal InterestCharged { get; set; }
        [Column("NSF_FEES", TypeName = "money")]
        public decimal NsfFees { get; set; }
        [Column("NEW_CHARGES", TypeName = "money")]
        public decimal NewCharges { get; set; }
        [Column("PAYMENTS_ON_ACCT", TypeName = "money")]
        public decimal PaymentsOnAcct { get; set; }
        [Column("CREDIT_BALANCE_ADJUST", TypeName = "money")]
        public decimal CreditBalanceAdjust { get; set; }
        [Column("AR_ADJUST", TypeName = "money")]
        public decimal ArAdjust { get; set; }
        [Column("DOWN_PAYMENTS", TypeName = "money")]
        public decimal DownPayments { get; set; }
        [Column("INV_QTY")]
        public int InvQty { get; set; }
        [Column("INV_QTY_0TOT")]
        public int InvQty0tot { get; set; }
        [Column("INV_TOTAL", TypeName = "money")]
        public decimal InvTotal { get; set; }
        [Column("CLT_INV_QTY")]
        public int CltInvQty { get; set; }
        [Column("CLT_INV_QTY_0TOT")]
        public int CltInvQty0tot { get; set; }
        [Column("CLT_INV_TOTAL", TypeName = "money")]
        public decimal CltInvTotal { get; set; }
        [Column("PAT_INV_QTY")]
        public int PatInvQty { get; set; }
        [Column("PAT_INV_QTY_0TOT")]
        public int PatInvQty0tot { get; set; }
        [Column("PAT_INV_TOTAL", TypeName = "money")]
        public decimal PatInvTotal { get; set; }
        [Column("PAT_VIS_YES_QTY")]
        public int PatVisYesQty { get; set; }
        [Column("PAT_VIS_YES_QTY_0TOT")]
        public int PatVisYesQty0tot { get; set; }
        [Column("PAT_VIS_YES_TOTAL", TypeName = "money")]
        public decimal PatVisYesTotal { get; set; }
        [Column("PAT_VIS_NO_QTY")]
        public int PatVisNoQty { get; set; }
        [Column("PAT_VIS_NO_QTY_0TOT")]
        public int PatVisNoQty0tot { get; set; }
        [Column("PAT_VIS_NO_TOTAL", TypeName = "money")]
        public decimal PatVisNoTotal { get; set; }
        [Column("CREDIT_CHANGE_DISPENSED", TypeName = "money")]
        public decimal CreditChangeDispensed { get; set; }
        [Column("NSF_AMOUNT", TypeName = "money")]
        public decimal NsfAmount { get; set; }
        [Column("BILLING_FEES", TypeName = "money")]
        public decimal BillingFees { get; set; }
        [Column("BILLING_QTY")]
        public int BillingQty { get; set; }
    }
}