// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("CALL_LOG")]
    public partial class CallLog
    {
        [Key]
        [Column("REVISION_GUID")]
        public Guid RevisionGuid { get; set; }
        [Column("CALL_GUID")]
        public Guid CallGuid { get; set; }
        [Column("CLIENT_GUID")]
        public Guid ClientGuid { get; set; }
        [Column("START_DATE_TIME", TypeName = "datetime")]
        public DateTime StartDateTime { get; set; }
        [Column("END_DATE_TIME", TypeName = "datetime")]
        public DateTime EndDateTime { get; set; }
        [Required]
        [Column("CALL_TYPE")]
        [StringLength(200)]
        [Unicode(false)]
        public string CallType { get; set; }
        [Required]
        [Column("CALL_NOTES", TypeName = "text")]
        public string CallNotes { get; set; }
        [Required]
        [Column("CALL_RTF", TypeName = "text")]
        public string CallRtf { get; set; }
        [Column("CREATE_USER_GUID")]
        public Guid CreateUserGuid { get; set; }
        [Column("CREATE_WORKSTATION_GUID")]
        public Guid CreateWorkstationGuid { get; set; }
        [Column("CREATE_DATE_TIME", TypeName = "datetime")]
        public DateTime CreateDateTime { get; set; }
        [Column("DELETED_GUID")]
        public Guid DeletedGuid { get; set; }
        [Column("REVISION")]
        public int Revision { get; set; }
        [Column("EGROUP_GUID")]
        public Guid EgroupGuid { get; set; }
        [Column("EMPLOYEE_GUID")]
        public Guid EmployeeGuid { get; set; }
        [Column("STATUS_CODE")]
        public Guid StatusCode { get; set; }
        [Column("EUSER_GUID")]
        public Guid EuserGuid { get; set; }
    }
}