// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("CENSUS_PATIENT_LOG_LOCATIONS")]
    public partial class CensusPatientLogLocation
    {
        [Key]
        [Column("CPLL_GUID")]
        public Guid CpllGuid { get; set; }
        [Column("CPL_GUID")]
        public Guid CplGuid { get; set; }
        [Column("LOCATION_REV_GUID")]
        public Guid LocationRevGuid { get; set; }
        [Column("LOCATION_GUID")]
        public Guid LocationGuid { get; set; }
        [Column("LOCATION_COUNT")]
        public int LocationCount { get; set; }
        [Column("ARRIVAL_DATE_TIME", TypeName = "datetime")]
        public DateTime ArrivalDateTime { get; set; }
        [Column("ARRIVAL_USER_GUID")]
        public Guid ArrivalUserGuid { get; set; }
        [Column("ARRIVAL_WORKSTATION_GUID")]
        public Guid ArrivalWorkstationGuid { get; set; }
        [Column("ELAPSED_TIME")]
        public int? ElapsedTime { get; set; }
        [Required]
        [Column("MOVED_BY_OP")]
        [StringLength(5)]
        [Unicode(false)]
        public string MovedByOp { get; set; }
    }
}