// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("CENSUS_WORKSTATION")]
    public partial class CensusWorkstation
    {
        [Key]
        [Column("CENSUS_WKST_GUID")]
        public Guid CensusWkstGuid { get; set; }
        [Column("PRACTICE_VID")]
        public short PracticeVid { get; set; }
        [Column("WORKSTATION_GUID")]
        public Guid WorkstationGuid { get; set; }
        [Column("SHOW_PET_IMAGE")]
        public bool ShowPetImage { get; set; }
        [Column("SHOW_RES_IMAGE")]
        public bool ShowResImage { get; set; }
        [Column("LAYOUT_WIDTH")]
        public int LayoutWidth { get; set; }
        [Column("LAYOUT_HEIGHT")]
        public int LayoutHeight { get; set; }
        [Column("LOC_PER_ROW")]
        public int LocPerRow { get; set; }
        [Column("RESOURCE_HEIGHT")]
        public int ResourceHeight { get; set; }
        [Column("SAVED_LAYOUT", TypeName = "image")]
        public byte[] SavedLayout { get; set; }
    }
}