// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("CENSUS_USER_SETTINGS")]
    public partial class CensusUserSetting
    {
        [Key]
        [Column("USER_GUID")]
        public Guid UserGuid { get; set; }
        [Column("CV_STATUS_COLOR")]
        public int CvStatusColor { get; set; }
        [Column("CV_PATIENT_COLOR")]
        public int CvPatientColor { get; set; }
        [Column("CV_CLIENT_COLOR")]
        public int CvClientColor { get; set; }
        [Column("CV_CENSUS_COLOR")]
        public int CvCensusColor { get; set; }
        [Column("CV_APPT_COLOR")]
        public int CvApptColor { get; set; }
        [Column("CV_RESERV_COLOR")]
        public int CvReservColor { get; set; }
        [Column("CV_SHOW_CENSUS_INFO")]
        public bool CvShowCensusInfo { get; set; }
        [Column("CV_SHOW_APPT_INFO")]
        public bool CvShowApptInfo { get; set; }
        [Column("CV_SHOW_RESERV_INFO")]
        public bool CvShowReservInfo { get; set; }
    }
}