// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("CENSUS_LOCATIONS")]
    public partial class CensusLocation
    {
        [Key]
        [Column("REVISION_GUID")]
        public Guid RevisionGuid { get; set; }
        [Column("LOCATION_GUID")]
        public Guid LocationGuid { get; set; }
        [Required]
        [Column("LOCATION_NAME")]
        [StringLength(50)]
        [Unicode(false)]
        public string LocationName { get; set; }
        [Column("DELETE_GUID")]
        public Guid DeleteGuid { get; set; }
        [Column("PRACTICE_VID")]
        public short PracticeVid { get; set; }
        [Column("LOCATION_TYPE")]
        public short LocationType { get; set; }
        [Column("RESOURCE_TYPE")]
        public short ResourceType { get; set; }
        [Column("TITLE_BACK_COLOR")]
        public int TitleBackColor { get; set; }
        [Column("TITLE_FORE_COLOR")]
        public int TitleForeColor { get; set; }
        [Column("WORK_BACK_COLOR")]
        public int WorkBackColor { get; set; }
        [Required]
        [Column("FONT_NAME")]
        [StringLength(100)]
        [Unicode(false)]
        public string FontName { get; set; }
        [Column("FONT_SIZE")]
        public short FontSize { get; set; }
        [Column("FONT_BOLD")]
        public bool FontBold { get; set; }
        [Column("FONT_ITALICS")]
        public bool FontItalics { get; set; }
        [Column("FONT_3D")]
        public int Font3d { get; set; }
        [Column("CREATE_DATE_TIME", TypeName = "datetime")]
        public DateTime CreateDateTime { get; set; }
        [Column("CREATE_USER_GUID")]
        public Guid CreateUserGuid { get; set; }
        [Column("CREATE_WORKSTATION_GUID")]
        public Guid CreateWorkstationGuid { get; set; }
        [Column("USER_DEFINED_FIELD")]
        public Guid UserDefinedField { get; set; }
    }
}