// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("CERTIFICATES")]
    public partial class Certificate
    {
        [Key]
        [Column("CERTIFICATE_GUID")]
        public Guid CertificateGuid { get; set; }
        [Column("CERT_TEMP_GUID")]
        public Guid CertTempGuid { get; set; }
        [Column("TEMPLATE_GUID")]
        public Guid TemplateGuid { get; set; }
        [Column("TEMPLATE_REVISION_GUID")]
        public Guid TemplateRevisionGuid { get; set; }
        [Column("CLIENT_GUID")]
        public Guid ClientGuid { get; set; }
        [Column("PATIENT_GUID")]
        public Guid PatientGuid { get; set; }
        [Column("EMPLOYEE_GUID")]
        public Guid EmployeeGuid { get; set; }
        [Column("EMP_REVISION_GUID")]
        public Guid EmpRevisionGuid { get; set; }
        [Column("RH_GUID")]
        public Guid RhGuid { get; set; }
        [Column("PRACTICE_VID")]
        public short PracticeVid { get; set; }
        [Column("PRACTICE_DATE", TypeName = "datetime")]
        public DateTime PracticeDate { get; set; }
        [Column("DOC_NUMBER")]
        public int DocNumber { get; set; }
        [Column("PRINT_COUNT")]
        public int PrintCount { get; set; }
        [Column("CREATE_DATE_TIME", TypeName = "datetime")]
        public DateTime CreateDateTime { get; set; }
        [Column("CREATE_USER_GUID")]
        public Guid CreateUserGuid { get; set; }
        [Column("CREATE_WORKSTATION_GUID")]
        public Guid CreateWorkstationGuid { get; set; }
        [Column("DELETED_GUID")]
        public Guid DeletedGuid { get; set; }
        [Column("DELETED")]
        public bool Deleted { get; set; }
        [Column("PRINTED")]
        public bool Printed { get; set; }
        [Column("OWNER_GUID")]
        public Guid OwnerGuid { get; set; }
        [Required]
        [Column("CERT_TEMP_NAME")]
        [StringLength(40)]
        [Unicode(false)]
        public string CertTempName { get; set; }
        [Column("TEMPLATE_TYPE")]
        public short TemplateType { get; set; }
    }
}