// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("CLIENT_NOTES")]
    public partial class ClientNote
    {
        [Key]
        [Column("NOTE_GUID")]
        public Guid NoteGuid { get; set; }
        [Column("CLIENT_GUID")]
        public Guid ClientGuid { get; set; }
        [Required]
        [Column("CAPTION")]
        [StringLength(50)]
        [Unicode(false)]
        public string Caption { get; set; }
        [Column("NOTES", TypeName = "text")]
        public string Notes { get; set; }
        [Column("CREATE_DATE_TIME", TypeName = "datetime")]
        public DateTime CreateDateTime { get; set; }
        [Column("CREATE_USER_GUID")]
        public Guid CreateUserGuid { get; set; }
        [Column("CREATE_WORKSTATION_GUID")]
        public Guid CreateWorkstationGuid { get; set; }
        [Column("LOCK_FLAG")]
        public short LockFlag { get; set; }
        [Column("LOCK_GUID")]
        public Guid LockGuid { get; set; }
        [Required]
        [Column("LOCK_NAME")]
        [StringLength(30)]
        [Unicode(false)]
        public string LockName { get; set; }
        [Required]
        [Column("CREATE_USER_NAME")]
        [StringLength(30)]
        [Unicode(false)]
        public string CreateUserName { get; set; }
        [Column("RTF_NOTE", TypeName = "text")]
        public string RtfNote { get; set; }
    }
}