// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("CLIENT_AUTONUMBER")]
    public partial class ClientAutonumber
    {
        [Key]
        [Column("PK_GUID")]
        public Guid PkGuid { get; set; }
        [Column("NEXT_CLIENT_NUM")]
        public double NextClientNum { get; set; }
        [Column("MIN_CLIENT_NUM")]
        public double MinClientNum { get; set; }
        [Column("MAX_CLIENT_NUM")]
        public double MaxClientNum { get; set; }
    }
}