// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("CLIENTS")]
    [Index(nameof(ClientAccountId), nameof(DeletedUniqifyingGuid), Name = "IX_CLIENTS", IsUnique = true)]
    public partial class Client
    {
        [Key]
        [Column("CLIENT_GUID")]
        public Guid ClientGuid { get; set; }
        [Column("PRACTICE_VID")]
        public short PracticeVid { get; set; }
        [Required]
        [Column("CLIENT_ACCOUNT_ID")]
        [StringLength(11)]
        [Unicode(false)]
        public string ClientAccountId { get; set; }
        [Required]
        [Column("FIRST_NAME")]
        [StringLength(20)]
        [Unicode(false)]
        public string FirstName { get; set; }
        [Required]
        [Column("LAST_NAME")]
        [StringLength(25)]
        [Unicode(false)]
        public string LastName { get; set; }
        [Required]
        [Column("SPOUSE_FIRST_NAME")]
        [StringLength(20)]
        [Unicode(false)]
        public string SpouseFirstName { get; set; }
        [Required]
        [Column("SPOUSE_LAST_NAME")]
        [StringLength(25)]
        [Unicode(false)]
        public string SpouseLastName { get; set; }
        [Required]
        [Column("STREET_ADDRESS_1")]
        [StringLength(45)]
        [Unicode(false)]
        public string StreetAddress1 { get; set; }
        [Required]
        [Column("STREET_ADDRESS_2")]
        [StringLength(45)]
        [Unicode(false)]
        public string StreetAddress2 { get; set; }
        [Column("CITY_STATE_GUID")]
        public Guid CityStateGuid { get; set; }
        [Required]
        [Column("ZIPCODE")]
        [StringLength(10)]
        [Unicode(false)]
        public string Zipcode { get; set; }
        [Required]
        [Column("HOME_PHONE")]
        [StringLength(45)]
        [Unicode(false)]
        public string HomePhone { get; set; }
        [Required]
        [Column("WORK_PHONE")]
        [StringLength(45)]
        [Unicode(false)]
        public string WorkPhone { get; set; }
        [Required]
        [Column("EMAIL_ADDRESS")]
        [StringLength(255)]
        [Unicode(false)]
        public string EmailAddress { get; set; }
        [Column("ACTIVE")]
        public bool Active { get; set; }
        [Column("FIRST_VISIT", TypeName = "datetime")]
        public DateTime? FirstVisit { get; set; }
        [Column("LATEST_VISIT", TypeName = "datetime")]
        public DateTime? LatestVisit { get; set; }
        [Column("TOTAL_SALES", TypeName = "money")]
        public decimal TotalSales { get; set; }
        [Column("DELETED")]
        public bool Deleted { get; set; }
        [Required]
        [Column("SALUTATION")]
        [StringLength(55)]
        [Unicode(false)]
        public string Salutation { get; set; }
        [Column("CREATE_DATE_TIME", TypeName = "datetime")]
        public DateTime CreateDateTime { get; set; }
        [Column("CREATE_USER_GUID")]
        public Guid CreateUserGuid { get; set; }
        [Column("CREATE_WORKSTATION_GUID")]
        public Guid CreateWorkstationGuid { get; set; }
        [Required]
        [Column("MONETARY_FLAG")]
        [StringLength(15)]
        [Unicode(false)]
        public string MonetaryFlag { get; set; }
        [Column("DISCOUNT_GUID")]
        public Guid DiscountGuid { get; set; }
        [Required]
        [Column("COMMENT", TypeName = "text")]
        public string Comment { get; set; }
        [Column("TOTAL_VISITS")]
        public int TotalVisits { get; set; }
        [Column("REFERRAL_SOURCE_GUID")]
        public Guid ReferralSourceGuid { get; set; }
        [Column("TOTAL_REFERRALS")]
        public int TotalReferrals { get; set; }
        [Column("CLIENT_TYPE_GUID")]
        public Guid ClientTypeGuid { get; set; }
        [Column("IMAGE_GUID")]
        public Guid? ImageGuid { get; set; }
        [Required]
        [Column("SOCIAL_SECUR_NUM")]
        [StringLength(11)]
        [Unicode(false)]
        public string SocialSecurNum { get; set; }
        [Required]
        [Column("SPOUSE_SOCIAL_SECUR_NUM")]
        [StringLength(11)]
        [Unicode(false)]
        public string SpouseSocialSecurNum { get; set; }
        [Column("PREFERRED_COMM_METHOD_GUID")]
        public Guid PreferredCommMethodGuid { get; set; }
        [Required]
        [Column("FAX_NUMBER")]
        [StringLength(45)]
        [Unicode(false)]
        public string FaxNumber { get; set; }
        [Column("DELETED_UNIQIFYING_GUID")]
        public Guid DeletedUniqifyingGuid { get; set; }
        [Column("TAX_EXEMPT")]
        public bool TaxExempt { get; set; }
        [Required]
        [Column("DRIVER_LICENSE")]
        [StringLength(20)]
        [Unicode(false)]
        public string DriverLicense { get; set; }
        [Required]
        [Column("SPOUSE_DRIVER_LICENSE")]
        [StringLength(20)]
        [Unicode(false)]
        public string SpouseDriverLicense { get; set; }
        [Required]
        [Column("PREVIOUS_ACCOUNT_ID")]
        [StringLength(15)]
        [Unicode(false)]
        public string PreviousAccountId { get; set; }
        [Column("YTD_TOTAL_SALES", TypeName = "money")]
        public decimal YtdTotalSales { get; set; }
        [Column("YTD_TOTAL_REFERRALS")]
        public int YtdTotalReferrals { get; set; }
        [Column("YTD_TOTAL_VISITS")]
        public int YtdTotalVisits { get; set; }
    }
}