// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("CLIENT_LOCKS")]
    public partial class ClientLock
    {
        [Key]
        [Column("CLIENT_GUID")]
        public Guid ClientGuid { get; set; }
        [Column("USER_GUID")]
        public Guid UserGuid { get; set; }
        [Column("WORKSTATION_GUID")]
        public Guid WorkstationGuid { get; set; }
        [Column("SESSION_GUID")]
        public Guid SessionGuid { get; set; }
    }
}