// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("CLIENT_YTDS")]
    public partial class ClientYtd
    {
        [Key]
        [Column("KEY_GUID")]
        public Guid KeyGuid { get; set; }
        [Column("CLIENT_GUID")]
        public Guid ClientGuid { get; set; }
        [Column("FISCAL_YEAR")]
        public short FiscalYear { get; set; }
        [Column("YEAR_START", TypeName = "datetime")]
        public DateTime YearStart { get; set; }
        [Column("YEAR_END", TypeName = "datetime")]
        public DateTime YearEnd { get; set; }
        [Column("YTD_TOTAL_SALES", TypeName = "money")]
        public decimal YtdTotalSales { get; set; }
        [Column("YTD_TOTAL_REFERRALS")]
        public int YtdTotalReferrals { get; set; }
        [Column("YTD_TOTAL_VISITS")]
        public int YtdTotalVisits { get; set; }
        [Column("CREATE_DATE_TIME", TypeName = "datetime")]
        public DateTime CreateDateTime { get; set; }
        [Column("CREATE_USER_GUID")]
        public Guid CreateUserGuid { get; set; }
    }
}