// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("COMMUNICATION_METHODS")]
    public partial class CommunicationMethod
    {
        [Key]
        [Column("COMMUNICATION_METHOD_GUID")]
        public Guid CommunicationMethodGuid { get; set; }
        [Required]
        [Column("COMMUNICATION_METHOD")]
        [StringLength(30)]
        [Unicode(false)]
        public string CommunicationMethod1 { get; set; }
    }
}