// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("CONTROLLED_SUBSTANCES")]
    public partial class ControlledSubstance
    {
        [Key]
        [Column("CS_GUID")]
        public Guid CsGuid { get; set; }
        [Column("INVM_GUID")]
        public Guid InvmGuid { get; set; }
        [Column("INV_GUID")]
        public Guid InvGuid { get; set; }
        [Column("PRACTICE_VID")]
        public short PracticeVid { get; set; }
        [Column("ADJUSTMENT_TYPE")]
        public short AdjustmentType { get; set; }
        [Column("OLD_STORAGE_GUID")]
        public Guid OldStorageGuid { get; set; }
        [Column("NEW_STORAGE_GUID")]
        public Guid NewStorageGuid { get; set; }
        [Column("OLD_LOT_GUID")]
        public Guid OldLotGuid { get; set; }
        [Column("NEW_LOT_GUID")]
        public Guid NewLotGuid { get; set; }
        [Column("OLD_VENDOR_GUID")]
        public Guid OldVendorGuid { get; set; }
        [Column("NEW_VENDOR_GUID")]
        public Guid NewVendorGuid { get; set; }
        [Column("CLIENT_GUID")]
        public Guid ClientGuid { get; set; }
        [Column("PATIENT_GUID")]
        public Guid PatientGuid { get; set; }
        [Column("ENTRY_DATETIME", TypeName = "datetime")]
        public DateTime EntryDatetime { get; set; }
        [Required]
        [Column("USER_NOTES")]
        [StringLength(1000)]
        [Unicode(false)]
        public string UserNotes { get; set; }
        [Required]
        [Column("OLD_UNIT_OF_MEASURE")]
        [StringLength(20)]
        [Unicode(false)]
        public string OldUnitOfMeasure { get; set; }
        [Required]
        [Column("NEW_UNIT_OF_MEASURE")]
        [StringLength(20)]
        [Unicode(false)]
        public string NewUnitOfMeasure { get; set; }
        [Column("QTY_CHANGE", TypeName = "money")]
        public decimal QtyChange { get; set; }
        [Column("OLD_QTY", TypeName = "money")]
        public decimal OldQty { get; set; }
        [Column("NEW_QTY", TypeName = "money")]
        public decimal NewQty { get; set; }
        [Column("OLD_DECIMALS")]
        public short OldDecimals { get; set; }
        [Column("NEW_DECIMALS")]
        public short NewDecimals { get; set; }
        [Column("COST_CHANGE", TypeName = "money")]
        public decimal CostChange { get; set; }
        [Column("OLD_COST", TypeName = "money")]
        public decimal OldCost { get; set; }
        [Column("NEW_COST", TypeName = "money")]
        public decimal NewCost { get; set; }
        [Column("OLD_EMP_REVISION_GUID")]
        public Guid OldEmpRevisionGuid { get; set; }
        [Column("OLD_EMPLOYEE_GUID")]
        public Guid OldEmployeeGuid { get; set; }
        [Required]
        [Column("OLD_EMPLOYEE_NAME")]
        [StringLength(50)]
        [Unicode(false)]
        public string OldEmployeeName { get; set; }
        [Required]
        [Column("OLD_EMPLOYEE_DEA_NUMBER")]
        [StringLength(30)]
        [Unicode(false)]
        public string OldEmployeeDeaNumber { get; set; }
        [Column("NEW_EMP_REVISION_GUID")]
        public Guid NewEmpRevisionGuid { get; set; }
        [Column("NEW_EMPLOYEE_GUID")]
        public Guid NewEmployeeGuid { get; set; }
        [Required]
        [Column("NEW_EMPLOYEE_NAME")]
        [StringLength(50)]
        [Unicode(false)]
        public string NewEmployeeName { get; set; }
        [Required]
        [Column("NEW_EMPLOYEE_DEA_NUMBER")]
        [StringLength(30)]
        [Unicode(false)]
        public string NewEmployeeDeaNumber { get; set; }
        [Required]
        [Column("OLD_ITEM_NAME")]
        [StringLength(40)]
        [Unicode(false)]
        public string OldItemName { get; set; }
        [Required]
        [Column("NEW_ITEM_NAME")]
        [StringLength(40)]
        [Unicode(false)]
        public string NewItemName { get; set; }
        [Required]
        [Column("DETAILS")]
        [StringLength(250)]
        [Unicode(false)]
        public string Details { get; set; }
        [Required]
        [Column("OLD_NDC_NUMBER")]
        [StringLength(13)]
        [Unicode(false)]
        public string OldNdcNumber { get; set; }
        [Required]
        [Column("NEW_NDC_NUMBER")]
        [StringLength(13)]
        [Unicode(false)]
        public string NewNdcNumber { get; set; }
        [Column("DAYS_MEDS_WILL_LAST")]
        public short DaysMedsWillLast { get; set; }
        [Required]
        [Column("RX_NUMBER")]
        [StringLength(20)]
        [Unicode(false)]
        public string RxNumber { get; set; }
        [Required]
        [Column("SS_NUMBER")]
        [StringLength(20)]
        [Unicode(false)]
        public string SsNumber { get; set; }
        [Required]
        [Column("DRIVER_LICENSE")]
        [StringLength(20)]
        [Unicode(false)]
        public string DriverLicense { get; set; }
        [Required]
        [Column("CLIENT_FIRST_NAME")]
        [StringLength(20)]
        [Unicode(false)]
        public string ClientFirstName { get; set; }
        [Required]
        [Column("CLIENT_LAST_NAME")]
        [StringLength(25)]
        [Unicode(false)]
        public string ClientLastName { get; set; }
        [Required]
        [Column("PATIENT_NAME")]
        [StringLength(50)]
        [Unicode(false)]
        public string PatientName { get; set; }
        [Required]
        [Column("ADDRESS")]
        [StringLength(50)]
        [Unicode(false)]
        public string Address { get; set; }
        [Required]
        [Column("CITY")]
        [StringLength(30)]
        [Unicode(false)]
        public string City { get; set; }
        [Required]
        [Column("STATE_ABBREV")]
        [StringLength(2)]
        [Unicode(false)]
        public string StateAbbrev { get; set; }
        [Required]
        [Column("POSTAL_CODE")]
        [StringLength(15)]
        [Unicode(false)]
        public string PostalCode { get; set; }
        [Column("BIRTHDATE", TypeName = "datetime")]
        public DateTime Birthdate { get; set; }
        [Required]
        [Column("HOME_PHONE")]
        [StringLength(45)]
        [Unicode(false)]
        public string HomePhone { get; set; }
        [Column("NEW_RX")]
        public bool NewRx { get; set; }
        [Column("NUM_OF_REFILLS")]
        public short NumOfRefills { get; set; }
        [Column("CREATE_DATE_TIME", TypeName = "datetime")]
        public DateTime CreateDateTime { get; set; }
        [Column("CREATE_USER_GUID")]
        public Guid CreateUserGuid { get; set; }
        [Column("CREATE_WORKSTATION_GUID")]
        public Guid CreateWorkstationGuid { get; set; }
        [Column("WASTAGE_QTY", TypeName = "money")]
        public decimal WastageQty { get; set; }
        [Required]
        [Column("OLD_MANUFACTURER_LOT_NUM")]
        [StringLength(50)]
        [Unicode(false)]
        public string OldManufacturerLotNum { get; set; }
        [Required]
        [Column("NEW_MANUFACTURER_LOT_NUM")]
        [StringLength(50)]
        [Unicode(false)]
        public string NewManufacturerLotNum { get; set; }
        [Column("CASHIER_GUID")]
        public Guid CashierGuid { get; set; }
        [Column("ENTRY_NUM")]
        public int EntryNum { get; set; }
        [Column("TX_PROD_GUID")]
        public Guid TxProdGuid { get; set; }
    }
}