// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("CORP_IMAGE_TEXT")]
    public partial class CorpImageText
    {
        [Key]
        [Column("KEY_GUID")]
        public Guid KeyGuid { get; set; }
        [Column("REVISION_GUID")]
        public Guid RevisionGuid { get; set; }
        [Column("IMAGE_REVISION_GUID")]
        public Guid ImageRevisionGuid { get; set; }
        [Required]
        [Column("TEXT", TypeName = "text")]
        public string Text { get; set; }
        [Column("FONT_BOLD")]
        public bool FontBold { get; set; }
        [Column("FONT_ITALIC")]
        public bool FontItalic { get; set; }
        [Required]
        [Column("FONT_NAME")]
        [StringLength(500)]
        [Unicode(false)]
        public string FontName { get; set; }
        [Column("FONT_SIZE")]
        public int FontSize { get; set; }
        [Column("FONT_COLOR")]
        public int FontColor { get; set; }
        [Column("TEXT_ALIGN")]
        public int TextAlign { get; set; }
        [Column("TEXT_TOP")]
        public int TextTop { get; set; }
        [Column("TEXT_LEFT")]
        public int TextLeft { get; set; }
        [Column("TEXT_WIDTH")]
        public int TextWidth { get; set; }
        [Column("TEXT_HEIGHT")]
        public int TextHeight { get; set; }
        [Column("HAS_BORDER")]
        public bool HasBorder { get; set; }
        [Column("BORDER_COLOR")]
        public int BorderColor { get; set; }
        [Column("IS_FILLED")]
        public bool IsFilled { get; set; }
        [Column("FILL_COLOR")]
        public int FillColor { get; set; }
    }
}