// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    public partial class CorpPractice
    {
        [Key]
        [Column("PracticeGUID")]
        public Guid PracticeGuid { get; set; }
        [Column("ServerGUID")]
        public Guid ServerGuid { get; set; }
        [Column("RemoteGUID")]
        public Guid RemoteGuid { get; set; }
        [Column("DatabaseGUID")]
        public Guid DatabaseGuid { get; set; }
        [Column("RemoteDatabaseGUID")]
        public Guid RemoteDatabaseGuid { get; set; }
        [Column("PracticeVID")]
        public short PracticeVid { get; set; }
        [Column("DeletedGUID")]
        public Guid DeletedGuid { get; set; }
        [Column("NewPracticeVID")]
        public short NewPracticeVid { get; set; }
        [Required]
        [StringLength(256)]
        [Unicode(false)]
        public string PracticeName { get; set; }
        [Column("PricingModelGUID")]
        public Guid PricingModelGuid { get; set; }
        [Column("TaxingModelGUID")]
        public Guid TaxingModelGuid { get; set; }
        [Column("AttributeModelGUID")]
        public Guid AttributeModelGuid { get; set; }
        public Guid EmployeeComModelGuid { get; set; }
    }
}