// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Keyless]
    [Table("CorpDatesAdded")]
    public partial class CorpDatesAdded
    {
        [Column("PracticeGUID")]
        public Guid PracticeGuid { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DateAdded { get; set; }
        [Required]
        [StringLength(1000)]
        [Unicode(false)]
        public string FranchiseName { get; set; }
    }
}