// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("CORP_MR_VIEW")]
    public partial class CorpMrView
    {
        [Key]
        [Column("ROW_KEY_GUID")]
        public Guid RowKeyGuid { get; set; }
        [Column("KEY_GUID")]
        public Guid KeyGuid { get; set; }
        [Required]
        [Column("MR_TYPE")]
        [StringLength(50)]
        [Unicode(false)]
        public string MrType { get; set; }
        [Required]
        [Column("DISPLAY_NAME")]
        [StringLength(100)]
        [Unicode(false)]
        public string DisplayName { get; set; }
        [Required]
        [Column("DISPLAY_COLOR")]
        [StringLength(50)]
        [Unicode(false)]
        public string DisplayColor { get; set; }
        [Column("CLICK_GUID")]
        public Guid ClickGuid { get; set; }
        [Column("REVISION_GUID")]
        public Guid RevisionGuid { get; set; }
        [Column("MR_GUID")]
        public Guid MrGuid { get; set; }
        [Column("MR_DATE_TIME", TypeName = "datetime")]
        public DateTime MrDateTime { get; set; }
        [Column("CREATE_DATE_TIME", TypeName = "datetime")]
        public DateTime CreateDateTime { get; set; }
        [Required]
        [Column("TITLE")]
        [StringLength(4000)]
        [Unicode(false)]
        public string Title { get; set; }
        [Column("TEXT1", TypeName = "text")]
        public string Text1 { get; set; }
        [Column("TEXT2", TypeName = "text")]
        public string Text2 { get; set; }
        [Column("TEXT3", TypeName = "text")]
        public string Text3 { get; set; }
        [Column("TEXT4", TypeName = "text")]
        public string Text4 { get; set; }
        [Required]
        [Column("LABEL1")]
        [StringLength(100)]
        [Unicode(false)]
        public string Label1 { get; set; }
        [Required]
        [Column("LABEL2")]
        [StringLength(100)]
        [Unicode(false)]
        public string Label2 { get; set; }
        [Required]
        [Column("LABEL3")]
        [StringLength(100)]
        [Unicode(false)]
        public string Label3 { get; set; }
        [Required]
        [Column("LABEL4")]
        [StringLength(100)]
        [Unicode(false)]
        public string Label4 { get; set; }
        [Column("IMAGE1")]
        public Guid Image1 { get; set; }
        [Column("IMAGE2")]
        public Guid Image2 { get; set; }
        [Column("IMAGE3")]
        public Guid Image3 { get; set; }
        [Column("IMAGE4")]
        public Guid Image4 { get; set; }
        [Column("M_CASE_GUID")]
        public Guid MCaseGuid { get; set; }
        [Required]
        [Column("CASE_NUMBER_TEXT")]
        [StringLength(100)]
        [Unicode(false)]
        public string CaseNumberText { get; set; }
        [Column("M_PROBLEM_GUID")]
        public Guid MProblemGuid { get; set; }
        [Required]
        [Column("PROBLEM_NUMBER_TEXT")]
        [StringLength(100)]
        [Unicode(false)]
        public string ProblemNumberText { get; set; }
        [Required]
        [Column("M_USER_NAME")]
        [StringLength(100)]
        [Unicode(false)]
        public string MUserName { get; set; }
        [Required]
        [Column("EMPLOYEE")]
        [StringLength(500)]
        [Unicode(false)]
        public string Employee { get; set; }
        [Column("REVISION_NUMBER")]
        public int RevisionNumber { get; set; }
        [Column("XFERED")]
        public bool Xfered { get; set; }
        [Column("DELETED")]
        public Guid Deleted { get; set; }
        [Column("LINE_ORDER")]
        public short LineOrder { get; set; }
        [Column("LOCKED_RECORD")]
        public bool LockedRecord { get; set; }
        [Column("FIXED_RECORD")]
        public bool FixedRecord { get; set; }
        [Column("EXPANDED")]
        public bool Expanded { get; set; }
        [Column("SOAP_GUID")]
        public Guid? SoapGuid { get; set; }
        [Column("SOAP_TAB")]
        public int? SoapTab { get; set; }
        [Column("SOAP_DATE_TIME", TypeName = "datetime")]
        public DateTime? SoapDateTime { get; set; }
        [Column("CLIENT_GUID")]
        public Guid ClientGuid { get; set; }
        [Column("PATIENT_GUID")]
        public Guid PatientGuid { get; set; }
        [Column("UP_USER_GUID")]
        public Guid UpUserGuid { get; set; }
        [Column("REVISED")]
        public bool Revised { get; set; }
        [Required]
        [Column("EUSER_NAME")]
        [StringLength(70)]
        [Unicode(false)]
        public string EuserName { get; set; }
    }
}