// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("CorpMessageStatus")]
    public partial class CorpMessageStatus
    {
        [Key]
        [Column("StatusGUID")]
        public Guid StatusGuid { get; set; }
        [Column("CorpMessageGUID")]
        public Guid CorpMessageGuid { get; set; }
        [Column("UserGUID")]
        public Guid UserGuid { get; set; }
        [Column("FranchiseGUID")]
        public Guid FranchiseGuid { get; set; }
        public bool? Read { get; set; }
        public bool? Deleted { get; set; }
    }
}