// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("CORP_TRANS_MSG")]
    [Index(nameof(Sequence), Name = "CORP_TRANS_MSG_SEQUENCE", IsUnique = true)]
    public partial class CorpTransMsg
    {
        [Key]
        [Column("CORP_TRANS_MSG_GUID")]
        public Guid CorpTransMsgGuid { get; set; }
        [Column("CORP_TRANS_GUID")]
        public Guid CorpTransGuid { get; set; }
        [Column("SEQUENCE")]
        public long Sequence { get; set; }
        [Required]
        [Column("MESSAGE", TypeName = "text")]
        public string Message { get; set; }
    }
}