// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    public partial class CorpDatabase
    {
        [Key]
        [Column("DatabaseGUID")]
        public Guid DatabaseGuid { get; set; }
        [Required]
        [StringLength(256)]
        public string DatabaseName { get; set; }
    }
}