// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("CorpPricingProd")]
    public partial class CorpPricingProd
    {
        [Key]
        [Column("CORP_PRICING_PROD_GUID")]
        public Guid CorpPricingProdGuid { get; set; }
        [Column("CORP_PRICING_GUID")]
        public Guid CorpPricingGuid { get; set; }
        [Column("PRODM_GUID")]
        public Guid ProdmGuid { get; set; }
        [Column("INVM_GUID")]
        public Guid InvmGuid { get; set; }
        [Column("PRICE_OF_1", TypeName = "money")]
        public decimal PriceOf1 { get; set; }
        [Column("INVENTORY_QTY", TypeName = "money")]
        public decimal InventoryQty { get; set; }
        [Column("UNIT_COST", TypeName = "money")]
        public decimal UnitCost { get; set; }
        [Column("IMARKUP1", TypeName = "money")]
        public decimal Imarkup1 { get; set; }
        [Column("IMARKUP2", TypeName = "money")]
        public decimal Imarkup2 { get; set; }
        [Column("IMARKUP3", TypeName = "money")]
        public decimal Imarkup3 { get; set; }
        [Column("IMARKUP4", TypeName = "money")]
        public decimal Imarkup4 { get; set; }
        [Column("IMARKUP5", TypeName = "money")]
        public decimal Imarkup5 { get; set; }
        [Column("IPRICE1", TypeName = "money")]
        public decimal Iprice1 { get; set; }
        [Column("IPRICE2", TypeName = "money")]
        public decimal Iprice2 { get; set; }
        [Column("IPRICE3", TypeName = "money")]
        public decimal Iprice3 { get; set; }
        [Column("IPRICE4", TypeName = "money")]
        public decimal Iprice4 { get; set; }
        [Column("IPRICE5", TypeName = "money")]
        public decimal Iprice5 { get; set; }
        [Column("EMARKUP1", TypeName = "money")]
        public decimal Emarkup1 { get; set; }
        [Column("EMARKUP2", TypeName = "money")]
        public decimal Emarkup2 { get; set; }
        [Column("EMARKUP3", TypeName = "money")]
        public decimal Emarkup3 { get; set; }
        [Column("EMARKUP4", TypeName = "money")]
        public decimal Emarkup4 { get; set; }
        [Column("EMARKUP5", TypeName = "money")]
        public decimal Emarkup5 { get; set; }
        [Column("EPRICE1", TypeName = "money")]
        public decimal Eprice1 { get; set; }
        [Column("EPRICE2", TypeName = "money")]
        public decimal Eprice2 { get; set; }
        [Column("EPRICE3", TypeName = "money")]
        public decimal Eprice3 { get; set; }
        [Column("EPRICE4", TypeName = "money")]
        public decimal Eprice4 { get; set; }
        [Column("EPRICE5", TypeName = "money")]
        public decimal Eprice5 { get; set; }
        [Column("MIN_PRICE", TypeName = "money")]
        public decimal MinPrice { get; set; }
        [Column("PKG_FEE", TypeName = "money")]
        public decimal PkgFee { get; set; }
        [Column("DEF_QTY", TypeName = "money")]
        public decimal DefQty { get; set; }
        [Column("DEF_HI_QTY", TypeName = "money")]
        public decimal DefHiQty { get; set; }
    }
}