// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("CORP_MRCV")]
    public partial class CorpMrcv
    {
        [Key]
        [Column("KEY_GUID")]
        public Guid KeyGuid { get; set; }
        [Column("CREATE_DATE_TIME", TypeName = "datetime")]
        public DateTime CreateDateTime { get; set; }
        [Column("RECORD_COUNT")]
        public int RecordCount { get; set; }
        [Column("PRACTICE_GUID")]
        public Guid PracticeGuid { get; set; }
    }
}