// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Keyless]
    public partial class CorpOption
    {
        [Column("PRICE_UPDATE_OPTION")]
        public byte PriceUpdateOption { get; set; }
        [Column("PRICE_UPDATE_DAY")]
        public byte PriceUpdateDay { get; set; }
        [Column("PRICE_UPDATE_TIME1", TypeName = "datetime")]
        public DateTime PriceUpdateTime1 { get; set; }
        [Column("PRICE_UPDATE_DATE", TypeName = "datetime")]
        public DateTime PriceUpdateDate { get; set; }
        [Column("PRICE_UPDATE_TIME2", TypeName = "datetime")]
        public DateTime PriceUpdateTime2 { get; set; }
    }
}