// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("CorpAttributeInv")]
    public partial class CorpAttributeInv
    {
        [Key]
        [Column("CORP_ATTRIBUTE_INV_GUID")]
        public Guid CorpAttributeInvGuid { get; set; }
        [Column("CORP_ATTRIBUTE_GUID")]
        public Guid CorpAttributeGuid { get; set; }
        [Column("INVM_GUID")]
        public Guid InvmGuid { get; set; }
        [Column("AVAILABLE")]
        public bool Available { get; set; }
    }
}