// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("CorpPricingInv")]
    public partial class CorpPricingInv
    {
        [Key]
        [Column("CORP_PRICING_INV_GUID")]
        public Guid CorpPricingInvGuid { get; set; }
        [Column("CORP_PRICING_GUID")]
        public Guid CorpPricingGuid { get; set; }
        [Column("INVM_GUID")]
        public Guid InvmGuid { get; set; }
        [Column("UNIT_COST", TypeName = "money")]
        public decimal UnitCost { get; set; }
    }
}