// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("CORP_TRANS_ERR")]
    public partial class CorpTransErr
    {
        [Key]
        [Column("CORP_TRANS_ERR_GUID")]
        public Guid CorpTransErrGuid { get; set; }
        [Required]
        [Column("MESSAGE", TypeName = "text")]
        public string Message { get; set; }
    }
}