// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("CorpPricingAtt")]
    public partial class CorpPricingAtt
    {
        [Key]
        [Column("CORP_PRICING_ATT_GUID")]
        public Guid CorpPricingAttGuid { get; set; }
        [Column("CORP_PRICING_GUID")]
        public Guid CorpPricingGuid { get; set; }
        [Column("BUNDLE_GUID")]
        public Guid BundleGuid { get; set; }
        [Column("LOPRICE", TypeName = "money")]
        public decimal Loprice { get; set; }
        [Column("HIPRICE", TypeName = "money")]
        public decimal Hiprice { get; set; }
        [Column("DISCOUNT_AMOUNT", TypeName = "money")]
        public decimal DiscountAmount { get; set; }
        [Column("LOQTY", TypeName = "money")]
        public decimal Loqty { get; set; }
        [Column("HIQTY", TypeName = "money")]
        public decimal Hiqty { get; set; }
        [Column("PRICE_OPTION")]
        public short PriceOption { get; set; }
        [Column("CORP_BUNDLE_LINK_GUID")]
        public Guid CorpBundleLinkGuid { get; set; }
    }
}