// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    public partial class CorpMessage
    {
        [Key]
        [Column("CorpMessageGUID")]
        public Guid CorpMessageGuid { get; set; }
        [Column("ParentGUID")]
        public Guid ParentGuid { get; set; }
        [Required]
        [Column("MessRTF", TypeName = "text")]
        public string MessRtf { get; set; }
        [Required]
        [Column(TypeName = "text")]
        public string MessText { get; set; }
        [Required]
        [StringLength(200)]
        [Unicode(false)]
        public string Subject { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreateDateTime { get; set; }
        [Column("CreateUTC", TypeName = "datetime")]
        public DateTime CreateUtc { get; set; }
        public Guid FromFranchiseGuid { get; set; }
        public Guid FromUserGuid { get; set; }
        public Guid ToFranchiseGuid { get; set; }
        public Guid ToUserGuid { get; set; }
    }
}