// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("CORP_TRANS_M")]
    [Index(nameof(ProgramId), Name = "CORP_TRANS_M_PROGRAM_ID")]
    [Index(nameof(Sequence), Name = "CORP_TRANS_M_SEQUENCE", IsUnique = true)]
    public partial class CorpTransM
    {
        [Key]
        [Column("CORP_TRANS_M_GUID")]
        public Guid CorpTransMGuid { get; set; }
        [Column("EXECUTED")]
        public bool Executed { get; set; }
        [Column("SEQUENCE")]
        public long Sequence { get; set; }
        [Required]
        [Column("PROGRAM_ID")]
        [StringLength(500)]
        [Unicode(false)]
        public string ProgramId { get; set; }
        [Column("CREATE_DATE_TIME", TypeName = "datetime")]
        public DateTime CreateDateTime { get; set; }
        [Column("CREATE_USER_GUID")]
        public Guid CreateUserGuid { get; set; }
        [Column("CREATE_WORKSTATION_GUID")]
        public Guid CreateWorkstationGuid { get; set; }
    }
}