// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("COUNTRIES")]
    public partial class Country
    {
        [Key]
        [Column("COUNTRY_GUID")]
        public Guid CountryGuid { get; set; }
        [Required]
        [Column("COUNTRY_NAME")]
        [StringLength(30)]
        [Unicode(false)]
        public string CountryName { get; set; }
        [Required]
        [Column("COUNTRY_ABBREV")]
        [StringLength(5)]
        [Unicode(false)]
        public string CountryAbbrev { get; set; }
        [Required]
        [Column("ZIPCODE_MASK")]
        [StringLength(10)]
        [Unicode(false)]
        public string ZipcodeMask { get; set; }
        [Required]
        [Column("DEFAULT_VALUE")]
        [StringLength(10)]
        [Unicode(false)]
        public string DefaultValue { get; set; }
    }
}