// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("CUSTOM_DICT")]
    public partial class CustomDict
    {
        [Key]
        [Column("CD_KEY")]
        public Guid CdKey { get; set; }
        [Required]
        [Column("WORD")]
        [StringLength(300)]
        [Unicode(false)]
        public string Word { get; set; }
        [Column("DTS", TypeName = "datetime")]
        public DateTime Dts { get; set; }
    }
}