// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("DB_CLIENTS")]
    public partial class DbClient
    {
        [Key]
        [Column("AR_CURRENT", TypeName = "money")]
        public decimal ArCurrent { get; set; }
        [Column("AR_30", TypeName = "money")]
        public decimal Ar30 { get; set; }
        [Column("AR_60", TypeName = "money")]
        public decimal Ar60 { get; set; }
        [Column("AR_90", TypeName = "money")]
        public decimal Ar90 { get; set; }
        [Column("AR_ESTIMATES")]
        public int ArEstimates { get; set; }
        [Column("AR_TOTAL_DUE", TypeName = "money")]
        public decimal ArTotalDue { get; set; }
        [Column("AR_CREDIT_LIMIT", TypeName = "money")]
        public decimal ArCreditLimit { get; set; }
        [Column("AR_YTD_SALES", TypeName = "money")]
        public decimal ArYtdSales { get; set; }
        [Column("AR_YTD_INTEREST", TypeName = "money")]
        public decimal ArYtdInterest { get; set; }
        [Column("AR_PPLAN")]
        public bool ArPplan { get; set; }
        [Column("AR_PPLAN_FREQ")]
        public int ArPplanFreq { get; set; }
        [Column("AR_PPLAN_AMOUNT", TypeName = "money")]
        public decimal ArPplanAmount { get; set; }
        [Column("AR_LAST_PAY_DATE", TypeName = "datetime")]
        public DateTime? ArLastPayDate { get; set; }
        [Column("AR_LAST_PAY_AMT", TypeName = "money")]
        public decimal ArLastPayAmt { get; set; }
        [Column("AR_STATEMENT_DETAILS_BEGIN", TypeName = "datetime")]
        public DateTime? ArStatementDetailsBegin { get; set; }
        [Column("AR_BEGINNING_BALANCE", TypeName = "money")]
        public decimal ArBeginningBalance { get; set; }
        [Column("NUMBER_OF_PETS")]
        public int NumberOfPets { get; set; }
        [Required]
        [Column("BC_POSTAL_CODE", TypeName = "image")]
        public byte[] BcPostalCode { get; set; }
        [Required]
        [Column("BC_CACCT_NUMBER", TypeName = "image")]
        public byte[] BcCacctNumber { get; set; }
        [Required]
        [Column("BC_LAST_NAME_FIRST_NAME")]
        [StringLength(47)]
        [Unicode(false)]
        public string BcLastNameFirstName { get; set; }
        [Required]
        [Column("BC_FIRST_NAME_LAST_NAME")]
        [StringLength(46)]
        [Unicode(false)]
        public string BcFirstNameLastName { get; set; }
        [Required]
        [Column("BC_CITY_STATE_ZIP")]
        [StringLength(45)]
        [Unicode(false)]
        public string BcCityStateZip { get; set; }
        [Required]
        [Column("CS_NAMES")]
        [StringLength(200)]
        [Unicode(false)]
        public string CsNames { get; set; }
        [Column("KEY_ROW_GUID")]
        public Guid KeyRowGuid { get; set; }
    }
}