// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("DB_INT_UPDATES")]
    public partial class DbIntUpdate
    {
        [Key]
        [Column("UPDATE_GUID")]
        public Guid UpdateGuid { get; set; }
        [Column("GROUPING_GUID")]
        public Guid GroupingGuid { get; set; }
        [Column("TI_PROD_GUID")]
        public Guid TiProdGuid { get; set; }
        [Required]
        [Column("TABLE_NAME")]
        [StringLength(50)]
        [Unicode(false)]
        public string TableName { get; set; }
        [Required]
        [Column("FIELD_NAME")]
        [StringLength(50)]
        [Unicode(false)]
        public string FieldName { get; set; }
        [Column("O_VALUE", TypeName = "text")]
        public string OValue { get; set; }
        [Column("N_VALUE", TypeName = "text")]
        public string NValue { get; set; }
        [Column("CREATE_DATE_TIME", TypeName = "datetime")]
        public DateTime CreateDateTime { get; set; }
    }
}