// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("DB_MODULES_M")]
    public partial class DbModulesM
    {
        [Key]
        [Column("DB_MODULES_M_GUID")]
        public Guid DbModulesMGuid { get; set; }
        [Required]
        [Column("MODULE_NAME")]
        [StringLength(50)]
        [Unicode(false)]
        public string ModuleName { get; set; }
        [Column("MODULE_CODE")]
        public short ModuleCode { get; set; }
        [Column("INCLUDE_CLT_PAT")]
        public short IncludeCltPat { get; set; }
        [Column("LABELS_FLAG")]
        public bool LabelsFlag { get; set; }
        [Column("CREATE_DATE_TIME", TypeName = "datetime")]
        public DateTime CreateDateTime { get; set; }
    }
}