// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("DB_PATIENTS")]
    public partial class DbPatient
    {
        [Required]
        [Column("IMG_WEIGHT_HISTORY", TypeName = "image")]
        public byte[] ImgWeightHistory { get; set; }
        [Column("IS_DECEASED")]
        public bool IsDeceased { get; set; }
        [Column("STORED_SERVICES")]
        public int StoredServices { get; set; }
        [Column("SCHEDULED_SERVICES")]
        public int ScheduledServices { get; set; }
        [Column("DAILY_SERVICES")]
        public int DailyServices { get; set; }
        [Column("HB_VALUE")]
        public short HbValue { get; set; }
        [Required]
        [Column("HB_WARD_NAME")]
        [StringLength(40)]
        [Unicode(false)]
        public string HbWardName { get; set; }
        [Required]
        [Column("HB_CAGE_NAME")]
        [StringLength(40)]
        [Unicode(false)]
        public string HbCageName { get; set; }
        [Required]
        [Column("HB_STATUS")]
        [StringLength(50)]
        [Unicode(false)]
        public string HbStatus { get; set; }
        [Required]
        [Column("PAT_AGE")]
        [StringLength(50)]
        [Unicode(false)]
        public string PatAge { get; set; }
        [Required]
        [Column("BC_PACCT_NUMBER", TypeName = "image")]
        public byte[] BcPacctNumber { get; set; }
        [Key]
        [Column("LAST_TAG_NUMBER")]
        [StringLength(15)]
        [Unicode(false)]
        public string LastTagNumber { get; set; }
        [Required]
        [Column("LHE_SHE")]
        [StringLength(50)]
        [Unicode(false)]
        public string LheShe { get; set; }
        [Required]
        [Column("LHIM_HER")]
        [StringLength(50)]
        [Unicode(false)]
        public string LhimHer { get; set; }
        [Required]
        [Column("LHIS_HERS")]
        [StringLength(50)]
        [Unicode(false)]
        public string LhisHers { get; set; }
        [Required]
        [Column("LHIS_HER")]
        [StringLength(50)]
        [Unicode(false)]
        public string LhisHer { get; set; }
        [Required]
        [Column("UHE_SHE")]
        [StringLength(50)]
        [Unicode(false)]
        public string UheShe { get; set; }
        [Required]
        [Column("UHIM_HER")]
        [StringLength(50)]
        [Unicode(false)]
        public string UhimHer { get; set; }
        [Required]
        [Column("UHIS_HERS")]
        [StringLength(50)]
        [Unicode(false)]
        public string UhisHers { get; set; }
        [Required]
        [Column("UHIS_HER")]
        [StringLength(50)]
        [Unicode(false)]
        public string UhisHer { get; set; }
        [Required]
        [Column("W_KG")]
        [StringLength(50)]
        [Unicode(false)]
        public string WKg { get; set; }
        [Required]
        [Column("W_G")]
        [StringLength(50)]
        [Unicode(false)]
        public string WG { get; set; }
        [Required]
        [Column("W_LB")]
        [StringLength(50)]
        [Unicode(false)]
        public string WLb { get; set; }
        [Required]
        [Column("W_OZ")]
        [StringLength(50)]
        [Unicode(false)]
        public string WOz { get; set; }
        [Column("KEY_ROW_GUID")]
        public Guid KeyRowGuid { get; set; }
    }
}