// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("DB_SEX_PRONOUNS")]
    public partial class DbSexPronoun
    {
        [Key]
        [Column("KEY_GUID")]
        public Guid KeyGuid { get; set; }
        [Required]
        [Column("SEX_CODE")]
        [StringLength(2)]
        [Unicode(false)]
        public string SexCode { get; set; }
        [Column("SEX_INDEX")]
        public int SexIndex { get; set; }
        [Required]
        [Column("PRONOUN")]
        [StringLength(50)]
        [Unicode(false)]
        public string Pronoun { get; set; }
    }
}