// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("DISCOUNTS")]
    public partial class Discount
    {
        [Key]
        [Column("DISC_REV_GUID")]
        public Guid DiscRevGuid { get; set; }
        [Column("DISCOUNT_GUID")]
        public Guid DiscountGuid { get; set; }
        [Required]
        [Column("NAME")]
        [StringLength(30)]
        [Unicode(false)]
        public string Name { get; set; }
        [Column("DELETE_GUID")]
        public Guid DeleteGuid { get; set; }
        [Required]
        [Column("DESCRIPTION")]
        [StringLength(1000)]
        [Unicode(false)]
        public string Description { get; set; }
        [Column("PERCENTAGE")]
        public int Percentage { get; set; }
        [Column("CREATE_DATE_TIME", TypeName = "datetime")]
        public DateTime CreateDateTime { get; set; }
        [Column("CREATE_USER_GUID")]
        public Guid CreateUserGuid { get; set; }
        [Column("CREATE_WORKSTATION_GUID")]
        public Guid CreateWorkstationGuid { get; set; }
        [Column("DELETED")]
        public bool Deleted { get; set; }
        [Column("ALL_PRODUCTS")]
        public bool AllProducts { get; set; }
    }
}