// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("EF_LAB_FIELDS_DYNA")]
    public partial class EfLabFieldsDyna
    {
        [Key]
        [Column("LF_DYNA_GUID")]
        public Guid LfDynaGuid { get; set; }
        [Required]
        [Column("LF_NAME")]
        [StringLength(100)]
        [Unicode(false)]
        public string LfName { get; set; }
        [Required]
        [Column("LF_ID")]
        [StringLength(100)]
        [Unicode(false)]
        public string LfId { get; set; }
        [Column("LF_MODULE")]
        public int LfModule { get; set; }
        [Column("EF_LAB_FIELD_GUID")]
        public Guid EfLabFieldGuid { get; set; }
        [Column("LF_TYPE")]
        public int LfType { get; set; }
        [Column("LFMachineID")]
        public int LfmachineId { get; set; }
    }
}