// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("EFORMS_CATS")]
    public partial class EformsCat
    {
        [Key]
        [Column("EFORM_GUID")]
        public Guid EformGuid { get; set; }
        [Column("CAT_GUID")]
        public Guid CatGuid { get; set; }
    }
}