// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("EFORM_CATEGORIES")]
    public partial class EformCategory
    {
        [Key]
        [Column("CAT_GUID")]
        public Guid CatGuid { get; set; }
        [Required]
        [Column("CAT_NAME")]
        [StringLength(50)]
        [Unicode(false)]
        public string CatName { get; set; }
        [Required]
        [Column("DELETED_GUID")]
        [StringLength(50)]
        [Unicode(false)]
        public string DeletedGuid { get; set; }
    }
}