// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("EMAIL_BLOCKED")]
    public partial class EmailBlocked
    {
        [Key]
        [Column("CLIENT_GUID")]
        public Guid ClientGuid { get; set; }
        [Column("mreplcol")]
        public bool Mreplcol { get; set; }
    }
}