// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("EMPLOYEES_M")]
    public partial class EmployeesM
    {
        [Key]
        [Column("EMP_REVISION_GUID")]
        public Guid EmpRevisionGuid { get; set; }
        [Column("EMPLOYEE_GUID")]
        public Guid EmployeeGuid { get; set; }
        [Column("EGROUP_GUID")]
        public Guid EgroupGuid { get; set; }
        [Required]
        [Column("VID")]
        [StringLength(5)]
        [Unicode(false)]
        public string Vid { get; set; }
        [Column("DELETE_GUID")]
        public Guid DeleteGuid { get; set; }
        [Required]
        [Column("PREFIX")]
        [StringLength(5)]
        [Unicode(false)]
        public string Prefix { get; set; }
        [Required]
        [Column("FIRST_NAME")]
        [StringLength(20)]
        [Unicode(false)]
        public string FirstName { get; set; }
        [Required]
        [Column("LAST_NAME")]
        [StringLength(25)]
        [Unicode(false)]
        public string LastName { get; set; }
        [Required]
        [Column("SUFFIX")]
        [StringLength(20)]
        [Unicode(false)]
        public string Suffix { get; set; }
        [Required]
        [Column("ADDRESS1")]
        [StringLength(45)]
        [Unicode(false)]
        public string Address1 { get; set; }
        [Required]
        [Column("ADDRESS2")]
        [StringLength(45)]
        [Unicode(false)]
        public string Address2 { get; set; }
        [Column("CITY_STATE_GUID")]
        public Guid? CityStateGuid { get; set; }
        [Column("COUNTRY_GUID")]
        public Guid CountryGuid { get; set; }
        [Required]
        [Column("ZIPCODE")]
        [StringLength(10)]
        [Unicode(false)]
        public string Zipcode { get; set; }
        [Required]
        [Column("PHONE1")]
        [StringLength(24)]
        [Unicode(false)]
        public string Phone1 { get; set; }
        [Required]
        [Column("PHONE2")]
        [StringLength(24)]
        [Unicode(false)]
        public string Phone2 { get; set; }
        [Required]
        [Column("EMAIL_ADDRESS")]
        [StringLength(255)]
        [Unicode(false)]
        public string EmailAddress { get; set; }
        [Required]
        [Column("CELL_PHONE")]
        [StringLength(24)]
        [Unicode(false)]
        public string CellPhone { get; set; }
        [Required]
        [Column("PAGER")]
        [StringLength(50)]
        [Unicode(false)]
        public string Pager { get; set; }
        [Column("HIRE_DATE", TypeName = "datetime")]
        public DateTime HireDate { get; set; }
        [Column("RELEASE_DATE", TypeName = "datetime")]
        public DateTime? ReleaseDate { get; set; }
        [Required]
        [Column("POSITION")]
        [StringLength(100)]
        [Unicode(false)]
        public string Position { get; set; }
        [Required]
        [Column("SSNUMBER")]
        [StringLength(11)]
        [Unicode(false)]
        public string Ssnumber { get; set; }
        [Column("IMAGE_GUID")]
        public Guid? ImageGuid { get; set; }
        [Column("ENABLE")]
        public bool Enable { get; set; }
        [Column("CREATE_DATE_TIME", TypeName = "datetime")]
        public DateTime CreateDateTime { get; set; }
        [Column("CREATE_USER_GUID")]
        public Guid CreateUserGuid { get; set; }
        [Column("CREATE_WORKSTATION_GUID")]
        public Guid CreateWorkstationGuid { get; set; }
        [Column("DELETED")]
        public bool Deleted { get; set; }
        [Required]
        [Column("CUSTOM01")]
        [StringLength(50)]
        [Unicode(false)]
        public string Custom01 { get; set; }
        [Required]
        [Column("CUSTOM02")]
        [StringLength(50)]
        [Unicode(false)]
        public string Custom02 { get; set; }
        [Required]
        [Column("CUSTOM03")]
        [StringLength(50)]
        [Unicode(false)]
        public string Custom03 { get; set; }
        [Required]
        [Column("CUSTOM04")]
        [StringLength(50)]
        [Unicode(false)]
        public string Custom04 { get; set; }
        [Required]
        [Column("CUSTOM05")]
        [StringLength(50)]
        [Unicode(false)]
        public string Custom05 { get; set; }
        [Required]
        [Column("CUSTOM06")]
        [StringLength(50)]
        [Unicode(false)]
        public string Custom06 { get; set; }
        [Required]
        [Column("CUSTOM07")]
        [StringLength(50)]
        [Unicode(false)]
        public string Custom07 { get; set; }
        [Required]
        [Column("CUSTOM08")]
        [StringLength(50)]
        [Unicode(false)]
        public string Custom08 { get; set; }
        [Required]
        [Column("CUSTOM09")]
        [StringLength(50)]
        [Unicode(false)]
        public string Custom09 { get; set; }
        [Required]
        [Column("CUSTOM10")]
        [StringLength(50)]
        [Unicode(false)]
        public string Custom10 { get; set; }
        [Required]
        [Column("IS_PROVIDER")]
        public bool? IsProvider { get; set; }
        [Column("SIGNATURE_IMAGE_GUID")]
        public Guid? SignatureImageGuid { get; set; }
        [Required]
        [Column("ALLOW_DISCOUNTS")]
        public bool? AllowDiscounts { get; set; }
        [Required]
        [Column("MAY_INVOICE")]
        public bool? MayInvoice { get; set; }
        [Column("REFILL_EMPGUID")]
        public Guid RefillEmpguid { get; set; }
        [Column("IS_HD_PROVIDER")]
        public bool IsHdProvider { get; set; }
        [Column("IS_HD_STAFF")]
        public bool IsHdStaff { get; set; }
    }
}