// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("EMPLOYEE_CUSTOM")]
    public partial class EmployeeCustom
    {
        [Key]
        [Column("CUSTOM_GUID")]
        public Guid CustomGuid { get; set; }
        [Required]
        [Column("CUSTOM_FLD_NAME")]
        [StringLength(50)]
        [Unicode(false)]
        public string CustomFldName { get; set; }
        [Required]
        [Column("CUSTOM_DISPLAY_NAME")]
        [StringLength(50)]
        [Unicode(false)]
        public string CustomDisplayName { get; set; }
    }
}