// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("ESTIMATE_PRACTICE_SETTINGS")]
    public partial class EstimatePracticeSetting
    {
        [Key]
        [Column("SETTINGS_GUID")]
        public Guid SettingsGuid { get; set; }
        [Column("PRACTICE_VID")]
        public short PracticeVid { get; set; }
        [Column("NEXT_ESTIMATE_NUMBER", TypeName = "money")]
        public decimal NextEstimateNumber { get; set; }
        [Column("PREVIEW_ESTIMATE")]
        public bool PreviewEstimate { get; set; }
        [Column("DAYS_TIL_EXPIRED")]
        public short DaysTilExpired { get; set; }
        [Column("DOWN_PMT_PERCENT")]
        public short DownPmtPercent { get; set; }
        [Column("ON_HIGH_VALUE")]
        public bool OnHighValue { get; set; }
        [Column("USE_RANGES")]
        public bool UseRanges { get; set; }
        [Column("CREATE_DATE_TIME", TypeName = "datetime")]
        public DateTime CreateDateTime { get; set; }
        [Column("CREATE_USER_GUID")]
        public Guid CreateUserGuid { get; set; }
        [Column("CREATE_WORKSTATION_GUID")]
        public Guid CreateWorkstationGuid { get; set; }
        [Column("PROMPT_4_TEMPLATE")]
        public bool Prompt4Template { get; set; }
        [Column("DEFAULT_INACTIVE_TEMPLATE")]
        public Guid DefaultInactiveTemplate { get; set; }
        [Column("DEFAULT_ACTIVE_TEMPLATE")]
        public Guid DefaultActiveTemplate { get; set; }
        [Required]
        [Column("PREVIEW_BUNDLES")]
        public bool? PreviewBundles { get; set; }
        [Required]
        [Column("EMPLOYEE_FIRST")]
        public bool? EmployeeFirst { get; set; }
        [Required]
        [Column("CLIENT_ONLY_WARNING")]
        public bool? ClientOnlyWarning { get; set; }
        [Required]
        [Column("TEMPLATE_VERSION")]
        [StringLength(1)]
        [Unicode(false)]
        public string TemplateVersion { get; set; }
        [Required]
        [Column("PROMPT_4_CONSENTS")]
        public bool? Prompt4Consents { get; set; }
        [Required]
        [Column("RECALC_ON")]
        public bool? RecalcOn { get; set; }
    }
}