// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("ESTIMATE_LABELS_B")]
    public partial class EstimateLabelsB
    {
        [Key]
        [Column("LABEL_GUID")]
        public Guid LabelGuid { get; set; }
        [Column("TEMPLATE_REVISION_GUID")]
        public Guid TemplateRevisionGuid { get; set; }
        [Required]
        [Column("DISCOUNT_NAME")]
        [StringLength(30)]
        [Unicode(false)]
        public string DiscountName { get; set; }
        [Required]
        [Column("TOTAL_PRODUCTS")]
        [StringLength(30)]
        [Unicode(false)]
        public string TotalProducts { get; set; }
        [Required]
        [Column("INVOICE_DISCOUNTS")]
        [StringLength(30)]
        [Unicode(false)]
        public string InvoiceDiscounts { get; set; }
        [Required]
        [Column("INVOICE_SUBTOTAL")]
        [StringLength(30)]
        [Unicode(false)]
        public string InvoiceSubtotal { get; set; }
        [Required]
        [Column("TOTAL_INVOICE")]
        [StringLength(30)]
        [Unicode(false)]
        public string TotalInvoice { get; set; }
        [Required]
        [Column("TOTAL_PMTS")]
        [StringLength(30)]
        [Unicode(false)]
        public string TotalPmts { get; set; }
        [Required]
        [Column("MALE_CODE")]
        [StringLength(2)]
        [Unicode(false)]
        public string MaleCode { get; set; }
        [Required]
        [Column("MALE_NEUTERED_CODE")]
        [StringLength(2)]
        [Unicode(false)]
        public string MaleNeuteredCode { get; set; }
        [Required]
        [Column("FEMALE_CODE")]
        [StringLength(2)]
        [Unicode(false)]
        public string FemaleCode { get; set; }
        [Required]
        [Column("FEMALE_SPAYED_CODE")]
        [StringLength(2)]
        [Unicode(false)]
        public string FemaleSpayedCode { get; set; }
        [Required]
        [Column("MALE_LBL")]
        [StringLength(20)]
        [Unicode(false)]
        public string MaleLbl { get; set; }
        [Required]
        [Column("MALE_NEUTERED_LBL")]
        [StringLength(20)]
        [Unicode(false)]
        public string MaleNeuteredLbl { get; set; }
        [Required]
        [Column("FEMALE_LBL")]
        [StringLength(20)]
        [Unicode(false)]
        public string FemaleLbl { get; set; }
        [Required]
        [Column("FEMALE_SPAYED_LBL")]
        [StringLength(20)]
        [Unicode(false)]
        public string FemaleSpayedLbl { get; set; }
        [Required]
        [Column("CASHIER")]
        [StringLength(30)]
        [Unicode(false)]
        public string Cashier { get; set; }
        [Required]
        [Column("PRICE_TITLE")]
        [StringLength(15)]
        [Unicode(false)]
        public string PriceTitle { get; set; }
        [Required]
        [Column("TOTAL_CHANGE")]
        [StringLength(30)]
        [Unicode(false)]
        public string TotalChange { get; set; }
        [Required]
        [Column("ZERO_PRICE_LBL")]
        [StringLength(15)]
        [Unicode(false)]
        public string ZeroPriceLbl { get; set; }
        [Required]
        [Column("ZERO_PRICE_COMPONENT")]
        [StringLength(15)]
        [Unicode(false)]
        public string ZeroPriceComponent { get; set; }
        [Required]
        [Column("NUMBER_LBL")]
        [StringLength(20)]
        [Unicode(false)]
        public string NumberLbl { get; set; }
    }
}