// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("ESTIMATES")]
    public partial class Estimate
    {
        [Key]
        [Column("ESTIMATE_GUID")]
        public Guid EstimateGuid { get; set; }
        [Column("PRACTICE_VID")]
        public short PracticeVid { get; set; }
        [Column("ESTIMATE_NUMBER", TypeName = "money")]
        public decimal EstimateNumber { get; set; }
        [Column("CLIENT_GUID")]
        public Guid ClientGuid { get; set; }
        [Required]
        [Column("NAME")]
        [StringLength(50)]
        [Unicode(false)]
        public string Name { get; set; }
        [Column("DELETE_GUID")]
        public Guid DeleteGuid { get; set; }
        [Column("STATUS")]
        public short Status { get; set; }
        [Column("TEMPLATE_GUID")]
        public Guid TemplateGuid { get; set; }
        [Column("DATE_EXPIRES", TypeName = "datetime")]
        public DateTime DateExpires { get; set; }
        [Column("DATE_CREATED", TypeName = "datetime")]
        public DateTime DateCreated { get; set; }
        [Column("CREATEDBY_GUID")]
        public Guid CreatedbyGuid { get; set; }
        [Column("DATE_COMPLETED", TypeName = "datetime")]
        public DateTime? DateCompleted { get; set; }
        [Column("COMPLETEDBY_GUID")]
        public Guid CompletedbyGuid { get; set; }
        [Column("PRINT_COUNT")]
        public int PrintCount { get; set; }
        [Column("LOW_TOTAL", TypeName = "money")]
        public decimal LowTotal { get; set; }
        [Column("HIGH_TOTAL", TypeName = "money")]
        public decimal HighTotal { get; set; }
        [Column("DOWN_PAYMENT", TypeName = "money")]
        public decimal DownPayment { get; set; }
        [Column("CASHIER_GUID")]
        public Guid CashierGuid { get; set; }
        [Column("CREATE_DATE_TIME", TypeName = "datetime")]
        public DateTime CreateDateTime { get; set; }
        [Column("CREATE_USER_GUID")]
        public Guid CreateUserGuid { get; set; }
        [Column("CREATE_WORKSTATION_GUID")]
        public Guid CreateWorkstationGuid { get; set; }
        [Required]
        [Column("TEMPLATE_VERSION")]
        [StringLength(1)]
        [Unicode(false)]
        public string TemplateVersion { get; set; }
        [Column("RESERVATION_GUID")]
        public Guid ReservationGuid { get; set; }
        [Column("APPOINTMENT_GUID")]
        public Guid AppointmentGuid { get; set; }
        [Required]
        [Column("NOTE_TEXT", TypeName = "text")]
        public string NoteText { get; set; }
        [Required]
        [Column("NOTE_RTF", TypeName = "text")]
        public string NoteRtf { get; set; }
        [Column("TODO_GUID")]
        public Guid TodoGuid { get; set; }
        [Column("PATIENT_GUID")]
        public Guid PatientGuid { get; set; }
        [Column("CORP_ESTIMATE_GUID")]
        public Guid CorpEstimateGuid { get; set; }
        [Column("LOCKED")]
        public bool Locked { get; set; }
        [Column("REV_COUNT")]
        public int RevCount { get; set; }
        [Column("REVISED")]
        public bool Revised { get; set; }
    }
}