// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("EventLog")]
    public partial class EventLog
    {
        [Key]
        [Column("u")]
        public Guid U { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string LogType { get; set; }
        public int TimeGenerated { get; set; }
        [Column("EventID")]
        public int EventId { get; set; }
        public int EventType { get; set; }
        [Required]
        [StringLength(1000)]
        [Unicode(false)]
        public string SourceName { get; set; }
        public int StringCount { get; set; }
        [Required]
        [Column(TypeName = "text")]
        public string Strings { get; set; }
        [Column("ack")]
        public bool Ack { get; set; }
    }
}