// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    public partial class EventLogOption
    {
        [Key]
        [Column("pu")]
        public Guid Pu { get; set; }
        [Column("pi")]
        public int Pi { get; set; }
        [Column("pvalue")]
        public int Pvalue { get; set; }
    }
}