// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("FLAGS")]
    public partial class Flag
    {
        [Key]
        [Column("FLAG_GUID")]
        public Guid FlagGuid { get; set; }
        [Required]
        [Column("NAME")]
        [StringLength(40)]
        [Unicode(false)]
        public string Name { get; set; }
        [Column("DELETE_GUID")]
        public Guid DeleteGuid { get; set; }
        [Column("PRACTICE_VID")]
        public short PracticeVid { get; set; }
        [Column("FLAG_TYPE")]
        public short FlagType { get; set; }
        [Required]
        [Column("SOURCE_FIELD")]
        [StringLength(50)]
        [Unicode(false)]
        public string SourceField { get; set; }
        [Column("OPERATOR")]
        public short Operator { get; set; }
        [Required]
        [Column("VALUE1")]
        [StringLength(1000)]
        [Unicode(false)]
        public string Value1 { get; set; }
        [Required]
        [Column("VALUE2")]
        [StringLength(1000)]
        [Unicode(false)]
        public string Value2 { get; set; }
        [Column("VALUETYPE")]
        public short Valuetype { get; set; }
        [Column("PRIORITY_LEVEL")]
        public short PriorityLevel { get; set; }
        [Required]
        [Column("ICON", TypeName = "image")]
        public byte[] Icon { get; set; }
        [Required]
        [Column("DESCRIPTION")]
        [StringLength(1000)]
        [Unicode(false)]
        public string Description { get; set; }
        [Required]
        [Column("VERBOSE_DETAILS")]
        [StringLength(500)]
        [Unicode(false)]
        public string VerboseDetails { get; set; }
        [Column("CREATE_DATE_TIME", TypeName = "datetime")]
        public DateTime CreateDateTime { get; set; }
        [Column("CREATE_USER_GUID")]
        public Guid CreateUserGuid { get; set; }
        [Column("CREATE_WORKSTATION_GUID")]
        public Guid CreateWorkstationGuid { get; set; }
        [Column("DELETED")]
        public bool Deleted { get; set; }
        [Column("APPEND_VALUE")]
        public bool AppendValue { get; set; }
    }
}