// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("GlobalDictionary")]
    [Index(nameof(Term), Name = "IX_GlobalDictionary", IsUnique = true)]
    public partial class GlobalDictionary
    {
        [Key]
        [Column("DictGUID")]
        public Guid DictGuid { get; set; }
        [Required]
        [StringLength(300)]
        [Unicode(false)]
        public string Term { get; set; }
    }
}