// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("HD_INV")]
    [Index(nameof(HdInvMGuid), nameof(PracticeVid), Name = "HD_INV_PVID", IsUnique = true)]
    public partial class HdInv
    {
        [Key]
        [Column("HD_INV_GUID")]
        public Guid HdInvGuid { get; set; }
        [Column("HD_INV_M_GUID")]
        public Guid HdInvMGuid { get; set; }
        [Column("PRACTICE_VID")]
        public int PracticeVid { get; set; }
        [Column("IS_ACTIVE")]
        public int IsActive { get; set; }
    }
}