// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("HD_LISTS")]
    [Index(nameof(HdAcctNum), Name = "IX_HD_LISTS_ACCT_NUM")]
    [Index(nameof(ListEntry), Name = "IX_HD_LIST_ENTRY")]
    [Index(nameof(HdAcctNum), nameof(ListType), Name = "IX_HD_LIST_TYPE")]
    public partial class HdList
    {
        [Key]
        [Column("HD_LIST_GUID")]
        public Guid HdListGuid { get; set; }
        [Column("HD_ACCT_NUM")]
        public int HdAcctNum { get; set; }
        [Column("LIST_TYPE")]
        public int ListType { get; set; }
        [Required]
        [Column("LIST_ENTRY")]
        [StringLength(250)]
        [Unicode(false)]
        public string ListEntry { get; set; }
    }
}