// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("HD_ORDER_ITEM_RX")]
    [Index(nameof(RxNumber), Name = "IX_HD_OITEM_RX_NUMBER")]
    [Index(nameof(HdOitemGuid), Name = "IX_HD_OITEM_RX_OITEM")]
    [Index(nameof(HdOrderGuid), Name = "IX_HD_OITEM_RX_ORDER")]
    [Index(nameof(PatientGuid), Name = "IX_HD_OITEM_RX_PATIENT")]
    public partial class HdOrderItemRx
    {
        [Key]
        [Column("HD_OITEM_RX_GUID")]
        public Guid HdOitemRxGuid { get; set; }
        [Column("HD_OITEM_GUID")]
        public Guid HdOitemGuid { get; set; }
        [Column("HD_ORDER_GUID")]
        public Guid HdOrderGuid { get; set; }
        [Column("PATIENT_GUID")]
        public Guid PatientGuid { get; set; }
        [Required]
        [Column("RX_NUMBER")]
        [StringLength(30)]
        [Unicode(false)]
        public string RxNumber { get; set; }
        [Column("SIG_GUID")]
        public Guid SigGuid { get; set; }
        [Required]
        [Column("SIG_LINE1")]
        [StringLength(50)]
        [Unicode(false)]
        public string SigLine1 { get; set; }
        [Required]
        [Column("SIG_LINE2")]
        [StringLength(50)]
        [Unicode(false)]
        public string SigLine2 { get; set; }
        [Required]
        [Column("SIG_LINE3")]
        [StringLength(50)]
        [Unicode(false)]
        public string SigLine3 { get; set; }
        [Required]
        [Column("SIG_LINE4")]
        [StringLength(50)]
        [Unicode(false)]
        public string SigLine4 { get; set; }
        [Required]
        [Column("SIG_LINE5")]
        [StringLength(50)]
        [Unicode(false)]
        public string SigLine5 { get; set; }
        [Column("EXPIRE_DATE", TypeName = "datetime")]
        public DateTime ExpireDate { get; set; }
        [Column("REFILL_COUNT")]
        public int RefillCount { get; set; }
        [Column("DAYS_OF_SUPPLY")]
        public int DaysOfSupply { get; set; }
        [Required]
        [Column("PHARMACY_INSTRUCTIONS")]
        [StringLength(255)]
        [Unicode(false)]
        public string PharmacyInstructions { get; set; }
    }
}