// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("HD_SEX")]
    [Index(nameof(Sex), Name = "IX_HD_SEX")]
    [Index(nameof(HdAcctNum), Name = "IX_HD_SEX_ACCT_NUM")]
    public partial class HdSex
    {
        [Key]
        [Column("HD_SEX_GUID")]
        public Guid HdSexGuid { get; set; }
        [Column("HD_ACCT_NUM")]
        public int HdAcctNum { get; set; }
        [Required]
        [Column("SEX")]
        [StringLength(2)]
        [Unicode(false)]
        public string Sex { get; set; }
        [Column("MALE")]
        public bool Male { get; set; }
        [Column("NEUTERED")]
        public bool Neutered { get; set; }
        [Column("CREATE_DATE_TIME", TypeName = "datetime")]
        public DateTime CreateDateTime { get; set; }
        [Column("CREATE_USER_GUID")]
        public Guid CreateUserGuid { get; set; }
        [Column("CREATE_WORKSTATION_GUID")]
        public Guid CreateWorkstationGuid { get; set; }
    }
}