// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("HEALTH_PLANS")]
    public partial class HealthPlan
    {
        [Key]
        [Column("HEALTH_PLAN_GUID")]
        public Guid HealthPlanGuid { get; set; }
        [Required]
        [Column("HP_NAME")]
        [StringLength(30)]
        [Unicode(false)]
        public string HpName { get; set; }
        [Column("DELETE_GUID")]
        public Guid DeleteGuid { get; set; }
        [Required]
        [Column("DESCRIPTION")]
        [StringLength(1000)]
        [Unicode(false)]
        public string Description { get; set; }
        [Column("DISCOUNT_GUID")]
        public Guid DiscountGuid { get; set; }
        [Column("CHARGE_PRODM_GUID")]
        public Guid ChargeProdmGuid { get; set; }
        [Column("CREATE_DATE_TIME", TypeName = "datetime")]
        public DateTime CreateDateTime { get; set; }
        [Column("CREATE_USER_GUID")]
        public Guid CreateUserGuid { get; set; }
        [Column("CREATE_WORKSTATION_GUID")]
        public Guid CreateWorkstationGuid { get; set; }
        [Column("DELETED")]
        public bool Deleted { get; set; }
    }
}