// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("IA_COMMON")]
    public partial class IaCommon
    {
        [Key]
        [Column("COMMON_GUID")]
        public Guid CommonGuid { get; set; }
        [Column("PRACTICE_VID")]
        public short PracticeVid { get; set; }
        [Column("NEXT_ENTRY_NUMBER")]
        public int NextEntryNumber { get; set; }
    }
}