// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("IDV_dyn_CHANGES")]
    public partial class IdvDynChange
    {
        [Key]
        [Column("CHANGE_GUID")]
        public Guid ChangeGuid { get; set; }
        [Column("KEY_GUID")]
        public Guid KeyGuid { get; set; }
        [Required]
        [Column("ADM")]
        [StringLength(1)]
        [Unicode(false)]
        public string Adm { get; set; }
        [Column("DATE_TIME_STAMP", TypeName = "datetime")]
        public DateTime DateTimeStamp { get; set; }
        [Required]
        [Column("VIEW_NAME")]
        [StringLength(40)]
        [Unicode(false)]
        public string ViewName { get; set; }
    }
}