// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("IMAGE")]
    public partial class Image
    {
        [Key]
        [Column("IMAGE_REVISION_GUID")]
        public Guid ImageRevisionGuid { get; set; }
        [Required]
        [Column("IMAGE", TypeName = "image")]
        public byte[] Image1 { get; set; }
    }
}