// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("INVENTORY_INTERACTIONS")]
    public partial class InventoryInteraction
    {
        [Key]
        [Column("INTERACT_GUID")]
        public Guid InteractGuid { get; set; }
        [Column("INVM_GUID1")]
        public Guid InvmGuid1 { get; set; }
        [Column("INVM_GUID2")]
        public Guid InvmGuid2 { get; set; }
        [Required]
        [Column("INTERACT_MSG")]
        [StringLength(2000)]
        [Unicode(false)]
        public string InteractMsg { get; set; }
        [Column("CREATE_DATE_TIME", TypeName = "datetime")]
        public DateTime CreateDateTime { get; set; }
        [Column("CREATE_USER_GUID")]
        public Guid CreateUserGuid { get; set; }
        [Column("CREATE_WORKSTATION_GUID")]
        public Guid CreateWorkstationGuid { get; set; }
        [Column("DELETED")]
        public bool Deleted { get; set; }
    }
}