// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("INVENTORY_ITEMS")]
    public partial class InventoryItem
    {
        [Key]
        [Column("INV_GUID")]
        public Guid InvGuid { get; set; }
        [Column("INVM_GUID")]
        public Guid InvmGuid { get; set; }
        [Column("PRACTICE_VID")]
        public short PracticeVid { get; set; }
        [Column("AVAILABLE")]
        public bool Available { get; set; }
        [Column("UNIT_COST", TypeName = "money")]
        public decimal UnitCost { get; set; }
        [Column("LAST_VENDOR_GUID")]
        public Guid LastVendorGuid { get; set; }
        [Column("NEXT_LOT_NUM")]
        public int NextLotNum { get; set; }
        [Column("WASTAGE_PROMPT")]
        public bool WastagePrompt { get; set; }
        [Column("IMAGE_GUID")]
        public Guid? ImageGuid { get; set; }
        [Column("TAXED_ON_RECEIPT")]
        public bool TaxedOnReceipt { get; set; }
        [Column("CREATE_DATE_TIME", TypeName = "datetime")]
        public DateTime CreateDateTime { get; set; }
        [Column("CREATE_USER_GUID")]
        public Guid CreateUserGuid { get; set; }
        [Column("CREATE_WORKSTATION_GUID")]
        public Guid CreateWorkstationGuid { get; set; }
        [Column("DELETED")]
        public bool Deleted { get; set; }
        [Column("MEMO", TypeName = "text")]
        public string Memo { get; set; }
    }
}