// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("INVENTORY_LOTS")]
    public partial class InventoryLot
    {
        [Key]
        [Column("LOT_GUID")]
        public Guid LotGuid { get; set; }
        [Column("INVM_GUID")]
        public Guid InvmGuid { get; set; }
        [Column("INV_GUID")]
        public Guid InvGuid { get; set; }
        [Column("PRACTICE_VID")]
        public short PracticeVid { get; set; }
        [Column("STORAGE_GUID")]
        public Guid StorageGuid { get; set; }
        [Column("LOT_VID")]
        public int LotVid { get; set; }
        [Column("ACTIVE_FLAG")]
        public bool ActiveFlag { get; set; }
        [Required]
        [Column("NDC_NUMBER")]
        [StringLength(13)]
        [Unicode(false)]
        public string NdcNumber { get; set; }
        [Column("VENDOR_GUID")]
        public Guid VendorGuid { get; set; }
        [Column("EXPIRATION_DATE", TypeName = "datetime")]
        public DateTime ExpirationDate { get; set; }
        [Column("UNIT_COST", TypeName = "money")]
        public decimal UnitCost { get; set; }
        [Column("PRORATED_UNIT_COST", TypeName = "money")]
        public decimal ProratedUnitCost { get; set; }
        [Column("QTY_RECEIVED", TypeName = "money")]
        public decimal QtyReceived { get; set; }
        [Column("SPID_QTY_ON_HAND", TypeName = "money")]
        public decimal SpidQtyOnHand { get; set; }
        [Column("FIFO_QTY_ON_HAND", TypeName = "money")]
        public decimal FifoQtyOnHand { get; set; }
        [Column("LIFO_QTY_ON_HAND", TypeName = "money")]
        public decimal LifoQtyOnHand { get; set; }
        [Column("DATE_TIME_ORDERED", TypeName = "datetime")]
        public DateTime DateTimeOrdered { get; set; }
        [Column("DATE_TIME_RECEIVED", TypeName = "datetime")]
        public DateTime DateTimeReceived { get; set; }
        [Column("LASTMOD_DATE_TIME", TypeName = "datetime")]
        public DateTime LastmodDateTime { get; set; }
        [Column("LASTMOD_USER_GUID")]
        public Guid LastmodUserGuid { get; set; }
        [Column("LASTMOD_WORKSTATION_GUID")]
        public Guid LastmodWorkstationGuid { get; set; }
        [Column("CREATE_DATE_TIME", TypeName = "datetime")]
        public DateTime CreateDateTime { get; set; }
        [Column("CREATE_USER_GUID")]
        public Guid CreateUserGuid { get; set; }
        [Column("CREATE_WORKSTATION_GUID")]
        public Guid CreateWorkstationGuid { get; set; }
        [Column("DELETED")]
        public bool Deleted { get; set; }
        [Column("PO_RECEIPT_GUID")]
        public Guid PoReceiptGuid { get; set; }
        [Required]
        [Column("MANUFACTURER_LOT_NUM")]
        [StringLength(50)]
        [Unicode(false)]
        public string ManufacturerLotNum { get; set; }
        [Column("ON_CONSIGNMENT")]
        public bool OnConsignment { get; set; }
        [Required]
        [Column("MANUFACTURER_CODE")]
        [StringLength(50)]
        [Unicode(false)]
        public string ManufacturerCode { get; set; }
    }
}