// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("INVOICE_TEMPLATE_IMAGES")]
    public partial class InvoiceTemplateImage
    {
        [Key]
        [Column("IMAGES_GUID")]
        public Guid ImagesGuid { get; set; }
        [Required]
        [Column("THEME")]
        [StringLength(30)]
        [Unicode(false)]
        public string Theme { get; set; }
        [Column("PAGE_IMAGE", TypeName = "image")]
        public byte[] PageImage { get; set; }
        [Column("NUMBER_IMAGE", TypeName = "image")]
        public byte[] NumberImage { get; set; }
        [Column("PET_DTLS_IMAGE", TypeName = "image")]
        public byte[] PetDtlsImage { get; set; }
        [Column("AR_DTLS_IMAGE", TypeName = "image")]
        public byte[] ArDtlsImage { get; set; }
        [Column("SMALL_PET_DTLS_IMAGE", TypeName = "image")]
        public byte[] SmallPetDtlsImage { get; set; }
        [Column("SAMPLE_IMAGE", TypeName = "image")]
        public byte[] SampleImage { get; set; }
        [Column("CREATE_DATE_TIME", TypeName = "datetime")]
        public DateTime CreateDateTime { get; set; }
    }
}