// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("INVOICE_INVENTORY_LOTS")]
    public partial class InvoiceInventoryLot
    {
        [Key]
        [Column("INVOICE_LOT_GUID")]
        public Guid InvoiceLotGuid { get; set; }
        [Column("INVOICE_INV_GUID")]
        public Guid InvoiceInvGuid { get; set; }
        [Column("INVOICE_PROD_GUID")]
        public Guid InvoiceProdGuid { get; set; }
        [Column("PRACTICE_VID")]
        public short PracticeVid { get; set; }
        [Column("CLIENT_GUID")]
        public Guid ClientGuid { get; set; }
        [Column("PATIENT_GUID")]
        public Guid PatientGuid { get; set; }
        [Column("LOT_GUID")]
        public Guid LotGuid { get; set; }
        [Column("INVM_GUID")]
        public Guid InvmGuid { get; set; }
        [Column("INV_GUID")]
        public Guid InvGuid { get; set; }
        [Column("STORAGE_GUID")]
        public Guid StorageGuid { get; set; }
        [Column("FIFO_LIFO_OR_SPID")]
        public short FifoLifoOrSpid { get; set; }
        [Column("QTY", TypeName = "money")]
        public decimal Qty { get; set; }
        [Column("CREATE_DATE_TIME", TypeName = "datetime")]
        public DateTime CreateDateTime { get; set; }
        [Column("CREATE_USER_GUID")]
        public Guid CreateUserGuid { get; set; }
        [Column("CREATE_WORKSTATION_GUID")]
        public Guid CreateWorkstationGuid { get; set; }
        [Column("UNIT_COST", TypeName = "money")]
        public decimal UnitCost { get; set; }
        [Column("PRORATED_UNIT_COST", TypeName = "money")]
        public decimal ProratedUnitCost { get; set; }
    }
}