// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("INVOICE_PRODUCTS")]
    public partial class InvoiceProduct
    {
        [Key]
        [Column("INVOICE_PROD_GUID")]
        public Guid InvoiceProdGuid { get; set; }
        [Column("SOURCE_GUID")]
        public Guid SourceGuid { get; set; }
        [Column("PRACTICE_VID")]
        public short PracticeVid { get; set; }
        [Column("CLIENT_GUID")]
        public Guid ClientGuid { get; set; }
        [Column("PATIENT_GUID")]
        public Guid PatientGuid { get; set; }
        [Column("DATE_ENTERED", TypeName = "datetime")]
        public DateTime DateEntered { get; set; }
        [Column("TIME_ENTERED", TypeName = "datetime")]
        public DateTime TimeEntered { get; set; }
        [Column("DATE_PERFORMED", TypeName = "datetime")]
        public DateTime DatePerformed { get; set; }
        [Column("TIME_PERFORMED", TypeName = "datetime")]
        public DateTime TimePerformed { get; set; }
        [Column("LOCK_FLAG")]
        public short LockFlag { get; set; }
        [Column("LOCK_GUID")]
        public Guid LockGuid { get; set; }
        [Required]
        [Column("LOCK_NAME")]
        [StringLength(30)]
        [Unicode(false)]
        public string LockName { get; set; }
        [Column("PRODM_REVISION_GUID")]
        public Guid ProdmRevisionGuid { get; set; }
        [Column("PRODM_GUID")]
        public Guid ProdmGuid { get; set; }
        [Column("PROD_GUID")]
        public Guid ProdGuid { get; set; }
        [Column("PCAT_REVISION_GUID")]
        public Guid PcatRevisionGuid { get; set; }
        [Column("PCAT_GUID")]
        public Guid PcatGuid { get; set; }
        [Column("PTYPE_REVISION_GUID")]
        public Guid PtypeRevisionGuid { get; set; }
        [Column("PTYPE_GUID")]
        public Guid PtypeGuid { get; set; }
        [Column("PROFIT_REVISION_GUID")]
        public Guid ProfitRevisionGuid { get; set; }
        [Column("PROFIT_GUID")]
        public Guid ProfitGuid { get; set; }
        [Column("SOURCE_FLAG")]
        public short SourceFlag { get; set; }
        [Column("ACTION_GUID")]
        public Guid ActionGuid { get; set; }
        [Required]
        [Column("NAME")]
        [StringLength(40)]
        [Unicode(false)]
        public string Name { get; set; }
        [Required]
        [Column("CODE")]
        [StringLength(10)]
        [Unicode(false)]
        public string Code { get; set; }
        [Required]
        [Column("BARCODE")]
        [StringLength(30)]
        [Unicode(false)]
        public string Barcode { get; set; }
        [Column("DECIMALS")]
        public short Decimals { get; set; }
        [Column("ALLOW_DISCOUNTS")]
        public bool AllowDiscounts { get; set; }
        [Column("SHOW_ON_INVOICE")]
        public bool ShowOnInvoice { get; set; }
        [Column("MARKUP", TypeName = "money")]
        public decimal Markup { get; set; }
        [Column("DISCOUNT_TYPE")]
        public short DiscountType { get; set; }
        [Column("DISCOUNT_PERCENT")]
        public int DiscountPercent { get; set; }
        [Required]
        [Column("DISCOUNT_NAME")]
        [StringLength(30)]
        [Unicode(false)]
        public string DiscountName { get; set; }
        [Column("DISCOUNT_AMOUNT", TypeName = "money")]
        public decimal DiscountAmount { get; set; }
        [Column("DISCOUNT_GUID")]
        public Guid DiscountGuid { get; set; }
        [Column("DISCOUNT_REVISION_GUID")]
        public Guid DiscountRevisionGuid { get; set; }
        [Column("ACTION_TYPE")]
        public short ActionType { get; set; }
        [Required]
        [Column("ACTION_MSG")]
        [StringLength(50)]
        [Unicode(false)]
        public string ActionMsg { get; set; }
        [Column("UNIT_COST", TypeName = "money")]
        public decimal UnitCost { get; set; }
        [Column("QTY", TypeName = "money")]
        public decimal Qty { get; set; }
        [Required]
        [Column("UNIT_OF_MEASURE")]
        [StringLength(20)]
        [Unicode(false)]
        public string UnitOfMeasure { get; set; }
        [Column("MIN_PRICE", TypeName = "money")]
        public decimal MinPrice { get; set; }
        [Column("PKG_FEE", TypeName = "money")]
        public decimal PkgFee { get; set; }
        [Column("PRACTICE_PRICE", TypeName = "money")]
        public decimal PracticePrice { get; set; }
        [Column("ENTERED_PRICE", TypeName = "money")]
        public decimal EnteredPrice { get; set; }
        [Column("ADJUSTMENT_AMOUNT", TypeName = "money")]
        public decimal AdjustmentAmount { get; set; }
        [Column("INVOICE_DISCOUNT", TypeName = "money")]
        public decimal InvoiceDiscount { get; set; }
        [Column("INVM_REV_GUID")]
        public Guid InvmRevGuid { get; set; }
        [Column("INVM_GUID")]
        public Guid InvmGuid { get; set; }
        [Column("INV_GUID")]
        public Guid InvGuid { get; set; }
        [Column("INVENTORY_QTY", TypeName = "money")]
        public decimal InventoryQty { get; set; }
        [Column("TAXM_REVISION_GUID")]
        public Guid TaxmRevisionGuid { get; set; }
        [Column("TAXM_GUID")]
        public Guid TaxmGuid { get; set; }
        [Column("USE_TAX_REV_GUID")]
        public Guid UseTaxRevGuid { get; set; }
        [Column("USE_TAX_GUID")]
        public Guid UseTaxGuid { get; set; }
        [Column("IMAGE_GUID")]
        public Guid? ImageGuid { get; set; }
        [Column("PROBLEM_REVISION_GUID")]
        public Guid ProblemRevisionGuid { get; set; }
        [Column("CASE_REVISION_GUID")]
        public Guid CaseRevisionGuid { get; set; }
        [Column("EBUN_FLAG")]
        public bool EbunFlag { get; set; }
        [Column("EMPLOYEE_GUID")]
        public Guid EmployeeGuid { get; set; }
        [Column("EMPLOYEE_REVISION_GUID")]
        public Guid EmployeeRevisionGuid { get; set; }
        [Required]
        [Column("NOTES")]
        [StringLength(2000)]
        [Unicode(false)]
        public string Notes { get; set; }
        [Column("CREATE_DATE_TIME", TypeName = "datetime")]
        public DateTime CreateDateTime { get; set; }
        [Column("CREATE_USER_GUID")]
        public Guid CreateUserGuid { get; set; }
        [Column("CREATE_WORKSTATION_GUID")]
        public Guid CreateWorkstationGuid { get; set; }
        [Column("BUNDLE_GUID")]
        public Guid BundleGuid { get; set; }
        [Required]
        [Column("BUN_BULLET")]
        [StringLength(1)]
        [Unicode(false)]
        public string BunBullet { get; set; }
        [Column("CREATE_CASHIER_GUID")]
        public Guid CreateCashierGuid { get; set; }
        [Column("LASTMOD_CASHIER_GUID")]
        public Guid LastmodCashierGuid { get; set; }
        [Column("MODE_GUID")]
        public Guid ModeGuid { get; set; }
        [Column("POS1")]
        public int Pos1 { get; set; }
        [Column("POS2")]
        public int Pos2 { get; set; }
        [Column("POS3")]
        public int Pos3 { get; set; }
        [Column("POS4")]
        public int Pos4 { get; set; }
        [Column("SOAP_GUID")]
        public Guid SoapGuid { get; set; }
        [Required]
        [Column("LOCATION_CODE")]
        [StringLength(5)]
        [Unicode(false)]
        public string LocationCode { get; set; }
        [Column("TPLAN_SECTION")]
        public short TplanSection { get; set; }
        [Column("BUN_ADDPRICE")]
        public bool BunAddprice { get; set; }
        [Column("NESTED_BUNDLE_GUID")]
        public Guid NestedBundleGuid { get; set; }
    }
}