// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("INVOICE_SECTION_FIELDS")]
    public partial class InvoiceSectionField
    {
        [Key]
        [Column("ET_FIELD_GUID")]
        public Guid EtFieldGuid { get; set; }
        [Column("SECTION_GUID")]
        public Guid SectionGuid { get; set; }
        [Required]
        [Column("FIND_STRING")]
        [StringLength(250)]
        [Unicode(false)]
        public string FindString { get; set; }
        [Required]
        [Column("TABLE_NAME")]
        [StringLength(50)]
        [Unicode(false)]
        public string TableName { get; set; }
        [Required]
        [Column("FIELD_NAME")]
        [StringLength(250)]
        [Unicode(false)]
        public string FieldName { get; set; }
    }
}