// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("INVOICE_LOG")]
    public partial class InvoiceLog
    {
        [Key]
        [Column("LOG_GUID")]
        public Guid LogGuid { get; set; }
        [Column("LIST_PROD_GUID")]
        public Guid ListProdGuid { get; set; }
        [Column("ACTION_CODE")]
        public int ActionCode { get; set; }
        [Column("LOG_DATE_TIME", TypeName = "datetime")]
        public DateTime LogDateTime { get; set; }
        [Column("CASHIER_GUID")]
        public Guid CashierGuid { get; set; }
        [Column("USER_GUID")]
        public Guid UserGuid { get; set; }
        [Column("WORKSTATION_GUID")]
        public Guid WorkstationGuid { get; set; }
        [Column("OLD_QTY", TypeName = "money")]
        public decimal OldQty { get; set; }
        [Column("NEW_QTY", TypeName = "money")]
        public decimal NewQty { get; set; }
        [Column("OLD_PRICE", TypeName = "money")]
        public decimal OldPrice { get; set; }
        [Column("NEW_PRICE", TypeName = "money")]
        public decimal NewPrice { get; set; }
        [Column("INVQTY_DIFF", TypeName = "money")]
        public decimal InvqtyDiff { get; set; }
    }
}