// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("INVOICE_SUPERMODES")]
    public partial class InvoiceSupermode
    {
        [Key]
        [Column("MODE_GUID")]
        public Guid ModeGuid { get; set; }
        [Required]
        [Column("NAME")]
        [StringLength(50)]
        [Unicode(false)]
        public string Name { get; set; }
        [Column("DELETE_GUID")]
        public Guid DeleteGuid { get; set; }
        [Column("PRACTICE_VID")]
        public short PracticeVid { get; set; }
        [Column("MODE_VALUE", TypeName = "money")]
        public decimal ModeValue { get; set; }
        [Column("MODE_TYPE")]
        public short ModeType { get; set; }
        [Column("APPLY_DISCOUNT")]
        public bool ApplyDiscount { get; set; }
        [Column("DELETED")]
        public bool Deleted { get; set; }
        [Column("CREATE_DATE_TIME", TypeName = "datetime")]
        public DateTime CreateDateTime { get; set; }
        [Column("CREATE_USER_GUID")]
        public Guid CreateUserGuid { get; set; }
        [Column("CREATE_WORKSTATION_GUID")]
        public Guid CreateWorkstationGuid { get; set; }
        [Column("MODE_VALUE2", TypeName = "money")]
        public decimal ModeValue2 { get; set; }
        [Required]
        [Column("DO_RXLABEL")]
        public bool? DoRxlabel { get; set; }
    }
}