// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("INVOICE_COLORS_B")]
    public partial class InvoiceColorsB
    {
        [Key]
        [Column("COLOR_GUID")]
        public Guid ColorGuid { get; set; }
        [Column("TEMPLATE_REVISION_GUID")]
        public Guid TemplateRevisionGuid { get; set; }
        [Column("DISCOUNT_NAME_COLOR")]
        public int DiscountNameColor { get; set; }
        [Column("PRODUCT_CAT_COLOR")]
        public int ProductCatColor { get; set; }
        [Column("PRODUCT_NAME_COLOR")]
        public int ProductNameColor { get; set; }
        [Column("PRODUCT_DETAILS_COLOR")]
        public int ProductDetailsColor { get; set; }
        [Column("DATE_PERFORMED_COLOR")]
        public int DatePerformedColor { get; set; }
        [Column("CLIENT_NAME_COLOR")]
        public int ClientNameColor { get; set; }
        [Column("CLIENT_DETAILS_COLOR")]
        public int ClientDetailsColor { get; set; }
        [Column("PATIENT_NAME_COLOR")]
        public int PatientNameColor { get; set; }
        [Column("PATIENT_DETAILS_COLOR")]
        public int PatientDetailsColor { get; set; }
        [Column("VACC_NAME_COLOR")]
        public int VaccNameColor { get; set; }
        [Column("VACC_DATE_COLOR")]
        public int VaccDateColor { get; set; }
        [Column("PROVIDER_NAME_COLOR")]
        public int ProviderNameColor { get; set; }
        [Column("TOTAL_SECTION_COLOR")]
        public int TotalSectionColor { get; set; }
        [Column("TOTAL_UNPAID_COLOR")]
        public int TotalUnpaidColor { get; set; }
        [Column("POS_PRICE_COLOR")]
        public int PosPriceColor { get; set; }
        [Column("NEG_PRICE_COLOR")]
        public int NegPriceColor { get; set; }
        [Column("INVOICE_DATE_COLOR")]
        public int InvoiceDateColor { get; set; }
        [Column("INVOICE_NUMBER_COLOR")]
        public int InvoiceNumberColor { get; set; }
        [Column("PRODUCT_EMP_COLOR")]
        public int ProductEmpColor { get; set; }
        [Column("PRODUCT_CASHIER_COLOR")]
        public int ProductCashierColor { get; set; }
    }
}