// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("IPACSLookup")]
    public partial class Ipacslookup
    {
        [Key]
        [Column("PatientGUID")]
        public Guid PatientGuid { get; set; }
        [Required]
        [Column("LookupID")]
        [StringLength(100)]
        [Unicode(false)]
        public string LookupId { get; set; }
    }
}