// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("iPatches")]
    public partial class IPatch
    {
        [Key]
        [Column("SPID")]
        public Guid Spid { get; set; }
        [Column("PNUMBER")]
        public int Pnumber { get; set; }
        [Column("PRACTICE_DATE", TypeName = "datetime")]
        public DateTime PracticeDate { get; set; }
        [Column("CREATE_DATE_TIME", TypeName = "datetime")]
        public DateTime CreateDateTime { get; set; }
        [Required]
        [Column("VERSION")]
        [StringLength(500)]
        public string Version { get; set; }
        [Required]
        [Column("PATCH_NAME")]
        [StringLength(200)]
        public string PatchName { get; set; }
        [Required]
        [Column("PATCH_DESCRIPTION", TypeName = "text")]
        public string PatchDescription { get; set; }
        [Required]
        [Column("OPTIONS", TypeName = "text")]
        public string Options { get; set; }
        [Required]
        [Column("PATCH", TypeName = "text")]
        public string Patch { get; set; }
        [Column("RUN_ONCE")]
        public bool RunOnce { get; set; }
    }
}