// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("LABEL_ITEMS_STD")]
    public partial class LabelItemsStd
    {
        [Key]
        [Column("STD_LABEL_ITEM_GUID")]
        public Guid StdLabelItemGuid { get; set; }
        [Column("STD_LABEL_GUID")]
        public Guid StdLabelGuid { get; set; }
        [Column("LINE_NUMBER")]
        public short LineNumber { get; set; }
        [Required]
        [Column("TEXT")]
        [StringLength(300)]
        [Unicode(false)]
        public string Text { get; set; }
        [Column("ITYPE")]
        public byte Itype { get; set; }
        public float X { get; set; }
        public float Y { get; set; }
        public float P2 { get; set; }
        public float P3 { get; set; }
        [Column("FONT")]
        public short Font { get; set; }
        [Column("FONTSIZE")]
        public short Fontsize { get; set; }
        [Column("BOLD")]
        public bool Bold { get; set; }
        [Column("CAPITALIZE")]
        public bool Capitalize { get; set; }
        [Column("UNDERLINE")]
        public bool Underline { get; set; }
        [Column("BARCODE")]
        public bool Barcode { get; set; }
        [Column("BARCODETYPE")]
        public short Barcodetype { get; set; }
        [Column("ZEROPAD")]
        public bool Zeropad { get; set; }
        [Column("ROTATE")]
        public short Rotate { get; set; }
        [Column("ITALICIZE")]
        public bool Italicize { get; set; }
        [Column("COLOR")]
        public int Color { get; set; }
        [Required]
        [Column("DATA")]
        [StringLength(300)]
        [Unicode(false)]
        public string Data { get; set; }
    }
}