// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("LABEL_LOG")]
    public partial class LabelLog
    {
        [Key]
        [Column("LABEL_LOG_GUID")]
        public Guid LabelLogGuid { get; set; }
        [Column("MODULE_CODE")]
        public short ModuleCode { get; set; }
        [Column("LABEL_GUID")]
        public Guid LabelGuid { get; set; }
        [Column("LABEL_TYPE")]
        public short LabelType { get; set; }
        [Column("DATE_PRINTED", TypeName = "datetime")]
        public DateTime DatePrinted { get; set; }
        [Column("NUM_OF_COPIES")]
        public byte NumOfCopies { get; set; }
        [Column("LEVEL1_GUID")]
        public Guid? Level1Guid { get; set; }
        [Column("LEVEL2_GUID")]
        public Guid? Level2Guid { get; set; }
        [Column("LEVEL3_GUID")]
        public Guid? Level3Guid { get; set; }
        [Column("LEVEL4_GUID")]
        public Guid? Level4Guid { get; set; }
        [Column("LEVEL5_GUID")]
        public Guid? Level5Guid { get; set; }
        [Column("PRACTICE_VID")]
        public short PracticeVid { get; set; }
        [Column("CREATE_USER_GUID")]
        public Guid CreateUserGuid { get; set; }
        [Column("CREATE_WORKSTATION_GUID")]
        public Guid CreateWorkstationGuid { get; set; }
    }
}