// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("LABEL_ITEMS_ENH")]
    public partial class LabelItemsEnh
    {
        [Key]
        [Column("ENH_LABEL_ITEM_GUID")]
        public Guid EnhLabelItemGuid { get; set; }
        [Column("ENH_LABEL_GUID")]
        public Guid EnhLabelGuid { get; set; }
        [Column("LINE_NUMBER")]
        public short LineNumber { get; set; }
        [Required]
        [Column("TEXT")]
        [StringLength(300)]
        [Unicode(false)]
        public string Text { get; set; }
    }
}