// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("LICENSES")]
    public partial class License
    {
        [Key]
        [Column("CONTROL")]
        [StringLength(200)]
        [Unicode(false)]
        public string Control { get; set; }
        [Required]
        [Column("LICENSE")]
        [StringLength(200)]
        [Unicode(false)]
        public string License1 { get; set; }
        [Column("KEY_ROW_GUID")]
        public Guid KeyRowGuid { get; set; }
    }
}