// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    public partial class MergeExclusion
    {
        [Key]
        public Guid ExGuid { get; set; }
        [Required]
        [StringLength(256)]
        [Unicode(false)]
        public string TableName { get; set; }
        public byte MergeType { get; set; }
        public bool? Exclude { get; set; }
    }
}