// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("MR_DX_ALs")]
    public partial class MrDxAl
    {
        [Key]
        public Guid KeyGuid { get; set; }
        public Guid RevisionGuid { get; set; }
        [Column("alGuid")]
        public Guid AlGuid { get; set; }
    }
}