// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("PATIENT_DEFAULTS")]
    [Index(nameof(PracticeVid), Name = "IX_PATIENT_DEFAULTS", IsUnique = true)]
    public partial class PatientDefault
    {
        [Key]
        [Column("PK_GUID")]
        public Guid PkGuid { get; set; }
        [Column("PRACTICE_VID")]
        public short PracticeVid { get; set; }
        [Column("SPECIES_GUID")]
        public Guid SpeciesGuid { get; set; }
        [Required]
        [Column("MATURITY_CODE")]
        [StringLength(15)]
        [Unicode(false)]
        public string MaturityCode { get; set; }
        [Required]
        [Column("COMMENT", TypeName = "text")]
        public string Comment { get; set; }
        [Column("DOCTOR_PREFERENCE_GUID")]
        public Guid DoctorPreferenceGuid { get; set; }
        [Required]
        [Column("{0EECC2EA-205E-4F56-90D5-E4101EEF8430}")]
        [StringLength(8)]
        [Unicode(false)]
        public string _0eecc2ea205e4f5690d5E4101eef8430 { get; set; }
        [Required]
        [Column("{B995CD4D-3D01-4CAA-B148-5DF48EA3192B}")]
        [StringLength(8)]
        [Unicode(false)]
        public string B995cd4d3d014caaB1485df48ea3192b { get; set; }
        [Required]
        [Column("{9C0A21A9-9C84-4F2A-A9C0-85725E8DDF3A}")]
        [StringLength(3)]
        [Unicode(false)]
        public string _9c0a21a99c844f2aA9c085725e8ddf3a { get; set; }
        [Required]
        [Column("{6EAECDCB-57E5-41ED-B471-B6C2808A08A3}")]
        [StringLength(40)]
        [Unicode(false)]
        public string _6eaecdcb57e541edB471B6c2808a08a3 { get; set; }
        [Required]
        [Column("{93447AF8-106D-4B6B-ACC9-9FEFC639D1C4}")]
        [StringLength(40)]
        [Unicode(false)]
        public string _93447af8106d4b6bAcc99fefc639d1c4 { get; set; }
        [Column("{A7E9D7BE-0561-4F83-9FB3-BD5C9CE84A7F}", TypeName = "datetime")]
        public DateTime? A7e9d7be05614f839fb3Bd5c9ce84a7f { get; set; }
        [Column("{0C3D2847-69DA-4F19-9B42-5B561A4C1215}", TypeName = "datetime")]
        public DateTime? _0c3d284769da4f199b425b561a4c1215 { get; set; }
        [Column("{50D8FFC6-08F0-4FA4-9B3B-215899CFBCDD}", TypeName = "datetime")]
        public DateTime? _50d8ffc608f04fa49b3b215899cfbcdd { get; set; }
        [Required]
        [Column("{98331712-876E-46D2-B736-DD1B220933C4}")]
        [StringLength(40)]
        [Unicode(false)]
        public string _98331712876e46d2B736Dd1b220933c4 { get; set; }
        [Column("{B799189A-40CC-42EC-88F2-293A98588E33}", TypeName = "datetime")]
        public DateTime? B799189a40cc42ec88f2293a98588e33 { get; set; }
        [Required]
        [Column("{BB7CD819-68F8-4842-A983-CE0EC7E352F3}")]
        [StringLength(15)]
        [Unicode(false)]
        public string Bb7cd81968f84842A983Ce0ec7e352f3 { get; set; }
        [Column("{06997518-1139-4599-B4DC-5C3953639D47}", TypeName = "datetime")]
        public DateTime? _0699751811394599B4dc5c3953639d47 { get; set; }
        [Column("HEALTH_PLAN_GUID")]
        public Guid HealthPlanGuid { get; set; }
        [Required]
        [Column("{AA2F25AE-FF47-4246-BFEF-D42220EEE575}")]
        [StringLength(100)]
        [Unicode(false)]
        public string Aa2f25aeFf474246BfefD42220eee575 { get; set; }
        [Column("{A6D9CCED-E9AE-4BF0-8CDC-8ECEBE4AE757}")]
        public int A6d9ccedE9ae4bf08cdc8ecebe4ae757 { get; set; }
        [Required]
        [Column("{52D6105A-1351-4912-AD1D-52E2CB76F8F9}")]
        [StringLength(100)]
        [Unicode(false)]
        public string _52d6105a13514912Ad1d52e2cb76f8f9 { get; set; }
        [Required]
        [Column("{55F43305-EF48-4445-ABC2-A2AF670D598A}")]
        [StringLength(100)]
        [Unicode(false)]
        public string _55f43305Ef484445Abc2A2af670d598a { get; set; }
        [Required]
        [Column("{70A7D417-B2A8-4D32-B203-CBD782EAB9F9}", TypeName = "text")]
        public string _70a7d417B2a84d32B203Cbd782eab9f9 { get; set; }
        [Required]
        [Column("{5A0C284C-C2B2-4B7E-A397-7B321424D944}")]
        [StringLength(8)]
        [Unicode(false)]
        public string _5a0c284cC2b24b7eA3977b321424d944 { get; set; }
        [Column("TRAINER_GUID")]
        public Guid TrainerGuid { get; set; }
    }
}