// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("PP_DBVIEW_COLUMNS")]
    public partial class PpDbviewColumn
    {
        [Key]
        [Column("DBCOL_GUID")]
        public Guid DbcolGuid { get; set; }
        [Column("USER_GUID")]
        public Guid UserGuid { get; set; }
        [Required]
        [Column("LOCATION_ID")]
        [StringLength(10)]
        [Unicode(false)]
        public string LocationId { get; set; }
        [Column("DBVIEW_COL")]
        public short DbviewCol { get; set; }
        [Column("COLWIDTH")]
        public int Colwidth { get; set; }
    }
}