// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("PP_DBVIEW_SETTINGS")]
    public partial class PpDbviewSetting
    {
        [Key]
        [Column("DBVIEW_GUID")]
        public Guid DbviewGuid { get; set; }
        [Column("USER_GUID")]
        public Guid UserGuid { get; set; }
        [Required]
        [Column("LOCATION_ID")]
        [StringLength(10)]
        [Unicode(false)]
        public string LocationId { get; set; }
        [Column("CLIENT_FORECOLOR")]
        public int ClientForecolor { get; set; }
        [Required]
        [Column("CLIENT_FONTNAME")]
        [StringLength(100)]
        [Unicode(false)]
        public string ClientFontname { get; set; }
        [Column("CLIENT_FONTSIZE")]
        public short ClientFontsize { get; set; }
        [Column("CLIENT_FONTBOLD")]
        public bool ClientFontbold { get; set; }
        [Column("CLIENT_FONTITALICS")]
        public bool ClientFontitalics { get; set; }
        [Column("CLIENT_FONT3D")]
        public short ClientFont3d { get; set; }
        [Column("CLIENT_STYLE")]
        public short ClientStyle { get; set; }
        [Column("CIMAGE_SIZE")]
        public short CimageSize { get; set; }
        [Column("PIMAGE_SIZE")]
        public short PimageSize { get; set; }
        [Column("PET_DROPHEIGHT")]
        public int PetDropheight { get; set; }
        [Column("PET_DROPWIDTH")]
        public int PetDropwidth { get; set; }
        [Column("PET_SHOWICONS")]
        public bool PetShowicons { get; set; }
        [Column("CNAME_WIDTH")]
        public int CnameWidth { get; set; }
        [Column("PNAME_WIDTH")]
        public int PnameWidth { get; set; }
        [Column("CREATE_DATE_TIME", TypeName = "datetime")]
        public DateTime CreateDateTime { get; set; }
        [Required]
        [Column("AUTO_PNOTES")]
        public bool? AutoPnotes { get; set; }
    }
}