// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("PRODUCTS")]
    public partial class Product
    {
        [Key]
        [Column("REVISION_GUID")]
        public Guid RevisionGuid { get; set; }
        [Column("PROD_GUID")]
        public Guid ProdGuid { get; set; }
        [Column("PRODM_GUID")]
        public Guid ProdmGuid { get; set; }
        [Column("PRACTICE_VID")]
        public short PracticeVid { get; set; }
        [Column("AVAILABLE")]
        public bool Available { get; set; }
        [Column("TYPE_OF_PRODUCT")]
        public short TypeOfProduct { get; set; }
        [Column("RESTRICT_EMPLOYEES")]
        public bool RestrictEmployees { get; set; }
        [Column("PKG_FEE", TypeName = "money")]
        public decimal PkgFee { get; set; }
        [Column("PRICE_IS_FIXED")]
        public bool PriceIsFixed { get; set; }
        [Column("MIN_PRICE", TypeName = "money")]
        public decimal MinPrice { get; set; }
        [Column("DEF_QTY", TypeName = "money")]
        public decimal DefQty { get; set; }
        [Column("SPECIAL_DISCOUNT_PERCENT")]
        public int SpecialDiscountPercent { get; set; }
        [Column("UNIT_COST", TypeName = "money")]
        public decimal UnitCost { get; set; }
        [Column("HIQTY1", TypeName = "money")]
        public decimal Hiqty1 { get; set; }
        [Column("HIQTY2", TypeName = "money")]
        public decimal Hiqty2 { get; set; }
        [Column("HIQTY3", TypeName = "money")]
        public decimal Hiqty3 { get; set; }
        [Column("HIQTY4", TypeName = "money")]
        public decimal Hiqty4 { get; set; }
        [Column("HIQTY5", TypeName = "money")]
        public decimal Hiqty5 { get; set; }
        [Column("IMARKUP1", TypeName = "money")]
        public decimal Imarkup1 { get; set; }
        [Column("IMARKUP2", TypeName = "money")]
        public decimal Imarkup2 { get; set; }
        [Column("IMARKUP3", TypeName = "money")]
        public decimal Imarkup3 { get; set; }
        [Column("IMARKUP4", TypeName = "money")]
        public decimal Imarkup4 { get; set; }
        [Column("IMARKUP5", TypeName = "money")]
        public decimal Imarkup5 { get; set; }
        [Column("IPRICE1", TypeName = "money")]
        public decimal Iprice1 { get; set; }
        [Column("IPRICE2", TypeName = "money")]
        public decimal Iprice2 { get; set; }
        [Column("IPRICE3", TypeName = "money")]
        public decimal Iprice3 { get; set; }
        [Column("IPRICE4", TypeName = "money")]
        public decimal Iprice4 { get; set; }
        [Column("IPRICE5", TypeName = "money")]
        public decimal Iprice5 { get; set; }
        [Column("EMARKUP1", TypeName = "money")]
        public decimal Emarkup1 { get; set; }
        [Column("EMARKUP2", TypeName = "money")]
        public decimal Emarkup2 { get; set; }
        [Column("EMARKUP3", TypeName = "money")]
        public decimal Emarkup3 { get; set; }
        [Column("EMARKUP4", TypeName = "money")]
        public decimal Emarkup4 { get; set; }
        [Column("EMARKUP5", TypeName = "money")]
        public decimal Emarkup5 { get; set; }
        [Column("EPRICE1", TypeName = "money")]
        public decimal Eprice1 { get; set; }
        [Column("EPRICE2", TypeName = "money")]
        public decimal Eprice2 { get; set; }
        [Column("EPRICE3", TypeName = "money")]
        public decimal Eprice3 { get; set; }
        [Column("EPRICE4", TypeName = "money")]
        public decimal Eprice4 { get; set; }
        [Column("EPRICE5", TypeName = "money")]
        public decimal Eprice5 { get; set; }
        [Column("INVM_GUID")]
        public Guid InvmGuid { get; set; }
        [Column("INV_GUID")]
        public Guid InvGuid { get; set; }
        [Column("INVENTORY_QTY", TypeName = "money")]
        public decimal InventoryQty { get; set; }
        [Column("ROUND_TO_NEAREST")]
        public short RoundToNearest { get; set; }
        [Column("TAX_GUID")]
        public Guid TaxGuid { get; set; }
        [Column("USAGE_TAX_GUID")]
        public Guid UsageTaxGuid { get; set; }
        [Column("ALLOW_PRICE_CHANGE")]
        public bool AllowPriceChange { get; set; }
        [Column("MOD_ALLOW_PRICE_CHANGE")]
        public bool ModAllowPriceChange { get; set; }
        [Column("ALLOW_QTY_CHANGE")]
        public bool AllowQtyChange { get; set; }
        [Column("MOD_ALLOW_QTY_CHANGE")]
        public bool ModAllowQtyChange { get; set; }
        [Column("ALLOW_NAME_CHANGE")]
        public bool AllowNameChange { get; set; }
        [Column("MOD_ALLOW_NAME_CHANGE")]
        public bool ModAllowNameChange { get; set; }
        [Column("ALLOW_DISCOUNTS")]
        public bool AllowDiscounts { get; set; }
        [Column("ALLOW_ZERO_PRICE")]
        public bool AllowZeroPrice { get; set; }
        [Column("ALLOW_TAX_CHANGE")]
        public bool AllowTaxChange { get; set; }
        [Column("MOD_ALLOW_TAX_CHANGE")]
        public bool ModAllowTaxChange { get; set; }
        [Column("ALLOW_TAX_EXEMPT")]
        public bool AllowTaxExempt { get; set; }
        [Column("IMAGE_GUID")]
        public Guid? ImageGuid { get; set; }
        [Required]
        [Column("INVOICE_NOTES")]
        [StringLength(1000)]
        [Unicode(false)]
        public string InvoiceNotes { get; set; }
        [Required]
        [Column("ESTIMATE_NOTES")]
        [StringLength(1000)]
        [Unicode(false)]
        public string EstimateNotes { get; set; }
        [Column("SHOW_ON_INVOICE")]
        public bool ShowOnInvoice { get; set; }
        [Column("SHOW_ON_ESTIMATE")]
        public bool ShowOnEstimate { get; set; }
        [Column("CREATE_DATE_TIME", TypeName = "datetime")]
        public DateTime CreateDateTime { get; set; }
        [Column("CREATE_USER_GUID")]
        public Guid CreateUserGuid { get; set; }
        [Column("CREATE_WORKSTATION_GUID")]
        public Guid CreateWorkstationGuid { get; set; }
        [Column("DELETED")]
        public bool Deleted { get; set; }
        [Column("CLIENT_NOT_ALLOWED")]
        public bool ClientNotAllowed { get; set; }
        [Column("SOAP_TAB")]
        public short SoapTab { get; set; }
        [Column("RESTRICT_SPECIES")]
        public bool RestrictSpecies { get; set; }
        [Column("RESTRICT_SEX")]
        public bool RestrictSex { get; set; }
        [Column("PRICE_OF_1", TypeName = "money")]
        public decimal PriceOf1 { get; set; }
        [Column("DEF_HI_QTY", TypeName = "money")]
        public decimal DefHiQty { get; set; }
        [Column("DEF_PRIORITY")]
        public int DefPriority { get; set; }
        [Column("DEF_STATUS")]
        public int DefStatus { get; set; }
        [Column("DEF_TIME_DUE", TypeName = "datetime")]
        public DateTime? DefTimeDue { get; set; }
        [Column("NUM_DAYS_DUE")]
        public int NumDaysDue { get; set; }
        [Required]
        [Column("DEF_COMMENT")]
        [StringLength(2000)]
        [Unicode(false)]
        public string DefComment { get; set; }
        [Column("MEMO", TypeName = "text")]
        public string Memo { get; set; }
        [Column("RESTRICT_AGE")]
        public bool RestrictAge { get; set; }
        [Column("RESTRICT_WEIGHT")]
        public bool RestrictWeight { get; set; }
        [Column("START_AGE")]
        public int StartAge { get; set; }
        [Column("END_AGE")]
        public int EndAge { get; set; }
        [Column("START_WEIGHT")]
        public double StartWeight { get; set; }
        [Column("END_WEIGHT")]
        public double EndWeight { get; set; }
        [Column("TIMER_GUID")]
        public Guid TimerGuid { get; set; }
        [Column("PROMPT_INVOICE_NOTES")]
        public bool PromptInvoiceNotes { get; set; }
        [Column("PROMPT_ESTIMATE_NOTES")]
        public bool PromptEstimateNotes { get; set; }
    }
}