// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("PRODUCT_BUNDLES")]
    public partial class ProductBundle
    {
        [Key]
        [Column("BUNDLE_GUID")]
        public Guid BundleGuid { get; set; }
        [Column("BUN_PRODM_GUID")]
        public Guid BunProdmGuid { get; set; }
        [Column("BUN_PROD_GUID")]
        public Guid BunProdGuid { get; set; }
        [Column("COMP_PRODM_GUID")]
        public Guid CompProdmGuid { get; set; }
        [Column("COMP_PROD_GUID")]
        public Guid CompProdGuid { get; set; }
        [Column("PRACTICE_VID")]
        public short PracticeVid { get; set; }
        [Required]
        [Column("NAME")]
        [StringLength(40)]
        [Unicode(false)]
        public string Name { get; set; }
        [Column("QTY_OPTION")]
        public short QtyOption { get; set; }
        [Column("LOQTY", TypeName = "money")]
        public decimal Loqty { get; set; }
        [Column("HIQTY", TypeName = "money")]
        public decimal Hiqty { get; set; }
        [Column("PRICE_OPTION")]
        public short PriceOption { get; set; }
        [Column("LOPRICE", TypeName = "money")]
        public decimal Loprice { get; set; }
        [Column("HIPRICE", TypeName = "money")]
        public decimal Hiprice { get; set; }
        [Column("ADD_PRICE_TO_BUNDLE")]
        public bool AddPriceToBundle { get; set; }
        [Required]
        [Column("DISCOUNT_NAME")]
        [StringLength(30)]
        [Unicode(false)]
        public string DiscountName { get; set; }
        [Column("DISCOUNT_PERCENT")]
        public int DiscountPercent { get; set; }
        [Column("DISCOUNT_AMOUNT", TypeName = "money")]
        public decimal DiscountAmount { get; set; }
        [Required]
        [Column("BULLET")]
        [StringLength(1)]
        [Unicode(false)]
        public string Bullet { get; set; }
        [Column("DISPLAY_ORDER")]
        public int DisplayOrder { get; set; }
        [Column("SELECTED_ON_PREVIEW")]
        public bool SelectedOnPreview { get; set; }
        [Column("CREATE_DATE_TIME", TypeName = "datetime")]
        public DateTime CreateDateTime { get; set; }
        [Column("CREATE_USER_GUID")]
        public Guid CreateUserGuid { get; set; }
        [Column("CREATE_WORKSTATION_GUID")]
        public Guid CreateWorkstationGuid { get; set; }
        [Column("CORP_BUNDLE_LINK_GUID")]
        public Guid CorpBundleLinkGuid { get; set; }
    }
}