// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("PRODUCT_RECHECKS")]
    public partial class ProductRecheck
    {
        [Key]
        [Column("PROD_RECHECK_GUID")]
        public Guid ProdRecheckGuid { get; set; }
        [Column("PROD_GUID")]
        public Guid ProdGuid { get; set; }
        [Column("PRODM_GUID")]
        public Guid ProdmGuid { get; set; }
        [Column("PRACTICE_VID")]
        public short PracticeVid { get; set; }
        [Column("RECHECK_GUID")]
        public Guid RecheckGuid { get; set; }
        [Column("DAYS_TO_ADD")]
        public short DaysToAdd { get; set; }
        [Column("RECHECK_CAT_GUID")]
        public Guid RecheckCatGuid { get; set; }
        [Column("PRINT_ON_INVOICE")]
        public bool PrintOnInvoice { get; set; }
        [Required]
        [Column("DESCRIPTION")]
        [StringLength(250)]
        [Unicode(false)]
        public string Description { get; set; }
        [Required]
        [Column("NOTES")]
        [StringLength(2500)]
        [Unicode(false)]
        public string Notes { get; set; }
        [Column("CREATE_DATE_TIME", TypeName = "datetime")]
        public DateTime CreateDateTime { get; set; }
        [Column("CREATE_USER_GUID")]
        public Guid CreateUserGuid { get; set; }
        [Column("CREATE_WORKSTATION_GUID")]
        public Guid CreateWorkstationGuid { get; set; }
        [Column("DELETED")]
        public bool Deleted { get; set; }
        [Column("WHEN_CODE")]
        public short WhenCode { get; set; }
        [Column("REVIEW_FLAG")]
        public bool ReviewFlag { get; set; }
    }
}