// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("PRODUCT_DB_INTERFACE")]
    public partial class ProductDbInterface
    {
        [Key]
        [Column("PROD_DB_GUID")]
        public Guid ProdDbGuid { get; set; }
        [Column("PROD_GUID")]
        public Guid ProdGuid { get; set; }
        [Column("PRODM_GUID")]
        public Guid ProdmGuid { get; set; }
        [Column("PRACTICE_VID")]
        public short PracticeVid { get; set; }
        [Column("TABLE_TYPE")]
        public short TableType { get; set; }
        [Required]
        [Column("SOURCE_FIELD")]
        [StringLength(50)]
        [Unicode(false)]
        public string SourceField { get; set; }
        [Column("OPERATION")]
        public short Operation { get; set; }
        [Required]
        [Column("DEF_VALUE")]
        [StringLength(1000)]
        [Unicode(false)]
        public string DefValue { get; set; }
        [Column("DISPLAY_VALUE")]
        [StringLength(1000)]
        [Unicode(false)]
        public string DisplayValue { get; set; }
        [Column("CREATE_DATE_TIME", TypeName = "datetime")]
        public DateTime CreateDateTime { get; set; }
        [Column("CREATE_USER_GUID")]
        public Guid CreateUserGuid { get; set; }
        [Column("CREATE_WORKSTATION_GUID")]
        public Guid CreateWorkstationGuid { get; set; }
        [Column("DELETED")]
        public bool Deleted { get; set; }
        [Column("WHEN_CODE")]
        public short WhenCode { get; set; }
    }
}