// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("PURCHASE_ORDERS")]
    public partial class PurchaseOrder
    {
        [Key]
        [Column("PO_GUID")]
        public Guid PoGuid { get; set; }
        [Column("PO_VID")]
        public int PoVid { get; set; }
        [Column("PRACTICE_VID")]
        public short PracticeVid { get; set; }
        [Column("VENDOR_GUID")]
        public Guid VendorGuid { get; set; }
        [Column("VENDOR_CONTACT_GUID")]
        public Guid VendorContactGuid { get; set; }
        [Column("STATUS")]
        public short Status { get; set; }
        [Column("WKST_LOCK_GUID")]
        public Guid WkstLockGuid { get; set; }
        [Column("OPEN_DATE", TypeName = "datetime")]
        public DateTime OpenDate { get; set; }
        [Column("CLOSE_DATE", TypeName = "datetime")]
        public DateTime? CloseDate { get; set; }
        [Column("TOTAL_COST_OF_ITEMS", TypeName = "money")]
        public decimal TotalCostOfItems { get; set; }
        [Column("SHIPPING_COST", TypeName = "money")]
        public decimal ShippingCost { get; set; }
        [Column("TAX_COST", TypeName = "money")]
        public decimal TaxCost { get; set; }
        [Column("TOTAL_PKG_QTY_ORDERED", TypeName = "money")]
        public decimal TotalPkgQtyOrdered { get; set; }
        [Column("TOTAL_PKG_QTY_RECEIVED", TypeName = "money")]
        public decimal TotalPkgQtyReceived { get; set; }
        [Column("ESTIMATED_ARRIVAL_DATE", TypeName = "datetime")]
        public DateTime EstimatedArrivalDate { get; set; }
        [Column("CREATED_EMP_REVISION_GUID")]
        public Guid CreatedEmpRevisionGuid { get; set; }
        [Column("MODIFIED_EMP_REVISION_GUID")]
        public Guid ModifiedEmpRevisionGuid { get; set; }
        [Column("LAST_MODIFIED_DATE", TypeName = "datetime")]
        public DateTime LastModifiedDate { get; set; }
        [Column("LAST_MODIFIED_USER_GUID")]
        public Guid LastModifiedUserGuid { get; set; }
        [Column("LAST_MODIFIED_WORKSTATION_GUID")]
        public Guid LastModifiedWorkstationGuid { get; set; }
        [Column("CREATE_DATE", TypeName = "datetime")]
        public DateTime CreateDate { get; set; }
        [Column("CREATE_USER_GUID")]
        public Guid CreateUserGuid { get; set; }
        [Column("CREATE_WORKSTATION_GUID")]
        public Guid CreateWorkstationGuid { get; set; }
        [Column("DELETED")]
        public bool Deleted { get; set; }
        [Column("TOTAL_UNIT_QTY_ORDERED", TypeName = "money")]
        public decimal TotalUnitQtyOrdered { get; set; }
        [Column("TOTAL_UNIT_QTY_RECEIVED", TypeName = "money")]
        public decimal TotalUnitQtyReceived { get; set; }
        [Required]
        [Column("VENDOR_PO_VID")]
        [StringLength(50)]
        [Unicode(false)]
        public string VendorPoVid { get; set; }
        [Column("CORP_ORDERS")]
        public bool CorpOrders { get; set; }
        [Column("CORP_PO_VID")]
        public int CorpPoVid { get; set; }
        [Column("PRACTICE_GUID")]
        public Guid PracticeGuid { get; set; }
        [Required]
        [Column("WEB_PO_STATUS")]
        [StringLength(100)]
        [Unicode(false)]
        public string WebPoStatus { get; set; }
        [Required]
        [Column("VENDOR_NAME")]
        [StringLength(100)]
        [Unicode(false)]
        public string VendorName { get; set; }
        [Column("SENT_TO_GATEWAY")]
        public bool SentToGateway { get; set; }
    }
}