// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("REM_REPLACE_HISTORY")]
    public partial class RemReplaceHistory
    {
        [Key]
        [Column("REP_HIST_GUID")]
        public Guid RepHistGuid { get; set; }
        [Column("REMOTE_GUID")]
        public Guid RemoteGuid { get; set; }
        [Column("REP_GUID")]
        public Guid RepGuid { get; set; }
        [Column("CREATE_DATE_TIME", TypeName = "datetime")]
        public DateTime CreateDateTime { get; set; }
        [Column("OLD_GUID")]
        public Guid OldGuid { get; set; }
        [Column("NEW_GUID")]
        public Guid? NewGuid { get; set; }
        [Required]
        [Column("TABLE_NAME")]
        [StringLength(255)]
        [Unicode(false)]
        public string TableName { get; set; }
        [Required]
        [Column("FIELD_NAME")]
        [StringLength(255)]
        [Unicode(false)]
        public string FieldName { get; set; }
        [Column("CONDITIONS")]
        [StringLength(500)]
        [Unicode(false)]
        public string Conditions { get; set; }
        [Column("PRACTICE_VID")]
        public int PracticeVid { get; set; }
    }
}