// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("REM_SYNC_HISTORY")]
    public partial class RemSyncHistory
    {
        [Key]
        [Column("HISTORY_GUID")]
        public Guid HistoryGuid { get; set; }
        [Column("REMOTE_GUID")]
        public Guid RemoteGuid { get; set; }
        [Column("SYNC_DATE", TypeName = "datetime")]
        public DateTime SyncDate { get; set; }
        [Column("SYNC_TYPE")]
        public int SyncType { get; set; }
        [Column("SYNC_NUM")]
        public int SyncNum { get; set; }
        [Column("user_guid")]
        public Guid UserGuid { get; set; }
        [Column("result")]
        public int Result { get; set; }
    }
}