// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("REPORTS_AVAILABILITY")]
    public partial class ReportsAvailability
    {
        [Key]
        [Column("REPORT_AVAIL_GUID")]
        public Guid ReportAvailGuid { get; set; }
        [Column("USER_GUID")]
        public Guid UserGuid { get; set; }
        [Required]
        [Column("REPORT_CODE")]
        [StringLength(10)]
        [Unicode(false)]
        public string ReportCode { get; set; }
        [Column("AVAILABLE_TO_PRINT")]
        public bool AvailableToPrint { get; set; }
        [Column("MODIFY_DEFAULTS")]
        public bool ModifyDefaults { get; set; }
        [Column("PRACTICE_VID")]
        public short PracticeVid { get; set; }
    }
}