// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("RESERVATIONPATIENTS")]
    public partial class Reservationpatient
    {
        [Key]
        [Column("RESERVATION_PATIENT_GUID")]
        public Guid ReservationPatientGuid { get; set; }
        [Column("PRACTICE_VID")]
        public short PracticeVid { get; set; }
        [Column("RESERVATION_GUID")]
        public Guid ReservationGuid { get; set; }
        [Column("PATIENT_GUID")]
        public Guid PatientGuid { get; set; }
        [Required]
        [Column("COMMENTS", TypeName = "text")]
        public string Comments { get; set; }
        [Column("DELETED")]
        public bool Deleted { get; set; }
    }
}