// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("RESERVATIONDAYS")]
    public partial class Reservationday
    {
        [Key]
        [Column("RESERVATION_DAY_GUID")]
        public Guid ReservationDayGuid { get; set; }
        [Column("PRACTICE_VID")]
        public short PracticeVid { get; set; }
        [Column("RESERVATION_GUID")]
        public Guid ReservationGuid { get; set; }
        [Column("CAGE_GUID")]
        public Guid CageGuid { get; set; }
        [Column("RSV_DATE", TypeName = "datetime")]
        public DateTime RsvDate { get; set; }
        [Column("DELETED")]
        public bool Deleted { get; set; }
        [Column("AM")]
        public bool Am { get; set; }
    }
}