// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("RX_SIGS")]
    public partial class RxSig
    {
        [Key]
        [Column("SIG_GUID")]
        public Guid SigGuid { get; set; }
        [Required]
        [Column("CODE")]
        [StringLength(10)]
        [Unicode(false)]
        public string Code { get; set; }
        [Column("ENABLE")]
        public bool Enable { get; set; }
        [Required]
        [Column("SIGLINE1")]
        [StringLength(50)]
        [Unicode(false)]
        public string Sigline1 { get; set; }
        [Required]
        [Column("SIGLINE2")]
        [StringLength(50)]
        [Unicode(false)]
        public string Sigline2 { get; set; }
        [Required]
        [Column("SIGLINE3")]
        [StringLength(50)]
        [Unicode(false)]
        public string Sigline3 { get; set; }
        [Required]
        [Column("SIGLINE4")]
        [StringLength(50)]
        [Unicode(false)]
        public string Sigline4 { get; set; }
        [Required]
        [Column("SIGLINE5")]
        [StringLength(50)]
        [Unicode(false)]
        public string Sigline5 { get; set; }
        [Column("CREATE_DATE_TIME", TypeName = "datetime")]
        public DateTime CreateDateTime { get; set; }
        [Column("CREATE_USER_GUID")]
        public Guid CreateUserGuid { get; set; }
        [Column("CREATE_WORKSTATION_GUID")]
        public Guid CreateWorkstationGuid { get; set; }
    }
}