// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Keyless]
    [Table("_SESSIONS")]
    public partial class Session
    {
        [Column("SESSION_GUID")]
        public Guid SessionGuid { get; set; }
        [Required]
        [Column("SESSION_ID")]
        [StringLength(1000)]
        [Unicode(false)]
        public string SessionId { get; set; }
        [Column("CREATE_DATE_TIME", TypeName = "datetime")]
        public DateTime CreateDateTime { get; set; }
        [Required]
        [Column("hostname")]
        [StringLength(128)]
        public string Hostname { get; set; }
        [Required]
        [Column("hostprocess")]
        [StringLength(10)]
        public string Hostprocess { get; set; }
        [Column("WSGuid")]
        public Guid Wsguid { get; set; }
        public Guid UserGuid { get; set; }
    }
}