// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("SETUP_MODULE_SCREENS")]
    public partial class SetupModuleScreen
    {
        [Key]
        [Column("MENU_ID")]
        [StringLength(40)]
        [Unicode(false)]
        public string MenuId { get; set; }
        [Required]
        [Column("CATEGORY")]
        [StringLength(100)]
        [Unicode(false)]
        public string Category { get; set; }
        [Column("RESIZE")]
        public bool Resize { get; set; }
        [Column("SHOW")]
        public bool Show { get; set; }
        [Column("KEY_ROW_GUID")]
        public Guid KeyRowGuid { get; set; }
    }
}