// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("TECH_LOG")]
    public partial class TechLog
    {
        [Key]
        [Column("ENTRY_GUID")]
        public Guid EntryGuid { get; set; }
        [Required]
        [Column("ID")]
        [StringLength(100)]
        [Unicode(false)]
        public string Id { get; set; }
        [Required]
        [Column("ENTRY", TypeName = "text")]
        public string Entry { get; set; }
        [Column("CREATE_DATE_TIME", TypeName = "datetime")]
        public DateTime CreateDateTime { get; set; }
    }
}