// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("TODO_STATUS_COLORS")]
    public partial class TodoStatusColor
    {
        [Key]
        [Column("GUID")]
        public Guid Guid { get; set; }
        [Column("PRACTICE_VID")]
        public short PracticeVid { get; set; }
        [Column("NOT_COMPLETED_COLOR")]
        public int NotCompletedColor { get; set; }
        [Column("COMPLETED_ON_TIME_COLOR")]
        public int CompletedOnTimeColor { get; set; }
        [Column("OVER_DUE_COLOR")]
        public int OverDueColor { get; set; }
        [Column("COMPLETED_LATE_COLOR")]
        public int CompletedLateColor { get; set; }
        [Column("CREATE_DATE_TIME", TypeName = "datetime")]
        public DateTime CreateDateTime { get; set; }
        [Column("CREATE_USER_GUID")]
        public Guid CreateUserGuid { get; set; }
        [Column("CREATE_WORKSTATION_GUID")]
        public Guid CreateWorkstationGuid { get; set; }
    }
}