// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("TRANS_INTEREST")]
    public partial class TransInterest
    {
        [Key]
        [Column("REVISION_GUID")]
        public Guid RevisionGuid { get; set; }
        [Column("REVISED")]
        public bool Revised { get; set; }
        [Column("TX_INTEREST_GUID")]
        public Guid TxInterestGuid { get; set; }
        [Column("TRANS_GUID")]
        public Guid TransGuid { get; set; }
        [Column("CLIENT_GUID")]
        public Guid ClientGuid { get; set; }
        [Column("AGING_DATE", TypeName = "datetime")]
        public DateTime AgingDate { get; set; }
        [Column("ACTUAL_AMOUNT", TypeName = "money")]
        public decimal ActualAmount { get; set; }
        [Column("AMOUNT_CHARGED", TypeName = "money")]
        public decimal AmountCharged { get; set; }
        [Column("AMOUNT_UNPAID", TypeName = "money")]
        public decimal AmountUnpaid { get; set; }
        [Column("BALANCE_OVERDUE", TypeName = "money")]
        public decimal BalanceOverdue { get; set; }
        [Column("BALANCE_CHARGED_ON", TypeName = "money")]
        public decimal BalanceChargedOn { get; set; }
        [Column("CREATE_DATE_TIME", TypeName = "datetime")]
        public DateTime CreateDateTime { get; set; }
        [Column("CREATE_USER_GUID")]
        public Guid CreateUserGuid { get; set; }
        [Column("CREATE_WORKSTATION_GUID")]
        public Guid CreateWorkstationGuid { get; set; }
        [Column("REMOVED")]
        public bool Removed { get; set; }
        [Column("REV_COUNT")]
        public int RevCount { get; set; }
    }
}