// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("TRANS_PRODUCT_EMPLOYEES")]
    public partial class TransProductEmployee
    {
        [Key]
        [Column("REVISION_GUID")]
        public Guid RevisionGuid { get; set; }
        [Column("REVISED")]
        public bool Revised { get; set; }
        [Column("TX_PROD_EMP_GUID")]
        public Guid TxProdEmpGuid { get; set; }
        [Column("TRANS_GUID")]
        public Guid TransGuid { get; set; }
        [Column("INVOICE_GUID")]
        public Guid InvoiceGuid { get; set; }
        [Column("TX_PROD_GUID")]
        public Guid TxProdGuid { get; set; }
        [Column("PRACTICE_VID")]
        public short PracticeVid { get; set; }
        [Column("CLIENT_GUID")]
        public Guid ClientGuid { get; set; }
        [Column("PATIENT_GUID")]
        public Guid PatientGuid { get; set; }
        [Column("EMP_REVISION_GUID")]
        public Guid EmpRevisionGuid { get; set; }
        [Column("EMPLOYEE_GUID")]
        public Guid EmployeeGuid { get; set; }
        [Column("EGROUP_REV_GUID")]
        public Guid EgroupRevGuid { get; set; }
        [Column("EGROUP_GUID")]
        public Guid EgroupGuid { get; set; }
        [Column("PERCENTAGE")]
        public int Percentage { get; set; }
        [Column("PRACTICE_PRICE", TypeName = "money")]
        public decimal PracticePrice { get; set; }
        [Column("ENTERED_PRICE", TypeName = "money")]
        public decimal EnteredPrice { get; set; }
        [Column("DISCOUNT_AMOUNT", TypeName = "money")]
        public decimal DiscountAmount { get; set; }
        [Column("ADJUSTMENT_AMOUNT", TypeName = "money")]
        public decimal AdjustmentAmount { get; set; }
        [Column("INVOICE_DISCOUNT", TypeName = "money")]
        public decimal InvoiceDiscount { get; set; }
        [Column("UNIT_COST", TypeName = "money")]
        public decimal UnitCost { get; set; }
        [Column("QTY", TypeName = "money")]
        public decimal Qty { get; set; }
        [Column("CREATE_DATE_TIME", TypeName = "datetime")]
        public DateTime CreateDateTime { get; set; }
        [Column("CREATE_USER_GUID")]
        public Guid CreateUserGuid { get; set; }
        [Column("CREATE_WORKSTATION_GUID")]
        public Guid CreateWorkstationGuid { get; set; }
        [Column("REMOVED")]
        public bool Removed { get; set; }
        [Column("REV_COUNT")]
        public int RevCount { get; set; }
        [Column("COMM_PERCENT", TypeName = "money")]
        public decimal CommPercent { get; set; }
    }
}