// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("TRANS_PATIENTS")]
    public partial class TransPatient
    {
        [Key]
        [Column("REVISION_GUID")]
        public Guid RevisionGuid { get; set; }
        [Column("REVISED")]
        public bool Revised { get; set; }
        [Column("TX_ACCOUNT_GUID")]
        public Guid TxAccountGuid { get; set; }
        [Column("TRANS_GUID")]
        public Guid TransGuid { get; set; }
        [Column("INVOICE_GUID")]
        public Guid InvoiceGuid { get; set; }
        [Column("CLIENT_GUID")]
        public Guid ClientGuid { get; set; }
        [Column("PATIENT_GUID")]
        public Guid PatientGuid { get; set; }
        [Column("PRACTICE_VID")]
        public short PracticeVid { get; set; }
        [Column("PERCENT_OWNERSHIP")]
        public int PercentOwnership { get; set; }
        [Column("TOTAL_DUE", TypeName = "money")]
        public decimal TotalDue { get; set; }
        [Column("AMOUNT_UNPAID", TypeName = "money")]
        public decimal AmountUnpaid { get; set; }
        [Column("CREATE_DATE_TIME", TypeName = "datetime")]
        public DateTime CreateDateTime { get; set; }
        [Column("CREATE_USER_GUID")]
        public Guid CreateUserGuid { get; set; }
        [Column("CREATE_WORKSTATION_GUID")]
        public Guid CreateWorkstationGuid { get; set; }
        [Column("REMOVED")]
        public bool Removed { get; set; }
        [Column("REV_COUNT")]
        public int RevCount { get; set; }
        [Required]
        [Column("PATIENT_VISIT")]
        public bool? PatientVisit { get; set; }
        [Column("REFERRAL_SOURCE_GUID")]
        public Guid ReferralSourceGuid { get; set; }
    }
}