// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("TRAVEL_SHEET_PRODUCTS")]
    public partial class TravelSheetProduct
    {
        [Key]
        [Column("TSP_GUID")]
        public Guid TspGuid { get; set; }
        [Column("TRAVEL_GUID")]
        public Guid TravelGuid { get; set; }
        [Column("PRODM_GUID")]
        public Guid ProdmGuid { get; set; }
        [Column("PROD_GUID")]
        public Guid ProdGuid { get; set; }
        [Required]
        [Column("NAME")]
        [StringLength(55)]
        [Unicode(false)]
        public string Name { get; set; }
        [Column("DEFAULT_QTY", TypeName = "money")]
        public decimal DefaultQty { get; set; }
        [Column("CATEGORY")]
        public bool Category { get; set; }
        [Column("ROW")]
        public int Row { get; set; }
        [Column("COL")]
        public int Col { get; set; }
        [Column("COL_GROUP")]
        public int ColGroup { get; set; }
        [Column("DEFAULT_QTY2")]
        public int DefaultQty2 { get; set; }
    }
}