// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("USERS")]
    public partial class User
    {
        [Key]
        [Column("USER_GUID")]
        public Guid UserGuid { get; set; }
        [Required]
        [Column("USER_NAME")]
        [StringLength(30)]
        [Unicode(false)]
        public string UserName { get; set; }
        [Column("DELETE_GUID")]
        public Guid DeleteGuid { get; set; }
        [Column("PRACTICE_VID")]
        public short PracticeVid { get; set; }
        [Required]
        [Column("ABBREV_NAME")]
        [StringLength(5)]
        [Unicode(false)]
        public string AbbrevName { get; set; }
        [Column("MAX_OPEN_MODULES")]
        public int MaxOpenModules { get; set; }
        [Column("CREATE_DATE_TIME", TypeName = "datetime")]
        public DateTime CreateDateTime { get; set; }
        [Column("CREATE_USER_GUID")]
        public Guid CreateUserGuid { get; set; }
        [Column("CREATE_WORKSTATION_GUID")]
        public Guid CreateWorkstationGuid { get; set; }
        [Column("DELETED")]
        public bool Deleted { get; set; }
        [Column("ALT_WKST_GUID")]
        public Guid AltWkstGuid { get; set; }
    }
}