// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("USERS_MR_PREF")]
    public partial class UsersMrPref
    {
        [Key]
        [Column("USER_GUID")]
        public Guid UserGuid { get; set; }
        [Column("PRACTICE_VID")]
        public short PracticeVid { get; set; }
        [Column("CREATE_DATE_TIME", TypeName = "datetime")]
        public DateTime CreateDateTime { get; set; }
        [Column("CREATE_USER_GUID")]
        public Guid CreateUserGuid { get; set; }
        [Column("CREATE_WORKSTATION_GUID")]
        public Guid CreateWorkstationGuid { get; set; }
        [Column("P_NOTE")]
        public int PNote { get; set; }
        [Column("P_DX")]
        public int PDx { get; set; }
        [Column("P_IMAGE")]
        public int PImage { get; set; }
        [Column("P_CASE")]
        public int PCase { get; set; }
        [Column("P_PROB")]
        public int PProb { get; set; }
        [Column("P_LAB")]
        public int PLab { get; set; }
        [Column("P_SURG")]
        public int PSurg { get; set; }
        [Column("P_XRAY")]
        public int PXray { get; set; }
        [Column("P_AUDIO")]
        public int PAudio { get; set; }
        [Column("P_EFORM")]
        public int PEform { get; set; }
        [Column("P_CVTSVC")]
        public int PCvtsvc { get; set; }
        [Column("P_THI")]
        public int PThi { get; set; }
        [Column("P_CERT")]
        public int PCert { get; set; }
        [Column("P_STN")]
        public int PStn { get; set; }
        [Column("P_RCHK")]
        public int PRchk { get; set; }
        [Column("P_SVC")]
        public int PSvc { get; set; }
        [Column("P_MIN")]
        public bool PMin { get; set; }
        [Column("P_MED")]
        public bool PMed { get; set; }
        [Column("P_MAX")]
        public bool PMax { get; set; }
        [Column("C_NOTE")]
        public int CNote { get; set; }
        [Column("C_DX")]
        public int CDx { get; set; }
        [Column("C_IMAGE")]
        public int CImage { get; set; }
        [Column("C_LAB")]
        public int CLab { get; set; }
        [Column("C_SURG")]
        public int CSurg { get; set; }
        [Column("C_XRAY")]
        public int CXray { get; set; }
        [Column("C_AUDIO")]
        public int CAudio { get; set; }
        [Column("C_EFORM")]
        public int CEform { get; set; }
        [Column("C_CVTSVC")]
        public int CCvtsvc { get; set; }
        [Column("C_THI")]
        public int CThi { get; set; }
        [Column("C_CERT")]
        public int CCert { get; set; }
        [Column("C_STN")]
        public int CStn { get; set; }
        [Column("C_SVC")]
        public int CSvc { get; set; }
        [Column("C_RCHK")]
        public int CRchk { get; set; }
        [Column("HEIGHT")]
        public int Height { get; set; }
        [Column("WIDTH")]
        public int Width { get; set; }
        [Column("C_MR_VIEW_EFORM")]
        public Guid CMrViewEform { get; set; }
        [Column("P_MR_VIEW_EFORM")]
        public Guid PMrViewEform { get; set; }
        [Column("P_PROD_NOTES")]
        public int PProdNotes { get; set; }
        [Column("P_RX_INFO")]
        public int PRxInfo { get; set; }
        [Column("C_PROD_NOTES")]
        public int CProdNotes { get; set; }
        [Column("C_RX_INFO")]
        public int CRxInfo { get; set; }
        [Required]
        [Column("FONT_EDIT")]
        [StringLength(100)]
        [Unicode(false)]
        public string FontEdit { get; set; }
        [Required]
        [Column("FONT_VIEW")]
        [StringLength(100)]
        [Unicode(false)]
        public string FontView { get; set; }
        [Column("SIZE_EDIT")]
        public int SizeEdit { get; set; }
        [Column("SIZE_VIEW")]
        public int SizeView { get; set; }
        [Column("LAST_TAB")]
        public int LastTab { get; set; }
        [Column("C_SOAP")]
        public int CSoap { get; set; }
        [Column("P_SOAP")]
        public int PSoap { get; set; }
        [Required]
        [Column("SHOW_PICS")]
        public bool? ShowPics { get; set; }
        [Required]
        [Column("SHOW_LABS")]
        public bool? ShowLabs { get; set; }
        [Column("C_CASE")]
        public int CCase { get; set; }
        [Column("C_PROB")]
        public int CProb { get; set; }
    }
}