// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("VACCINE_FLAGS")]
    public partial class VaccineFlag
    {
        [Key]
        [Column("VF_GUID")]
        public Guid VfGuid { get; set; }
        [Column("PRACTICE_VID")]
        public short PracticeVid { get; set; }
        [Column("FLAG_TYPE")]
        public short FlagType { get; set; }
        [Required]
        [Column("ICON", TypeName = "image")]
        public byte[] Icon { get; set; }
        [Required]
        [Column("INVOICE_ICON", TypeName = "image")]
        public byte[] InvoiceIcon { get; set; }
        [Required]
        [Column("ESTIMATE_ICON", TypeName = "image")]
        public byte[] EstimateIcon { get; set; }
        [Required]
        [Column("DESCRIPTION")]
        [StringLength(500)]
        [Unicode(false)]
        public string Description { get; set; }
        [Column("AVAIL")]
        public bool Avail { get; set; }
        [Column("CREATE_DATE_TIME", TypeName = "datetime")]
        public DateTime CreateDateTime { get; set; }
        [Column("CREATE_USER_GUID")]
        public Guid CreateUserGuid { get; set; }
        [Column("CREATE_WORKSTATION_GUID")]
        public Guid CreateWorkstationGuid { get; set; }
    }
}