// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("VACC_HISTORY")]
    public partial class VaccHistory
    {
        [Key]
        [Column("VACC_HISTORY_GUID")]
        public Guid VaccHistoryGuid { get; set; }
        [Column("PATIENT_GUID")]
        public Guid PatientGuid { get; set; }
        [Required]
        [Column("VACCINE_NAME")]
        [StringLength(30)]
        [Unicode(false)]
        public string VaccineName { get; set; }
        [Column("DATE_DUE", TypeName = "datetime")]
        public DateTime? DateDue { get; set; }
        [Column("DATE_GIVEN", TypeName = "datetime")]
        public DateTime? DateGiven { get; set; }
        [Column("PRACTICE_VID")]
        public short PracticeVid { get; set; }
        [Column("REV_COUNT")]
        public int RevCount { get; set; }
        [Column("CREATE_DATE_TIME", TypeName = "datetime")]
        public DateTime CreateDateTime { get; set; }
        [Column("CREATE_USER_GUID")]
        public Guid CreateUserGuid { get; set; }
        [Column("CREATE_WORKSTATION_GUID")]
        public Guid CreateWorkstationGuid { get; set; }
    }
}