// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("VENDOR_CONTACTS")]
    public partial class VendorContact
    {
        [Key]
        [Column("VC_GUID")]
        public Guid VcGuid { get; set; }
        [Column("VENDOR_GUID")]
        public Guid VendorGuid { get; set; }
        [Column("PRACTICE_VID")]
        public short PracticeVid { get; set; }
        [Required]
        [Column("NAME")]
        [StringLength(40)]
        [Unicode(false)]
        public string Name { get; set; }
        [Required]
        [Column("PHONE1")]
        [StringLength(24)]
        [Unicode(false)]
        public string Phone1 { get; set; }
        [Required]
        [Column("PHONE2")]
        [StringLength(24)]
        [Unicode(false)]
        public string Phone2 { get; set; }
        [Required]
        [Column("FAX")]
        [StringLength(24)]
        [Unicode(false)]
        public string Fax { get; set; }
        [Required]
        [Column("PAGER")]
        [StringLength(50)]
        [Unicode(false)]
        public string Pager { get; set; }
        [Required]
        [Column("EMAIL_ADDRESS")]
        [StringLength(255)]
        [Unicode(false)]
        public string EmailAddress { get; set; }
        [Column("CREATE_DATE_TIME", TypeName = "datetime")]
        public DateTime CreateDateTime { get; set; }
        [Column("CREATE_USER_GUID")]
        public Guid CreateUserGuid { get; set; }
        [Column("CREATE_WORKSTATION_GUID")]
        public Guid CreateWorkstationGuid { get; set; }
        [Column("DELETED")]
        public bool Deleted { get; set; }
    }
}