// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("VENDORS_II_ACCTS")]
    [Index(nameof(IiAcctNum), Name = "VENDORS_II_ACCT_NUM", IsUnique = true)]
    public partial class VendorsIiAcct
    {
        [Key]
        [Column("VENDOR_II_GUID")]
        public Guid VendorIiGuid { get; set; }
        [Required]
        [Column("NAME")]
        [StringLength(100)]
        [Unicode(false)]
        public string Name { get; set; }
        [Required]
        [Column("ABBREV")]
        [StringLength(20)]
        [Unicode(false)]
        public string Abbrev { get; set; }
        [Column("II_ACCT_NUM")]
        public int IiAcctNum { get; set; }
    }
}