// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("VENDORS_SHIPTO_ACCTS")]
    [Index(nameof(VendorGuid), nameof(ShiptoAcctNum), Name = "IX_VENDORS_SHIPTTO_ACCT_NUM", IsUnique = true)]
    public partial class VendorsShiptoAcct
    {
        [Key]
        [Column("VENDOR_SHIPTO_GUID")]
        public Guid VendorShiptoGuid { get; set; }
        [Column("VENDOR_GUID")]
        public Guid VendorGuid { get; set; }
        [Required]
        [Column("SHIPTO_ACCT_NUM")]
        [StringLength(50)]
        [Unicode(false)]
        public string ShiptoAcctNum { get; set; }
        [Required]
        [Column("NAME")]
        [StringLength(100)]
        [Unicode(false)]
        public string Name { get; set; }
    }
}