// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("VETINSITE_CHANGES")]
    public partial class VetinsiteChange
    {
        [Key]
        [Column("MOD_GUID")]
        public Guid ModGuid { get; set; }
        [Column("KEY_GUID")]
        public Guid KeyGuid { get; set; }
        [Column("SUBKEY_GUID")]
        public Guid SubkeyGuid { get; set; }
        [Column("DATE_FIELD", TypeName = "datetime")]
        public DateTime? DateField { get; set; }
        [Required]
        [Column("TABLE_NAME")]
        [StringLength(40)]
        [Unicode(false)]
        public string TableName { get; set; }
        [Required]
        [Column("TYPE")]
        [StringLength(2)]
        [Unicode(false)]
        public string Type { get; set; }
        [Column("OPTIONS")]
        public int Options { get; set; }
        [Column("ORDER_NUM")]
        public int OrderNum { get; set; }
    }
}