// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("WHATIF")]
    public partial class Whatif
    {
        [Key]
        [Column("WHATIFGUID")]
        public Guid Whatifguid { get; set; }
        [Column("SESSIONGUID")]
        public Guid Sessionguid { get; set; }
        [Column("PRODMGUID")]
        public Guid Prodmguid { get; set; }
        [Column("CLIENTGUID")]
        public Guid Clientguid { get; set; }
        [Column("DATECOMPLETED", TypeName = "datetime")]
        public DateTime Datecompleted { get; set; }
        [Required]
        [Column("PCATNAME")]
        [StringLength(50)]
        [Unicode(false)]
        public string Pcatname { get; set; }
        [Required]
        [Column("PTYPENAME")]
        [StringLength(50)]
        [Unicode(false)]
        public string Ptypename { get; set; }
        [Required]
        [Column("PROFITNAME")]
        [StringLength(50)]
        [Unicode(false)]
        public string Profitname { get; set; }
        [Required]
        [Column("PRODCODE")]
        [StringLength(10)]
        [Unicode(false)]
        public string Prodcode { get; set; }
        [Required]
        [Column("PRODNAME")]
        [StringLength(50)]
        [Unicode(false)]
        public string Prodname { get; set; }
        [Column("INSTANCE")]
        public int Instance { get; set; }
        [Column("QTY", TypeName = "money")]
        public decimal Qty { get; set; }
        [Column("OLDPRICE", TypeName = "money")]
        public decimal Oldprice { get; set; }
        [Column("NEWPRICE", TypeName = "money")]
        public decimal Newprice { get; set; }
        [Column("OLDDISCOUNTS", TypeName = "money")]
        public decimal Olddiscounts { get; set; }
        [Column("NEWDISCOUNTS", TypeName = "money")]
        public decimal Newdiscounts { get; set; }
        [Column("ADJUSTMENTS", TypeName = "money")]
        public decimal Adjustments { get; set; }
        [Column("INVOICEDISCOUNTS", TypeName = "money")]
        public decimal Invoicediscounts { get; set; }
    }
}