// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("WORK_SCHEDULE_APPLIED_DATES")]
    public partial class WorkScheduleAppliedDate
    {
        [Key]
        [Column("APPLIED_GUID")]
        public Guid AppliedGuid { get; set; }
        [Column("APPLIED_DATE", TypeName = "datetime")]
        public DateTime AppliedDate { get; set; }
        [Column("W_WEEK_GUID")]
        public Guid WWeekGuid { get; set; }
        [Column("EMPLOYEE_GUID")]
        public Guid EmployeeGuid { get; set; }
        [Column("PRACTICE_VID")]
        public short PracticeVid { get; set; }
        [Column("WORK_FLAG")]
        public short WorkFlag { get; set; }
        [Required]
        [Column("IMAGE_GUID")]
        [StringLength(50)]
        [Unicode(false)]
        public string ImageGuid { get; set; }
        [Column("IMAGE", TypeName = "image")]
        public byte[] Image { get; set; }
        [Column("CREATE_DATE_TIME", TypeName = "datetime")]
        public DateTime CreateDateTime { get; set; }
        [Column("CREATE_USER_GUID")]
        public Guid CreateUserGuid { get; set; }
        [Column("CREATE_WORKSTATION_GUID")]
        public Guid CreateWorkstationGuid { get; set; }
    }
}