// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("WORK_SCHEDULE_APPLIED_TIMES")]
    public partial class WorkScheduleAppliedTime
    {
        [Key]
        [Column("APTIME_GUID")]
        public Guid AptimeGuid { get; set; }
        [Column("APPLIED_GUID")]
        public Guid AppliedGuid { get; set; }
        [Column("START_TIME", TypeName = "datetime")]
        public DateTime StartTime { get; set; }
        [Column("END_TIME", TypeName = "datetime")]
        public DateTime EndTime { get; set; }
        [Column("CREATE_DATE_TIME", TypeName = "datetime")]
        public DateTime CreateDateTime { get; set; }
        [Column("CREATE_USER_GUID")]
        public Guid CreateUserGuid { get; set; }
        [Column("CREATE_WORKSTATION_GUID")]
        public Guid CreateWorkstationGuid { get; set; }
    }
}