// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("WORK_SCHEDULE_IMAGES")]
    public partial class WorkScheduleImage
    {
        [Key]
        [Column("IMAGE_GUID")]
        public Guid ImageGuid { get; set; }
        [Required]
        [Column("IMAGE", TypeName = "image")]
        public byte[] Image { get; set; }
    }
}