// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("WORKSTATIONS")]
    public partial class Workstation1
    {
        [Key]
        [Column("WORKSTATION_GUID")]
        public Guid WorkstationGuid { get; set; }
        [Required]
        [Column("NAME")]
        [StringLength(30)]
        [Unicode(false)]
        public string Name { get; set; }
        [Column("DATE_SETTING")]
        public short DateSetting { get; set; }
        [Column("CURRENCY_SETTING")]
        public int CurrencySetting { get; set; }
        [Column("NUMERIC_SETTING")]
        public int NumericSetting { get; set; }
        [Column("SHOW_BOARDING_ICONS")]
        public bool ShowBoardingIcons { get; set; }
        [Column("CREATE_DATE_TIME", TypeName = "datetime")]
        public DateTime CreateDateTime { get; set; }
        [Column("CD_GUID")]
        public Guid CdGuid { get; set; }
    }
}