// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorBoilerplate.Api.SubModels
{
    [Table("WORKSTATION_CASHDRAWERS")]
    public partial class WorkstationCashdrawer
    {
        [Key]
        [Column("WCD_GUID")]
        public Guid WcdGuid { get; set; }
        [Column("WORKSTATION_GUID")]
        public Guid WorkstationGuid { get; set; }
        [Column("CD_GUID")]
        public Guid CdGuid { get; set; }
        [Required]
        [Column("DEVICE_NAME")]
        [StringLength(255)]
        [Unicode(false)]
        public string DeviceName { get; set; }
        [Column("CREATE_DATE_TIME", TypeName = "datetime")]
        public DateTime CreateDateTime { get; set; }
        [Column("CREATE_USER_GUID")]
        public Guid CreateUserGuid { get; set; }
        [Column("CREATE_WORKSTATION_GUID")]
        public Guid CreateWorkstationGuid { get; set; }
        [Column("CASHDRAWER_EXISTS")]
        public bool CashdrawerExists { get; set; }
        [Required]
        [Column("PRINTER_IS_ATTACHED")]
        public bool? PrinterIsAttached { get; set; }
        [Column("ASCII_CODE")]
        public short AsciiCode { get; set; }
    }
}